{
  "Mayavi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351390"
    ],
    "summaries": [
      "Mayavi fails to build with Python 3.14: TestMayaviGarbageCollection.test_mlab_scene_model_with_gui: IndexError: list index out of range"
    ]
  },
  "ansible": {
    "urls": [],
    "summaries": []
  },
  "ansible-core": {
    "urls": [],
    "summaries": []
  },
  "asv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339908"
    ],
    "summaries": [
      "asv: FTBFS in Fedora rawhide/f42"
    ]
  },
  "bandit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351393"
    ],
    "summaries": [
      "bandit fails to build with Python 3.14: TypeError: Error: Str is not a valid node type in AST"
    ]
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "capstone": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345714"
    ],
    "summaries": [
      "capstone fails to build with Python 3.14: from capstone import *: ImportError: ERROR: fail to load the dynamic library"
    ]
  },
  "ceph": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336913"
    ],
    "summaries": [
      "ceph fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "chirp": {
    "urls": [],
    "summaries": []
  },
  "cjdns": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339969"
    ],
    "summaries": [
      "cjdns: FTBFS in Fedora rawhide/f42"
    ]
  },
  "claws-mail": {
    "urls": [],
    "summaries": []
  },
  "cockpit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350287"
    ],
    "summaries": [
      "cockpit fails to build from source with Python 3.14: AttributeError: module 'asyncio' has no attribute 'SafeChildWatcher'"
    ]
  },
  "conda": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356170"
    ],
    "summaries": [
      "conda fails to build with Python 3.14: tests/test_shell.py: TypeError: 'str' object cannot be interpreted as an integer"
    ]
  },
  "conda-build": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356162"
    ],
    "summaries": [
      "conda-build fails to build with Python 3.14: TypeError: _WorkItem.__init__() takes 3 positional arguments but 5 were given"
    ]
  },
  "copr-backend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351386"
    ],
    "summaries": [
      "copr-backend fails to build with Python 3.14: TestActionWorkerManager.test_add_task_for_running_worker: TypeError: cannot pickle 'itertools.count' object"
    ]
  },
  "criu": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340011"
    ],
    "summaries": [
      "criu: FTBFS in Fedora rawhide/f42"
    ]
  },
  "dftd4": {
    "urls": [],
    "summaries": []
  },
  "diceware": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340075"
    ],
    "summaries": [
      "diceware: FTBFS in Fedora rawhide/f42"
    ]
  },
  "did": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328006"
    ],
    "summaries": [
      "did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'"
    ]
  },
  "ephemeral-port-reserve": {
    "urls": [],
    "summaries": []
  },
  "gdal": {
    "urls": [],
    "summaries": []
  },
  "gnofract4d": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339539"
    ],
    "summaries": [
      "gnofract4d fails to build with Python 3.14: AssertionError: 'ct_sin6 = (0.841471,-0)' != 'ct_sin6 = (0.841471,0)'"
    ]
  },
  "h5py": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339470"
    ],
    "summaries": [
      "h5py fails to build with Python 3.14: ResourceWarning: TestFileObj.test_TemporaryFile: Implicitly cleaning up <_TemporaryFileWrapper file=<_io.BufferedRandom name='/tmp/tmp8pqafmzv'>>"
    ]
  },
  "httpie": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350335"
    ],
    "summaries": [
      "httpie fails to build with Python 3.14: test_lazy_choices_help: AssertionError: Expected 'getter' to not have been called. Called 1 times."
    ]
  },
  "ikiwiki": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340642"
    ],
    "summaries": [
      "ikiwiki: FTBFS in Fedora rawhide/f42"
    ]
  },
  "insight": {
    "urls": [],
    "summaries": []
  },
  "ipython": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356174"
    ],
    "summaries": [
      "ipython fails to build with Python 3.14: AssertionErrors, pexpect.exceptions.TIMEOUTs and more in 12 tests"
    ]
  },
  "kernel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340285"
    ],
    "summaries": [
      "kernel: FTBFS in Fedora rawhide/f42"
    ]
  },
  "kitty": {
    "urls": [],
    "summaries": []
  },
  "kmymoney": {
    "urls": [],
    "summaries": []
  },
  "kvirc": {
    "urls": [],
    "summaries": []
  },
  "lazygal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350502"
    ],
    "summaries": [
      "lazygal: FTBFS in Fedora 41+ due to test_withvideo test failing with FFmpeg 7.1"
    ]
  },
  "libarcus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340716"
    ],
    "summaries": [
      "libarcus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "libpeas": {
    "urls": [],
    "summaries": []
  },
  "libxc": {
    "urls": [],
    "summaries": []
  },
  "llvm": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336915"
    ],
    "summaries": [
      "llvm fails to build with Python 3.14: tools/opt-viewer/suppress.test: AttributeError: type object 'Passed' has no attribute 'demangler_lock'"
    ]
  },
  "monkeytype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356179"
    ],
    "summaries": [
      "monkeytype fails to build with Python 3.14: typing.Union changed with Python 3.14.0a6"
    ]
  },
  "mopidy": {
    "urls": [],
    "summaries": []
  },
  "mopidy-mpd": {
    "urls": [],
    "summaries": []
  },
  "nmstate": {
    "urls": [],
    "summaries": []
  },
  "ocrmypdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357508"
    ],
    "summaries": [
      "ocrmypdf fails to build with Python 3.14: multiprocessing.Process now starts with forkserver method instead of fork, causing pickling error"
    ]
  },
  "onnx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354087"
    ],
    "summaries": [
      "onnx FTBFS due to missing tox configuration"
    ]
  },
  "openapi-python-client": {
    "urls": [],
    "summaries": []
  },
  "paraview": {
    "urls": [],
    "summaries": []
  },
  "pcs": {
    "urls": [],
    "summaries": []
  },
  "poetry": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351383"
    ],
    "summaries": [
      "poetry fails to build with Python 3.14: AssertionError in test_isolated_env_install_discards_requirements_not_needed_by_env and test_python_get_preferred_default"
    ]
  },
  "poezio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341088"
    ],
    "summaries": [
      "poezio: FTBFS in Fedora rawhide/f42"
    ]
  },
  "powerline": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336943"
    ],
    "summaries": [
      "powerline fails to build with Python 3.14: ValueError: argument groups cannot be nested"
    ]
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pychromecast": {
    "urls": [],
    "summaries": []
  },
  "pygsl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341119"
    ],
    "summaries": [
      "pygsl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pysubnettree": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341123"
    ],
    "summaries": [
      "pysubnettree: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pytest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353140"
    ],
    "summaries": [
      "pytest fails to build with Python 3.14: mismatch of expected and actual strings in test output"
    ]
  },
  "python-TestSlide": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350306",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343971"
    ],
    "summaries": [
      "Heads-up: python-TestSlide fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-TestSlide fails to build with Python 3.14: ERROR collecting tests/mock_callable_testslide.py: RuntimeError: dictionary changed size during iteration"
    ]
  },
  "python-aioesphomeapi": {
    "urls": [],
    "summaries": []
  },
  "python-aiokafka": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2346517"
    ],
    "summaries": [
      "python-aiokafka fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-aiounittest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356177"
    ],
    "summaries": [
      "python-aiounittest fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-apsw": {
    "urls": [],
    "summaries": []
  },
  "python-asgiref": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345528"
    ],
    "summaries": [
      "python-asgiref fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-astdoc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349452"
    ],
    "summaries": [
      "python-astdoc fails to build with Python 3.14: 3 doctests fail, e.g.: Expected: <ast.Name object at 0x...> Got: Name(id='int', ctx=Load())"
    ]
  },
  "python-astroid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
    ],
    "summaries": [
      "python-astroid fails to build with Python 3.14: astroid.exceptions.InferenceError: StopIteration raised without any error information."
    ]
  },
  "python-astropy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345524"
    ],
    "summaries": [
      "python-astropy fails to build with Python 3.14: test_info_preserved_pickle_copy_init[arrayswap]: AssertionError: assert dtype('>i4') == dtype('int32')"
    ]
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-atomicwrites": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341128"
    ],
    "summaries": [
      "python-atomicwrites: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-autocommand": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
    ],
    "summaries": [
      "python-autocommand fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341130",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado: FTBFS in Fedora rawhide/f42",
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-awesomeversion": {
    "urls": [],
    "summaries": []
  },
  "python-aws-sam-translator": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353126"
    ],
    "summaries": [
      "python-aws-sam-translator fails to build with Python 3.14: 77 test failures, 4 error"
    ]
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341131",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype: FTBFS in Fedora rawhide/f42",
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-behave": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339094"
    ],
    "summaries": [
      "python-behave fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-blinker": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325193"
    ],
    "summaries": [
      "python-blinker fails to build with Python 3.14: pluggy.PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown."
    ]
  },
  "python-boto3": {
    "urls": [],
    "summaries": []
  },
  "python-boutdata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352553"
    ],
    "summaries": [
      "python-boutdata fails to build with Python 3.14: NotImplementedError: Dataset is not picklable"
    ]
  },
  "python-bsmschema": {
    "urls": [],
    "summaries": []
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-carbon": {
    "urls": [],
    "summaries": []
  },
  "python-catkin_tools": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341134"
    ],
    "summaries": [
      "python-catkin_tools: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-cattrs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343916"
    ],
    "summaries": [
      "python-cattrs fails to build with Python 3.14: TypeError: <class 'tests.strategies.test_include_subclasses.GrandChild'> has no usable non-default attributes"
    ]
  },
  "python-chalice": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342568"
    ],
    "summaries": [
      "python-chalice fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-cmd2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356178"
    ],
    "summaries": [
      "python-cmd2 fails to build with Python 3.14:  ValueError: action 'store_true' is not valid for positional arguments"
    ]
  },
  "python-colcon-cmake": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339465"
    ],
    "summaries": [
      "python-colcon-cmake fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-colcon-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339464"
    ],
    "summaries": [
      "python-colcon-core fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-confuse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
    ],
    "summaries": [
      "python-confuse fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-crcmod": {
    "urls": [],
    "summaries": []
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-cvxopt": {
    "urls": [],
    "summaries": []
  },
  "python-daphne": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341140"
    ],
    "summaries": [
      "python-daphne: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-deepdiff": {
    "urls": [],
    "summaries": []
  },
  "python-django-configurations": {
    "urls": [],
    "summaries": []
  },
  "python-django-contrib-comments": {
    "urls": [],
    "summaries": []
  },
  "python-django-extensions": {
    "urls": [],
    "summaries": []
  },
  "python-django-filter": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336944"
    ],
    "summaries": [
      "python-django-filter fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "python-django-mailman3": {
    "urls": [],
    "summaries": []
  },
  "python-dns-lexicon": {
    "urls": [],
    "summaries": []
  },
  "python-domdf-python-tools": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345519"
    ],
    "summaries": [
      "python-domdf-python-tools fails to build with Python 3.14: tests/test_words.py::test_alpha_sort - AssertionError: Regex pattern did not match."
    ]
  },
  "python-doubleratchet": {
    "urls": [],
    "summaries": []
  },
  "python-etcd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
    ],
    "summaries": [
      "python-etcd fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestWatch.test_watch_indexed_generator.<locals>.watch_value at 0x7f0d39f71dd0>"
    ]
  },
  "python-eth-stdlib": {
    "urls": [],
    "summaries": []
  },
  "python-executing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349436"
    ],
    "summaries": [
      "python-executing fails to build with Python 3.14: 52 test fail during the build"
    ]
  },
  "python-fasjson-client": {
    "urls": [],
    "summaries": []
  },
  "python-flake8-comprehensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351385"
    ],
    "summaries": [
      "python-flake8-comprehensions fails to build with Python 3.14: Unnecessary reversed call around sorted() in 10 tests"
    ]
  },
  "python-flask-caching": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341153"
    ],
    "summaries": [
      "python-flask-caching: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-fs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336951"
    ],
    "summaries": [
      "python-fs fails to build with Python 3.14: AssertionError: 'osfs://///tmp/tmppauy69swfstestosfs/foo' != 'osfs:///tmp/tmppauy69swfstestosfs/foo'"
    ]
  },
  "python-fsleyes-widgets": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336911"
    ],
    "summaries": [
      "python-fsleyes-widgets fails to build with Python 3.14: AssertionError: assert 'file:/home/b...htmlfile.html' == 'file:///home...htmlfile.html'"
    ]
  },
  "python-fsspec": {
    "urls": [],
    "summaries": []
  },
  "python-giacpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341608"
    ],
    "summaries": [
      "python-giacpy: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-gitlab": {
    "urls": [],
    "summaries": []
  },
  "python-googleapis-common-protos": {
    "urls": [],
    "summaries": []
  },
  "python-gphoto2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341158"
    ],
    "summaries": [
      "python-gphoto2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-gstreamer1": {
    "urls": [],
    "summaries": []
  },
  "python-hamcrest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2346504"
    ],
    "summaries": [
      "python-hamcrest fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-hl7": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341161"
    ],
    "summaries": [
      "python-hl7: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-howdoi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342558"
    ],
    "summaries": [
      "python-howdoi fails to build with Python 3.14: AssertionError: 'ERROR: Unable to reach google. Do you need to use a proxy? + json.decoder.JSONDecodeError"
    ]
  },
  "python-imbalanced-learn": {
    "urls": [],
    "summaries": []
  },
  "python-inject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
    ],
    "summaries": [
      "python-inject fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-injector": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341165"
    ],
    "summaries": [
      "python-injector: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-irc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
    ],
    "summaries": [
      "python-irc fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-janus": {
    "urls": [],
    "summaries": []
  },
  "python-jedi": {
    "urls": [],
    "summaries": []
  },
  "python-jiter": {
    "urls": [],
    "summaries": []
  },
  "python-josepy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342557"
    ],
    "summaries": [
      "python-josepy fails to build with Python 3.14: 7 tests fail with ValueError: Field `alg` in JSONObject `Header` has no type annotation."
    ]
  },
  "python-jupyter-server": {
    "urls": [],
    "summaries": []
  },
  "python-jupytext": {
    "urls": [],
    "summaries": []
  },
  "python-lfpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341168"
    ],
    "summaries": [
      "python-lfpy: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-libcst": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356182"
    ],
    "summaries": [
      "python-libcst fails to build with Python 3.14: Exception: Logic error, unexpected top level type! when importing libcst.codegen.gen_matcher_classes"
    ]
  },
  "python-loguru": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356181"
    ],
    "summaries": [
      "python-loguru fails to build with Python 3.14: test_exception_modern[type_hints-minimum_python_version0]: m<class 'typing.Union'>"
    ]
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-metakernel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357903"
    ],
    "summaries": [
      "python-metakernel fails to build with Python 3.14: AssertionError in test_parallel_magic"
    ]
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-nbclient": {
    "urls": [],
    "summaries": []
  },
  "python-neatdend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341170"
    ],
    "summaries": [
      "python-neatdend: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-netpyne": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341171"
    ],
    "summaries": [
      "python-netpyne: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-network-runner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341172"
    ],
    "summaries": [
      "python-network-runner: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-neurotune": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341173"
    ],
    "summaries": [
      "python-neurotune: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-nikola": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341174"
    ],
    "summaries": [
      "python-nikola: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-notify2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341175"
    ],
    "summaries": [
      "python-notify2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-ollama": {
    "urls": [],
    "summaries": []
  },
  "python-osc-lib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351387"
    ],
    "summaries": [
      "python-osc-lib fails to build with Python 3.14: testtools.matchers._impl.MismatchError in 4 tests"
    ]
  },
  "python-oslo-config": {
    "urls": [],
    "summaries": []
  },
  "python-packvers": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341178"
    ],
    "summaries": [
      "python-packvers: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pamela": {
    "urls": [],
    "summaries": []
  },
  "python-pika": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351384"
    ],
    "summaries": [
      "python-pika fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pip": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335909"
    ],
    "summaries": [
      "python-pip fails to build with Python 3.14: AssertionError: assert 'file:/tmp/file' == 'file:///tmp/file'"
    ]
  },
  "python-pkginfo": {
    "urls": [],
    "summaries": []
  },
  "python-praw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342562"
    ],
    "summaries": [
      "python-praw fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-priority": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341182"
    ],
    "summaries": [
      "python-priority: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pydantic-settings": {
    "urls": [],
    "summaries": []
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pyforgejo": {
    "urls": [],
    "summaries": []
  },
  "python-pymdown-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350300",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336948"
    ],
    "summaries": [
      "Heads-up: python-pymdown-extensions fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-pymdown-extensions fails to build with Python 3.14: TestAbsolute.test_relative_path and TestAbsoluteFileScheme.test_relative_path AssertionErrors"
    ]
  },
  "python-pymeeus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341186"
    ],
    "summaries": [
      "python-pymeeus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pymongo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356166",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341188"
    ],
    "summaries": [
      "python-pymongo fails to build with Python 3.14: DeprecationWarning: 'asyncio.iscoroutinefunction' and 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16",
      "python-pymongo: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pynamodb": {
    "urls": [],
    "summaries": []
  },
  "python-pynn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341189"
    ],
    "summaries": [
      "python-pynn: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyopencl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341190"
    ],
    "summaries": [
      "python-pyopencl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyopengl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341191"
    ],
    "summaries": [
      "python-pyopengl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pypet": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341192"
    ],
    "summaries": [
      "python-pypet: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyphi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341193"
    ],
    "summaries": [
      "python-pyphi: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pysaml2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341199"
    ],
    "summaries": [
      "python-pysaml2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pysdl2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339020"
    ],
    "summaries": [
      "python-pysdl2: FTBFS in Fedora Rawhide"
    ]
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pytesseract": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341201"
    ],
    "summaries": [
      "python-pytesseract: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pytest-aiohttp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339466"
    ],
    "summaries": [
      "python-pytest-aiohttp fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-pytest-lsp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349451"
    ],
    "summaries": [
      "python-pytest-lsp fails to build with Python 3.14: warnings counts differ, resulting in AssertionError in 3 tests"
    ]
  },
  "python-pytest-testinfra": {
    "urls": [],
    "summaries": []
  },
  "python-python-ulid": {
    "urls": [],
    "summaries": []
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-pyvlx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
    ],
    "summaries": [
      "python-pyvlx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-rdflib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343978",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336891"
    ],
    "summaries": [
      "python-rdflib fails to build with Python 3.14: AttributeError: term 'value' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'",
      "python-rdflib fails to build with Python 3.14: \"TypeError: '<' not supported between instances of 'Literal' and 'Literal'\""
    ]
  },
  "python-reactivex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
    ],
    "summaries": [
      "python-reactivex fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-redis": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345526"
    ],
    "summaries": [
      "python-redis fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f10027f31c0>"
    ]
  },
  "python-remoto": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341205"
    ],
    "summaries": [
      "python-remoto: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-rich": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350303",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339510"
    ],
    "summaries": [
      "Heads-up: python-rich fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-rich fails to build with Python 3.14: 5 test fail"
    ]
  },
  "python-rope": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351391"
    ],
    "summaries": [
      "python-rope fails to build with Python 3.14: ImportError while loading conftest '/builddir/build/BUILD/python-rope-1.13.0-build/rope-1.13.0/ropetest/conftest.py'.: AssertionError: assert sys.version_info < (3, 8)"
    ]
  },
  "python-rosdep": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341207"
    ],
    "summaries": [
      "python-rosdep: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-rpmautospec": {
    "urls": [],
    "summaries": []
  },
  "python-rq": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342234"
    ],
    "summaries": [
      "python-rq fails to build with Python 3.14: test_worker.py::HerokuWorkerShutdownTestCase::test_handle_shutdown_request shuts down the whole build"
    ]
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-s3transfer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326933"
    ],
    "summaries": [
      "python-s3transfer fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <class 'tests.unit.test_compat.TestBaseManager.create_pid_manager.<locals>.PIDManager'>"
    ]
  },
  "python-scikit-build": {
    "urls": [],
    "summaries": []
  },
  "python-scikit-build-core": {
    "urls": [],
    "summaries": []
  },
  "python-scikit-learn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353125"
    ],
    "summaries": [
      "python-scikit-learn fails to build with Python 3.14: AssertionError in test_warn_if_metric_bool_data_no_bool and test_open_openml_url_retry_on_network_error"
    ]
  },
  "python-shortuuid": {
    "urls": [],
    "summaries": []
  },
  "python-simframe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352552"
    ],
    "summaries": [
      "python-simframe fails to build with Python 3.14: TypeError: cannot pickle 'itertools.cycle' object"
    ]
  },
  "python-sqlalchemy1.4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
    ],
    "summaries": [
      "python-sqlalchemy1.4 fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-stack-data": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350304",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345532"
    ],
    "summaries": [
      "Heads-up: python-stack-data fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-stack-data fails to build with Python 3.14: test_example: IndexError: list index out of range"
    ]
  },
  "python-steam": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341218"
    ],
    "summaries": [
      "python-steam: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-streamlink": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353127"
    ],
    "summaries": [
      "python-streamlink fails to build with Python 3.14: test_deprecated: AssetionError: Left contains one more item: <warnings.WarningMessage object at 0x7fd80afa3410>"
    ]
  },
  "python-svg2tikz": {
    "urls": [],
    "summaries": []
  },
  "python-tenacity": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
    ],
    "summaries": [
      "python-tenacity fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-tornado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
    ],
    "summaries": [
      "python-tornado fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-twisted": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342754"
    ],
    "summaries": [
      "python-twisted fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'. + more"
    ]
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typeguard": {
    "urls": [],
    "summaries": []
  },
  "python-typing-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336937"
    ],
    "summaries": [
      "python-typing-extensions fails to build with Python 3.14: test_drop_in_for_typing: AssertionError: self.assertGreaterEqual(te_all, t_all - exceptions)"
    ]
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-ufoLib2": {
    "urls": [],
    "summaries": []
  },
  "python-urwid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
    ],
    "summaries": [
      "python-urwid fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341233",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop: FTBFS in Fedora rawhide/f42",
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-webob": {
    "urls": [],
    "summaries": []
  },
  "python-wordcloud": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335908"
    ],
    "summaries": [
      "python-wordcloud fails to build with Python 3.14: test_cli_as_executable: AssertionError: assert expected_output in out if ret_code == 0 else err"
    ]
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-zeep": {
    "urls": [],
    "summaries": []
  },
  "python-zict": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328012"
    ],
    "summaries": [
      "python-zict fails to build with Python 3.14: test_stress_different_keys_threadsafe Timeout"
    ]
  },
  "python-zope-exceptions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341240"
    ],
    "summaries": [
      "python-zope-exceptions: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-zope-testrunner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335907"
    ],
    "summaries": [
      "python-zope-testrunner fails to build with Python 3.14: difference in the asserted content in testrunner-edge-cases.rst"
    ]
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "rebase-helper": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352551"
    ],
    "summaries": [
      "rebase-helper fails to build with Python 3.14: AssertionError in TestCLI.test_cli_unit and TestConfig.test_merge"
    ]
  },
  "signon-glib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341348"
    ],
    "summaries": [
      "signon-glib: FTBFS in Fedora rawhide/f42"
    ]
  },
  "swift-lang": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341403"
    ],
    "summaries": [
      "swift-lang: FTBFS in Fedora rawhide/f42"
    ]
  },
  "tree-sitter-java": {
    "urls": [],
    "summaries": []
  },
  "ufw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341477"
    ],
    "summaries": [
      "ufw: FTBFS in Fedora rawhide/f42"
    ]
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "xpra": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350289"
    ],
    "summaries": [
      "xpra fails to build from source with Python 3.14: RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase."
    ]
  },
  "yt-dlp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345522"
    ],
    "summaries": [
      "yt-dlp fails to build with Python 3.14: TestTraversal.test_traversal_morsel: AssertionError: `...` should yield all values: Left contains one more item: 'item_value'"
    ]
  },
  "zeek": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341601"
    ],
    "summaries": [
      "zeek: FTBFS in Fedora rawhide/f42"
    ]
  }
}