{
  "Mayavi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351390"
    ],
    "summaries": [
      "Mayavi fails to build with Python 3.14: TestMayaviGarbageCollection.test_mlab_scene_model_with_gui: IndexError: list index out of range"
    ]
  },
  "NLopt": {
    "urls": [],
    "summaries": []
  },
  "NiaAML-GUI": {
    "urls": [],
    "summaries": []
  },
  "ProDy": {
    "urls": [],
    "summaries": []
  },
  "PyMca": {
    "urls": [],
    "summaries": []
  },
  "Zim": {
    "urls": [],
    "summaries": []
  },
  "ansible": {
    "urls": [],
    "summaries": []
  },
  "ansible-builder": {
    "urls": [],
    "summaries": []
  },
  "ansible-core": {
    "urls": [],
    "summaries": []
  },
  "ansible-inventory-grapher": {
    "urls": [],
    "summaries": []
  },
  "arbor": {
    "urls": [],
    "summaries": []
  },
  "astrometry": {
    "urls": [],
    "summaries": []
  },
  "asv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339908"
    ],
    "summaries": [
      "asv: FTBFS in Fedora rawhide/f42"
    ]
  },
  "aubio": {
    "urls": [],
    "summaries": []
  },
  "awscli2": {
    "urls": [],
    "summaries": []
  },
  "bandit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351393"
    ],
    "summaries": [
      "bandit fails to build with Python 3.14: TypeError: Error: Str is not a valid node type in AST"
    ]
  },
  "beaker": {
    "urls": [],
    "summaries": []
  },
  "beets": {
    "urls": [],
    "summaries": []
  },
  "bids-schema": {
    "urls": [],
    "summaries": []
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "bluechi": {
    "urls": [],
    "summaries": []
  },
  "bodhi-client": {
    "urls": [],
    "summaries": []
  },
  "boost": {
    "urls": [],
    "summaries": []
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "borgmatic": {
    "urls": [],
    "summaries": []
  },
  "breezy": {
    "urls": [],
    "summaries": []
  },
  "bst-external": {
    "urls": [],
    "summaries": []
  },
  "calibre": {
    "urls": [],
    "summaries": []
  },
  "capstone": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345714"
    ],
    "summaries": [
      "capstone fails to build with Python 3.14: from capstone import *: ImportError: ERROR: fail to load the dynamic library"
    ]
  },
  "caribou": {
    "urls": [],
    "summaries": []
  },
  "centpkg": {
    "urls": [],
    "summaries": []
  },
  "cepces": {
    "urls": [],
    "summaries": []
  },
  "ceph": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336913"
    ],
    "summaries": [
      "ceph fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "cffconvert": {
    "urls": [],
    "summaries": []
  },
  "chirp": {
    "urls": [],
    "summaries": []
  },
  "cjdns": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339969"
    ],
    "summaries": [
      "cjdns: FTBFS in Fedora rawhide/f42"
    ]
  },
  "classification-banner": {
    "urls": [],
    "summaries": []
  },
  "claws-mail": {
    "urls": [],
    "summaries": []
  },
  "cloud-init": {
    "urls": [],
    "summaries": []
  },
  "cockpit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350287"
    ],
    "summaries": [
      "cockpit fails to build from source with Python 3.14: AttributeError: module 'asyncio' has no attribute 'SafeChildWatcher'"
    ]
  },
  "coin-or-HiGHS": {
    "urls": [],
    "summaries": []
  },
  "compose-utils": {
    "urls": [],
    "summaries": []
  },
  "conda": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356170"
    ],
    "summaries": [
      "conda fails to build with Python 3.14: tests/test_shell.py: TypeError: 'str' object cannot be interpreted as an integer"
    ]
  },
  "conda-build": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356162"
    ],
    "summaries": [
      "conda-build fails to build with Python 3.14: TypeError: _WorkItem.__init__() takes 3 positional arguments but 5 were given"
    ]
  },
  "copr-backend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351386"
    ],
    "summaries": [
      "copr-backend fails to build with Python 3.14: TestActionWorkerManager.test_add_task_for_running_worker: TypeError: cannot pickle 'itertools.count' object"
    ]
  },
  "copr-cli": {
    "urls": [],
    "summaries": []
  },
  "copr-dist-git": {
    "urls": [],
    "summaries": []
  },
  "copr-rpmbuild": {
    "urls": [],
    "summaries": []
  },
  "cozy": {
    "urls": [],
    "summaries": []
  },
  "credslayer": {
    "urls": [],
    "summaries": []
  },
  "criu": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340011"
    ],
    "summaries": [
      "criu: FTBFS in Fedora rawhide/f42"
    ]
  },
  "dbus-python": {
    "urls": [],
    "summaries": []
  },
  "dftd4": {
    "urls": [],
    "summaries": []
  },
  "diceware": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340075"
    ],
    "summaries": [
      "diceware: FTBFS in Fedora rawhide/f42"
    ]
  },
  "did": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328006"
    ],
    "summaries": [
      "did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'"
    ]
  },
  "dlib": {
    "urls": [],
    "summaries": []
  },
  "dnsviz": {
    "urls": [],
    "summaries": []
  },
  "dogtag-pki": {
    "urls": [],
    "summaries": []
  },
  "dt-schema": {
    "urls": [],
    "summaries": []
  },
  "elements-alexandria": {
    "urls": [],
    "summaries": []
  },
  "ephemeral-port-reserve": {
    "urls": [],
    "summaries": []
  },
  "espresso": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340139"
    ],
    "summaries": [
      "espresso: FTBFS in Fedora rawhide/f42"
    ]
  },
  "fedora-third-party": {
    "urls": [],
    "summaries": []
  },
  "fedpkg": {
    "urls": [],
    "summaries": []
  },
  "fedrq": {
    "urls": [],
    "summaries": []
  },
  "flatbuffers": {
    "urls": [],
    "summaries": []
  },
  "flatpak-module-tools": {
    "urls": [],
    "summaries": []
  },
  "fmf": {
    "urls": [],
    "summaries": []
  },
  "freeipa-healthcheck": {
    "urls": [],
    "summaries": []
  },
  "gaupol": {
    "urls": [],
    "summaries": []
  },
  "gdal": {
    "urls": [],
    "summaries": []
  },
  "gdl": {
    "urls": [],
    "summaries": []
  },
  "geopmd": {
    "urls": [],
    "summaries": []
  },
  "gnofract4d": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339539"
    ],
    "summaries": [
      "gnofract4d fails to build with Python 3.14: AssertionError: 'ct_sin6 = (0.841471,-0)' != 'ct_sin6 = (0.841471,0)'"
    ]
  },
  "gnome-feeds": {
    "urls": [],
    "summaries": []
  },
  "gpaw": {
    "urls": [],
    "summaries": []
  },
  "gplugin": {
    "urls": [],
    "summaries": []
  },
  "h5py": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339470"
    ],
    "summaries": [
      "h5py fails to build with Python 3.14: ResourceWarning: TestFileObj.test_TemporaryFile: Implicitly cleaning up <_TemporaryFileWrapper file=<_io.BufferedRandom name='/tmp/tmp8pqafmzv'>>"
    ]
  },
  "hddfancontrol": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354083"
    ],
    "summaries": [
      "hddfancontrol FTBFS due to missing tox configuration"
    ]
  },
  "home-assistant-cli": {
    "urls": [],
    "summaries": []
  },
  "httpie": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350335"
    ],
    "summaries": [
      "httpie fails to build with Python 3.14: test_lazy_choices_help: AssertionError: Expected 'getter' to not have been called. Called 1 times."
    ]
  },
  "hydrapaper": {
    "urls": [],
    "summaries": []
  },
  "ibus": {
    "urls": [],
    "summaries": []
  },
  "ibus-cangjie": {
    "urls": [],
    "summaries": []
  },
  "ikiwiki": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340642"
    ],
    "summaries": [
      "ikiwiki: FTBFS in Fedora rawhide/f42"
    ]
  },
  "ilua": {
    "urls": [],
    "summaries": []
  },
  "imath": {
    "urls": [],
    "summaries": []
  },
  "input-remapper": {
    "urls": [],
    "summaries": []
  },
  "insight": {
    "urls": [],
    "summaries": []
  },
  "ipa-hcc": {
    "urls": [],
    "summaries": []
  },
  "ipython": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356174"
    ],
    "summaries": [
      "ipython fails to build with Python 3.14: AssertionErrors, pexpect.exceptions.TIMEOUTs and more in 12 tests"
    ]
  },
  "javapackages-tools": {
    "urls": [],
    "summaries": []
  },
  "jrnl": {
    "urls": [],
    "summaries": []
  },
  "jupyterlab": {
    "urls": [],
    "summaries": []
  },
  "kernel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340285"
    ],
    "summaries": [
      "kernel: FTBFS in Fedora rawhide/f42"
    ]
  },
  "kicad": {
    "urls": [],
    "summaries": []
  },
  "kitty": {
    "urls": [],
    "summaries": []
  },
  "kiwi": {
    "urls": [],
    "summaries": []
  },
  "kmymoney": {
    "urls": [],
    "summaries": []
  },
  "koji-image-builder": {
    "urls": [],
    "summaries": []
  },
  "kvirc": {
    "urls": [],
    "summaries": []
  },
  "lammps": {
    "urls": [],
    "summaries": []
  },
  "lasso": {
    "urls": [],
    "summaries": []
  },
  "lazygal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350502"
    ],
    "summaries": [
      "lazygal: FTBFS in Fedora 41+ due to test_withvideo test failing with FFmpeg 7.1"
    ]
  },
  "libarcus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340716"
    ],
    "summaries": [
      "libarcus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "libarrow": {
    "urls": [],
    "summaries": []
  },
  "libgexiv2": {
    "urls": [],
    "summaries": []
  },
  "libmodulemd": {
    "urls": [],
    "summaries": []
  },
  "libpeas": {
    "urls": [],
    "summaries": []
  },
  "libreoffice": {
    "urls": [],
    "summaries": []
  },
  "libsonata": {
    "urls": [],
    "summaries": []
  },
  "libsvm": {
    "urls": [],
    "summaries": []
  },
  "libvirt-test-API": {
    "urls": [],
    "summaries": []
  },
  "libxc": {
    "urls": [],
    "summaries": []
  },
  "linkchecker": {
    "urls": [],
    "summaries": []
  },
  "linux-thermaltake-rgb": {
    "urls": [],
    "summaries": []
  },
  "liquidctl": {
    "urls": [],
    "summaries": []
  },
  "lirc": {
    "urls": [],
    "summaries": []
  },
  "lutris": {
    "urls": [],
    "summaries": []
  },
  "mathgl": {
    "urls": [],
    "summaries": []
  },
  "menulibre": {
    "urls": [],
    "summaries": []
  },
  "meson": {
    "urls": [],
    "summaries": []
  },
  "mkdocs": {
    "urls": [],
    "summaries": []
  },
  "mkdocs-bootstrap": {
    "urls": [],
    "summaries": []
  },
  "mkdocs-bootswatch": {
    "urls": [],
    "summaries": []
  },
  "mkdocs-material": {
    "urls": [],
    "summaries": []
  },
  "mlpack": {
    "urls": [],
    "summaries": []
  },
  "mock": {
    "urls": [],
    "summaries": []
  },
  "module-build": {
    "urls": [],
    "summaries": []
  },
  "modulemd-tools": {
    "urls": [],
    "summaries": []
  },
  "monkeytype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356179"
    ],
    "summaries": [
      "monkeytype fails to build with Python 3.14: typing.Union changed with Python 3.14.0a6"
    ]
  },
  "moose": {
    "urls": [],
    "summaries": []
  },
  "mopidy": {
    "urls": [],
    "summaries": []
  },
  "mopidy-mpd": {
    "urls": [],
    "summaries": []
  },
  "morphio": {
    "urls": [],
    "summaries": []
  },
  "mrchem": {
    "urls": [],
    "summaries": []
  },
  "myst-nb": {
    "urls": [],
    "summaries": []
  },
  "netcdf4-python": {
    "urls": [],
    "summaries": []
  },
  "neuron": {
    "urls": [],
    "summaries": []
  },
  "nextpnr": {
    "urls": [],
    "summaries": []
  },
  "nfsometer": {
    "urls": [],
    "summaries": []
  },
  "nicotine+": {
    "urls": [],
    "summaries": []
  },
  "nik4": {
    "urls": [],
    "summaries": []
  },
  "ocrmypdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357508"
    ],
    "summaries": [
      "ocrmypdf fails to build with Python 3.14: multiprocessing.Process now starts with forkserver method instead of fork, causing pickling error"
    ]
  },
  "onnx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354087"
    ],
    "summaries": [
      "onnx FTBFS due to missing tox configuration"
    ]
  },
  "onnxruntime": {
    "urls": [],
    "summaries": []
  },
  "opae": {
    "urls": [],
    "summaries": []
  },
  "openapi-python-client": {
    "urls": [],
    "summaries": []
  },
  "opencv": {
    "urls": [],
    "summaries": []
  },
  "openmeeg": {
    "urls": [],
    "summaries": []
  },
  "openscap-report": {
    "urls": [],
    "summaries": []
  },
  "openvino": {
    "urls": [],
    "summaries": []
  },
  "orca": {
    "urls": [],
    "summaries": []
  },
  "oz": {
    "urls": [],
    "summaries": []
  },
  "paperwork": {
    "urls": [],
    "summaries": []
  },
  "paraview": {
    "urls": [],
    "summaries": []
  },
  "pcp": {
    "urls": [],
    "summaries": []
  },
  "pcs": {
    "urls": [],
    "summaries": []
  },
  "petsc": {
    "urls": [],
    "summaries": []
  },
  "pgzero": {
    "urls": [],
    "summaries": []
  },
  "piper": {
    "urls": [],
    "summaries": []
  },
  "plplot": {
    "urls": [],
    "summaries": []
  },
  "poetry": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351383"
    ],
    "summaries": [
      "poetry fails to build with Python 3.14: AssertionError in test_isolated_env_install_discards_requirements_not_needed_by_env and test_python_get_preferred_default"
    ]
  },
  "poezio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341088"
    ],
    "summaries": [
      "poezio: FTBFS in Fedora rawhide/f42"
    ]
  },
  "postfix-mta-sts-resolver": {
    "urls": [],
    "summaries": []
  },
  "powerline": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336943"
    ],
    "summaries": [
      "powerline fails to build with Python 3.14: ValueError: argument groups cannot be nested"
    ]
  },
  "pre-commit": {
    "urls": [],
    "summaries": []
  },
  "protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356165",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343969"
    ],
    "summaries": [
      "protobuf with Python 3.14: TypeError: Metaclasses with custom tp_new are not supported.",
      "protobuf doesn't work with Python 3.14: test_error_reason: TypeError: Metaclasses with custom tp_new are not supported."
    ]
  },
  "pungi": {
    "urls": [],
    "summaries": []
  },
  "pybind11": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336889"
    ],
    "summaries": [
      "pybind11 fails to build with Python 3.14: AttributeError: 'pybind11_tests.pickling.PickleableWithDict' object has no attribute 'dynamic' + AssertionError"
    ]
  },
  "pycairo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322709"
    ],
    "summaries": [
      "pycairo fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pychromecast": {
    "urls": [],
    "summaries": []
  },
  "pyflakes": {
    "urls": [],
    "summaries": []
  },
  "pygame": {
    "urls": [],
    "summaries": []
  },
  "pygobject3": {
    "urls": [],
    "summaries": []
  },
  "pygsl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341119"
    ],
    "summaries": [
      "pygsl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pylibacl": {
    "urls": [],
    "summaries": []
  },
  "pylint": {
    "urls": [],
    "summaries": []
  },
  "pyosmium": {
    "urls": [],
    "summaries": []
  },
  "pyplane": {
    "urls": [],
    "summaries": []
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pysubnettree": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341123"
    ],
    "summaries": [
      "pysubnettree: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pytest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353140"
    ],
    "summaries": [
      "pytest fails to build with Python 3.14: mismatch of expected and actual strings in test output"
    ]
  },
  "python-AppTools": {
    "urls": [],
    "summaries": []
  },
  "python-Bottleneck": {
    "urls": [],
    "summaries": []
  },
  "python-CacheControl": {
    "urls": [],
    "summaries": []
  },
  "python-Levenshtein": {
    "urls": [],
    "summaries": []
  },
  "python-Rtree": {
    "urls": [],
    "summaries": []
  },
  "python-SALib": {
    "urls": [],
    "summaries": []
  },
  "python-SecretStorage": {
    "urls": [],
    "summaries": []
  },
  "python-TestSlide": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350306",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343971"
    ],
    "summaries": [
      "Heads-up: python-TestSlide fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-TestSlide fails to build with Python 3.14: ERROR collecting tests/mock_callable_testslide.py: RuntimeError: dictionary changed size during iteration"
    ]
  },
  "python-Traits": {
    "urls": [],
    "summaries": []
  },
  "python-accuweather": {
    "urls": [],
    "summaries": []
  },
  "python-adjustText": {
    "urls": [],
    "summaries": []
  },
  "python-advisory-parser": {
    "urls": [],
    "summaries": []
  },
  "python-agate": {
    "urls": [],
    "summaries": []
  },
  "python-agate-dbf": {
    "urls": [],
    "summaries": []
  },
  "python-agate-excel": {
    "urls": [],
    "summaries": []
  },
  "python-agate-sql": {
    "urls": [],
    "summaries": []
  },
  "python-aioesphomeapi": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-cors": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-oauthlib": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-retry": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-sse-client": {
    "urls": [],
    "summaries": []
  },
  "python-aiokafka": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2346517"
    ],
    "summaries": [
      "python-aiokafka fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-aioresponses": {
    "urls": [],
    "summaries": []
  },
  "python-aioruckus": {
    "urls": [],
    "summaries": []
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-aiounittest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356177"
    ],
    "summaries": [
      "python-aiounittest fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-alembic": {
    "urls": [],
    "summaries": []
  },
  "python-annarchy": {
    "urls": [],
    "summaries": []
  },
  "python-ansible-compat": {
    "urls": [],
    "summaries": []
  },
  "python-ansible-runner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341125"
    ],
    "summaries": [
      "python-ansible-runner: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-anyio": {
    "urls": [],
    "summaries": []
  },
  "python-apsw": {
    "urls": [],
    "summaries": []
  },
  "python-archspec": {
    "urls": [],
    "summaries": []
  },
  "python-aresponses": {
    "urls": [],
    "summaries": []
  },
  "python-array-api-strict": {
    "urls": [],
    "summaries": []
  },
  "python-ase": {
    "urls": [],
    "summaries": []
  },
  "python-asgiref": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345528"
    ],
    "summaries": [
      "python-asgiref fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-aspy.yaml": {
    "urls": [],
    "summaries": []
  },
  "python-astdoc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349452"
    ],
    "summaries": [
      "python-astdoc fails to build with Python 3.14: 3 doctests fail, e.g.: Expected: <ast.Name object at 0x...> Got: Name(id='int', ctx=Load())"
    ]
  },
  "python-astroML": {
    "urls": [],
    "summaries": []
  },
  "python-astroid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
    ],
    "summaries": [
      "python-astroid fails to build with Python 3.14: astroid.exceptions.InferenceError: StopIteration raised without any error information."
    ]
  },
  "python-astroplan": {
    "urls": [],
    "summaries": []
  },
  "python-astropy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345524"
    ],
    "summaries": [
      "python-astropy fails to build with Python 3.14: test_info_preserved_pickle_copy_init[arrayswap]: AssertionError: assert dtype('>i4') == dtype('int32')"
    ]
  },
  "python-astropy-healpix": {
    "urls": [],
    "summaries": []
  },
  "python-astropy-iers-data": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349443"
    ],
    "summaries": [
      "python-astropy-iers-data fails to build with Python 3.14: 4 tests fail with KeyError: 'ra_in' and 'lon_in'"
    ]
  },
  "python-astroquery": {
    "urls": [],
    "summaries": []
  },
  "python-astroscrappy": {
    "urls": [],
    "summaries": []
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-atlassian-python-api": {
    "urls": [],
    "summaries": []
  },
  "python-atomicwrites": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341128"
    ],
    "summaries": [
      "python-atomicwrites: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-authlib": {
    "urls": [],
    "summaries": []
  },
  "python-autobahn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341129"
    ],
    "summaries": [
      "python-autobahn: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-autocommand": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
    ],
    "summaries": [
      "python-autocommand fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-autograd": {
    "urls": [],
    "summaries": []
  },
  "python-avalara": {
    "urls": [],
    "summaries": []
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341130",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado: FTBFS in Fedora rawhide/f42",
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-aw-core": {
    "urls": [],
    "summaries": []
  },
  "python-awesomeversion": {
    "urls": [],
    "summaries": []
  },
  "python-aws-sam-translator": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353126"
    ],
    "summaries": [
      "python-aws-sam-translator fails to build with Python 3.14: 77 test failures, 4 error"
    ]
  },
  "python-aws-xray-sdk": {
    "urls": [],
    "summaries": []
  },
  "python-azure-core": {
    "urls": [],
    "summaries": []
  },
  "python-azure-loganalytics": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-advisor": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-billing": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-botservice": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-consumption": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-core": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-databoxedge": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-datamigration": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-devtestlabs": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-dns": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-managedservices": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-maps": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-marketplaceordering": {
    "urls": [],
    "summaries": []
  },
  "python-azure-multiapi-storage": {
    "urls": [],
    "summaries": []
  },
  "python-azure-servicebus": {
    "urls": [],
    "summaries": []
  },
  "python-azure-storage-blob": {
    "urls": [],
    "summaries": []
  },
  "python-beaker": {
    "urls": [],
    "summaries": []
  },
  "python-beancount": {
    "urls": [],
    "summaries": []
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341131",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype: FTBFS in Fedora rawhide/f42",
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-beautifulsoup4": {
    "urls": [],
    "summaries": []
  },
  "python-behave": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339094"
    ],
    "summaries": [
      "python-behave fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-bids-validator": {
    "urls": [],
    "summaries": []
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-binary-manager": {
    "urls": [],
    "summaries": []
  },
  "python-binary-memcached": {
    "urls": [],
    "summaries": []
  },
  "python-bioframe": {
    "urls": [],
    "summaries": []
  },
  "python-biopython": {
    "urls": [],
    "summaries": []
  },
  "python-bioread": {
    "urls": [],
    "summaries": []
  },
  "python-blinker": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325193"
    ],
    "summaries": [
      "python-blinker fails to build with Python 3.14: pluggy.PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown."
    ]
  },
  "python-blosc": {
    "urls": [],
    "summaries": []
  },
  "python-blosc2": {
    "urls": [],
    "summaries": []
  },
  "python-boto3": {
    "urls": [],
    "summaries": []
  },
  "python-botocore": {
    "urls": [],
    "summaries": []
  },
  "python-boutdata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352553"
    ],
    "summaries": [
      "python-boutdata fails to build with Python 3.14: NotImplementedError: Dataset is not picklable"
    ]
  },
  "python-boututils": {
    "urls": [],
    "summaries": []
  },
  "python-box": {
    "urls": [],
    "summaries": []
  },
  "python-branca": {
    "urls": [],
    "summaries": []
  },
  "python-bravado": {
    "urls": [],
    "summaries": []
  },
  "python-bravado-core": {
    "urls": [],
    "summaries": []
  },
  "python-breathe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341133"
    ],
    "summaries": [
      "python-breathe: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-brian2": {
    "urls": [],
    "summaries": []
  },
  "python-brukerapi": {
    "urls": [],
    "summaries": []
  },
  "python-bsmschema": {
    "urls": [],
    "summaries": []
  },
  "python-cairocffi": {
    "urls": [],
    "summaries": []
  },
  "python-calcephpy": {
    "urls": [],
    "summaries": []
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-carbon": {
    "urls": [],
    "summaries": []
  },
  "python-cascadio": {
    "urls": [],
    "summaries": []
  },
  "python-catkin_lint": {
    "urls": [],
    "summaries": []
  },
  "python-catkin_tools": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341134"
    ],
    "summaries": [
      "python-catkin_tools: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-cattrs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343916"
    ],
    "summaries": [
      "python-cattrs fails to build with Python 3.14: TypeError: <class 'tests.strategies.test_include_subclasses.GrandChild'> has no usable non-default attributes"
    ]
  },
  "python-cclib": {
    "urls": [],
    "summaries": []
  },
  "python-cerberus": {
    "urls": [],
    "summaries": []
  },
  "python-cffsubr": {
    "urls": [],
    "summaries": []
  },
  "python-cftime": {
    "urls": [],
    "summaries": []
  },
  "python-chalice": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342568"
    ],
    "summaries": [
      "python-chalice fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-chaospy": {
    "urls": [],
    "summaries": []
  },
  "python-citeproc-py": {
    "urls": [],
    "summaries": []
  },
  "python-cleo": {
    "urls": [],
    "summaries": []
  },
  "python-cma": {
    "urls": [],
    "summaries": []
  },
  "python-cmake-build-extension": {
    "urls": [],
    "summaries": []
  },
  "python-cmap": {
    "urls": [],
    "summaries": []
  },
  "python-cmd2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356178"
    ],
    "summaries": [
      "python-cmd2 fails to build with Python 3.14:  ValueError: action 'store_true' is not valid for positional arguments"
    ]
  },
  "python-colcon-cmake": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339465"
    ],
    "summaries": [
      "python-colcon-cmake fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-colcon-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339464"
    ],
    "summaries": [
      "python-colcon-core fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-collada": {
    "urls": [],
    "summaries": []
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-colormath2": {
    "urls": [],
    "summaries": []
  },
  "python-colorthief": {
    "urls": [],
    "summaries": []
  },
  "python-compal": {
    "urls": [],
    "summaries": []
  },
  "python-compreffor": {
    "urls": [],
    "summaries": []
  },
  "python-configargparse": {
    "urls": [],
    "summaries": []
  },
  "python-confuse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
    ],
    "summaries": [
      "python-confuse fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-constantly": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341138"
    ],
    "summaries": [
      "python-constantly: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-contextualbandits": {
    "urls": [],
    "summaries": []
  },
  "python-contourpy": {
    "urls": [],
    "summaries": []
  },
  "python-copr": {
    "urls": [],
    "summaries": []
  },
  "python-cornice": {
    "urls": [],
    "summaries": []
  },
  "python-cramjam": {
    "urls": [],
    "summaries": []
  },
  "python-crcmod": {
    "urls": [],
    "summaries": []
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-cro": {
    "urls": [],
    "summaries": []
  },
  "python-crochet": {
    "urls": [],
    "summaries": []
  },
  "python-cs": {
    "urls": [],
    "summaries": []
  },
  "python-cssselect": {
    "urls": [],
    "summaries": []
  },
  "python-csvkit": {
    "urls": [],
    "summaries": []
  },
  "python-cvelib": {
    "urls": [],
    "summaries": []
  },
  "python-cvxopt": {
    "urls": [],
    "summaries": []
  },
  "python-cyipopt": {
    "urls": [],
    "summaries": []
  },
  "python-daikin": {
    "urls": [],
    "summaries": []
  },
  "python-daphne": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341140"
    ],
    "summaries": [
      "python-daphne: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-dateparser": {
    "urls": [],
    "summaries": []
  },
  "python-dbusmock": {
    "urls": [],
    "summaries": []
  },
  "python-deap": {
    "urls": [],
    "summaries": []
  },
  "python-deepdiff": {
    "urls": [],
    "summaries": []
  },
  "python-defcon": {
    "urls": [],
    "summaries": []
  },
  "python-defusedxml": {
    "urls": [],
    "summaries": []
  },
  "python-deprecated": {
    "urls": [],
    "summaries": []
  },
  "python-diff-cover": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350299"
    ],
    "summaries": [
      "Heads-up: python-diff-cover fails to build with python-pygments 2.19.1 on Fedora 43"
    ]
  },
  "python-diff-match-patch": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354097"
    ],
    "summaries": [
      "python-diff-match-patch FTBFS due to missing tox configuration"
    ]
  },
  "python-dijitso": {
    "urls": [],
    "summaries": []
  },
  "python-dipy": {
    "urls": [],
    "summaries": []
  },
  "python-dirty-equals": {
    "urls": [],
    "summaries": []
  },
  "python-distroinfo": {
    "urls": [],
    "summaries": []
  },
  "python-django-allauth": {
    "urls": [],
    "summaries": []
  },
  "python-django-configurations": {
    "urls": [],
    "summaries": []
  },
  "python-django-contrib-comments": {
    "urls": [],
    "summaries": []
  },
  "python-django-extensions": {
    "urls": [],
    "summaries": []
  },
  "python-django-filter": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336944"
    ],
    "summaries": [
      "python-django-filter fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "python-django-mailman3": {
    "urls": [],
    "summaries": []
  },
  "python-dns-lexicon": {
    "urls": [],
    "summaries": []
  },
  "python-domdf-python-tools": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345519"
    ],
    "summaries": [
      "python-domdf-python-tools fails to build with Python 3.14: tests/test_words.py::test_alpha_sort - AssertionError: Regex pattern did not match."
    ]
  },
  "python-doubleratchet": {
    "urls": [],
    "summaries": []
  },
  "python-ducc0": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341145"
    ],
    "summaries": [
      "python-ducc0: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-duecredit": {
    "urls": [],
    "summaries": []
  },
  "python-dunamai": {
    "urls": [],
    "summaries": []
  },
  "python-ebooklib": {
    "urls": [],
    "summaries": []
  },
  "python-eccodes": {
    "urls": [],
    "summaries": []
  },
  "python-efel": {
    "urls": [],
    "summaries": []
  },
  "python-elephant": {
    "urls": [],
    "summaries": []
  },
  "python-emcee": {
    "urls": [],
    "summaries": []
  },
  "python-engineio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327989"
    ],
    "summaries": [
      "python-engineio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-envisage": {
    "urls": [],
    "summaries": []
  },
  "python-ephyviewer": {
    "urls": [],
    "summaries": []
  },
  "python-et_xmlfile": {
    "urls": [],
    "summaries": []
  },
  "python-etcd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
    ],
    "summaries": [
      "python-etcd fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestWatch.test_watch_indexed_generator.<locals>.watch_value at 0x7f0d39f71dd0>"
    ]
  },
  "python-eth-stdlib": {
    "urls": [],
    "summaries": []
  },
  "python-exdir": {
    "urls": [],
    "summaries": []
  },
  "python-execnet": {
    "urls": [],
    "summaries": []
  },
  "python-executing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349436"
    ],
    "summaries": [
      "python-executing fails to build with Python 3.14: 52 test fail during the build"
    ]
  },
  "python-factory-boy": {
    "urls": [],
    "summaries": []
  },
  "python-fasjson-client": {
    "urls": [],
    "summaries": []
  },
  "python-fast-simplification": {
    "urls": [],
    "summaries": []
  },
  "python-fastavro": {
    "urls": [],
    "summaries": []
  },
  "python-feedgen": {
    "urls": [],
    "summaries": []
  },
  "python-filelock": {
    "urls": [],
    "summaries": []
  },
  "python-fireflyalgorithm": {
    "urls": [],
    "summaries": []
  },
  "python-fisx": {
    "urls": [],
    "summaries": []
  },
  "python-fitsio": {
    "urls": [],
    "summaries": []
  },
  "python-flake8-comprehensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351385"
    ],
    "summaries": [
      "python-flake8-comprehensions fails to build with Python 3.14: Unnecessary reversed call around sorted() in 10 tests"
    ]
  },
  "python-flask": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327965"
    ],
    "summaries": [
      "python-flask fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-flask-babel": {
    "urls": [],
    "summaries": []
  },
  "python-flask-caching": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341153"
    ],
    "summaries": [
      "python-flask-caching: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-flask-migrate": {
    "urls": [],
    "summaries": []
  },
  "python-flask-session": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354108"
    ],
    "summaries": [
      "python-flask-session FTBFS due to missing tox configuration"
    ]
  },
  "python-flask-sqlalchemy": {
    "urls": [],
    "summaries": []
  },
  "python-flask-sqlalchemy-lite": {
    "urls": [],
    "summaries": []
  },
  "python-flask-whooshee": {
    "urls": [],
    "summaries": []
  },
  "python-flexmock": {
    "urls": [],
    "summaries": []
  },
  "python-folium": {
    "urls": [],
    "summaries": []
  },
  "python-formulaic": {
    "urls": [],
    "summaries": []
  },
  "python-freeqdsk": {
    "urls": [],
    "summaries": []
  },
  "python-fs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336951"
    ],
    "summaries": [
      "python-fs fails to build with Python 3.14: AssertionError: 'osfs://///tmp/tmppauy69swfstestosfs/foo' != 'osfs:///tmp/tmppauy69swfstestosfs/foo'"
    ]
  },
  "python-fsleyes-widgets": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336911"
    ],
    "summaries": [
      "python-fsleyes-widgets fails to build with Python 3.14: AssertionError: assert 'file:/home/b...htmlfile.html' == 'file:///home...htmlfile.html'"
    ]
  },
  "python-fsspec": {
    "urls": [],
    "summaries": []
  },
  "python-furo": {
    "urls": [],
    "summaries": []
  },
  "python-geoip2": {
    "urls": [],
    "summaries": []
  },
  "python-geopmpy": {
    "urls": [],
    "summaries": []
  },
  "python-geopy": {
    "urls": [],
    "summaries": []
  },
  "python-gevent": {
    "urls": [],
    "summaries": []
  },
  "python-gevent-eventemitter": {
    "urls": [],
    "summaries": []
  },
  "python-giacpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341608"
    ],
    "summaries": [
      "python-giacpy: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-gios": {
    "urls": [],
    "summaries": []
  },
  "python-glanceclient": {
    "urls": [],
    "summaries": []
  },
  "python-googleapis-common-protos": {
    "urls": [],
    "summaries": []
  },
  "python-gphoto2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341158"
    ],
    "summaries": [
      "python-gphoto2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-gql": {
    "urls": [],
    "summaries": []
  },
  "python-gradunwarp": {
    "urls": [],
    "summaries": []
  },
  "python-graph-tool": {
    "urls": [],
    "summaries": []
  },
  "python-greenlet": {
    "urls": [],
    "summaries": []
  },
  "python-gsd": {
    "urls": [],
    "summaries": []
  },
  "python-gstreamer1": {
    "urls": [],
    "summaries": []
  },
  "python-gunicorn": {
    "urls": [],
    "summaries": []
  },
  "python-h5io": {
    "urls": [],
    "summaries": []
  },
  "python-hamcrest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2346504"
    ],
    "summaries": [
      "python-hamcrest fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-hass-data-detective": {
    "urls": [],
    "summaries": []
  },
  "python-haversion": {
    "urls": [],
    "summaries": []
  },
  "python-hdf5storage": {
    "urls": [],
    "summaries": []
  },
  "python-hdfs": {
    "urls": [],
    "summaries": []
  },
  "python-healpy": {
    "urls": [],
    "summaries": []
  },
  "python-hl7": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341161"
    ],
    "summaries": [
      "python-hl7: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-howdoi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342558"
    ],
    "summaries": [
      "python-howdoi fails to build with Python 3.14: AssertionError: 'ERROR: Unable to reach google. Do you need to use a proxy? + json.decoder.JSONDecodeError"
    ]
  },
  "python-html-text": {
    "urls": [],
    "summaries": []
  },
  "python-html5-parser": {
    "urls": [],
    "summaries": []
  },
  "python-html5lib": {
    "urls": [],
    "summaries": []
  },
  "python-httpcore": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353138"
    ],
    "summaries": [
      "python-httpcore fails to build with Python 3.14: AttributeError: 'typing.Union' object has no attribute '__module__' and no __dict__ for setting new attributes. Did you mean: '__reduce__'?"
    ]
  },
  "python-hvac": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354110"
    ],
    "summaries": [
      "python-hvac FTBFS due to missing tox configuration"
    ]
  },
  "python-igraph": {
    "urls": [],
    "summaries": []
  },
  "python-imagehash": {
    "urls": [],
    "summaries": []
  },
  "python-imageio": {
    "urls": [],
    "summaries": []
  },
  "python-imbalanced-learn": {
    "urls": [],
    "summaries": []
  },
  "python-img2pdf": {
    "urls": [],
    "summaries": []
  },
  "python-indexed_gzip": {
    "urls": [],
    "summaries": []
  },
  "python-influxdb-client": {
    "urls": [],
    "summaries": []
  },
  "python-iniparse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
    ],
    "summaries": [
      "python-iniparse fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestIni.test_queue.<locals>.getxy at 0x7f86659a7740>"
    ]
  },
  "python-inject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
    ],
    "summaries": [
      "python-inject fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-injector": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341165"
    ],
    "summaries": [
      "python-injector: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-inkex": {
    "urls": [],
    "summaries": []
  },
  "python-intern": {
    "urls": [],
    "summaries": []
  },
  "python-ipykernel": {
    "urls": [],
    "summaries": []
  },
  "python-ipyparallel": {
    "urls": [],
    "summaries": []
  },
  "python-ipywidgets": {
    "urls": [],
    "summaries": []
  },
  "python-irc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
    ],
    "summaries": [
      "python-irc fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-janus": {
    "urls": [],
    "summaries": []
  },
  "python-jedi": {
    "urls": [],
    "summaries": []
  },
  "python-jiter": {
    "urls": [],
    "summaries": []
  },
  "python-jnius": {
    "urls": [],
    "summaries": []
  },
  "python-joblib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339519"
    ],
    "summaries": [
      "python-joblib fails to build with Python 3.14: TypeError: Hasher._batch_setitems() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-josepy": {
    "urls": [],
    "summaries": []
  },
  "python-jsonpickle": {
    "urls": [],
    "summaries": []
  },
  "python-jsonschema": {
    "urls": [],
    "summaries": []
  },
  "python-jsonschema-path": {
    "urls": [],
    "summaries": []
  },
  "python-jsonschema-specifications": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-c-kernel": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-cache": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-client": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-console": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-events": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-kernel-singular": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-kernel-test": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-lsp": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-polymake": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-server": {
    "urls": [],
    "summaries": []
  },
  "python-jupyterlab-server": {
    "urls": [],
    "summaries": []
  },
  "python-jupytext": {
    "urls": [],
    "summaries": []
  },
  "python-keyring": {
    "urls": [],
    "summaries": []
  },
  "python-keystoneauth1": {
    "urls": [],
    "summaries": []
  },
  "python-keystoneclient": {
    "urls": [],
    "summaries": []
  },
  "python-klusta": {
    "urls": [],
    "summaries": []
  },
  "python-lazy-loader": {
    "urls": [],
    "summaries": []
  },
  "python-lazyarray": {
    "urls": [],
    "summaries": []
  },
  "python-ldap3": {
    "urls": [],
    "summaries": []
  },
  "python-leather": {
    "urls": [],
    "summaries": []
  },
  "python-lfpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341168"
    ],
    "summaries": [
      "python-lfpy: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-lfpykit": {
    "urls": [],
    "summaries": []
  },
  "python-libNeuroML": {
    "urls": [],
    "summaries": []
  },
  "python-libcst": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356182"
    ],
    "summaries": [
      "python-libcst fails to build with Python 3.14: Exception: Logic error, unexpected top level type! when importing libcst.codegen.gen_matcher_classes"
    ]
  },
  "python-logbook": {
    "urls": [],
    "summaries": []
  },
  "python-loguru": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356181"
    ],
    "summaries": [
      "python-loguru fails to build with Python 3.14: test_exception_modern[type_hints-minimum_python_version0]: m<class 'typing.Union'>"
    ]
  },
  "python-lqrt": {
    "urls": [],
    "summaries": []
  },
  "python-lunr": {
    "urls": [],
    "summaries": []
  },
  "python-lxml-html-clean": {
    "urls": [],
    "summaries": []
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-mapbox-earcut": {
    "urls": [],
    "summaries": []
  },
  "python-markdown-callouts": {
    "urls": [],
    "summaries": []
  },
  "python-markups": {
    "urls": [],
    "summaries": []
  },
  "python-matplotlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328713"
    ],
    "summaries": [
      "python-matplotlib fails to build with Python 3.14: RecursionError: maximum recursion depth exceeded"
    ]
  },
  "python-matplotlib-scalebar": {
    "urls": [],
    "summaries": []
  },
  "python-matrix-common": {
    "urls": [],
    "summaries": []
  },
  "python-matrix-nio": {
    "urls": [],
    "summaries": []
  },
  "python-mccabe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328016"
    ],
    "summaries": [
      "python-mccabe fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-meautility": {
    "urls": [],
    "summaries": []
  },
  "python-mechanicalsoup": {
    "urls": [],
    "summaries": []
  },
  "python-mechanize": {
    "urls": [],
    "summaries": []
  },
  "python-memray": {
    "urls": [],
    "summaries": []
  },
  "python-meshio": {
    "urls": [],
    "summaries": []
  },
  "python-metakernel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357903"
    ],
    "summaries": [
      "python-metakernel fails to build with Python 3.14: AssertionError in test_parallel_magic"
    ]
  },
  "python-mf2py": {
    "urls": [],
    "summaries": []
  },
  "python-micawber": {
    "urls": [],
    "summaries": []
  },
  "python-missingno": {
    "urls": [],
    "summaries": []
  },
  "python-mizani": {
    "urls": [],
    "summaries": []
  },
  "python-mkdocs-d2-plugin": {
    "urls": [],
    "summaries": []
  },
  "python-mkdocs-get-deps": {
    "urls": [],
    "summaries": []
  },
  "python-mkdocs-git-revision-date-localized-plugin": {
    "urls": [],
    "summaries": []
  },
  "python-mkdocs-include-markdown-plugin": {
    "urls": [],
    "summaries": []
  },
  "python-mkdocs-material-extensions": {
    "urls": [],
    "summaries": []
  },
  "python-mkdocs-rss-plugin": {
    "urls": [],
    "summaries": []
  },
  "python-mkdocs-static-i18n": {
    "urls": [],
    "summaries": []
  },
  "python-mmtf": {
    "urls": [],
    "summaries": []
  },
  "python-mockito": {
    "urls": [],
    "summaries": []
  },
  "python-moddb": {
    "urls": [],
    "summaries": []
  },
  "python-mplcairo": {
    "urls": [],
    "summaries": []
  },
  "python-mplcursors": {
    "urls": [],
    "summaries": []
  },
  "python-mpmath": {
    "urls": [],
    "summaries": []
  },
  "python-mrcfile": {
    "urls": [],
    "summaries": []
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-msgspec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325169"
    ],
    "summaries": [
      "python-msgspec fails to build with Python 3.14: error: \u2018_Py_IMMORTAL_REFCNT\u2019 undeclared here"
    ]
  },
  "python-msrest": {
    "urls": [],
    "summaries": []
  },
  "python-multiprocess": {
    "urls": [],
    "summaries": []
  },
  "python-murano-pkg-check": {
    "urls": [],
    "summaries": []
  },
  "python-music21": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354114"
    ],
    "summaries": [
      "python-music21 FTBFS due to missing tox configuration"
    ]
  },
  "python-myst-parser": {
    "urls": [],
    "summaries": []
  },
  "python-nanobind": {
    "urls": [],
    "summaries": []
  },
  "python-nbclassic": {
    "urls": [],
    "summaries": []
  },
  "python-nbclient": {
    "urls": [],
    "summaries": []
  },
  "python-nbdime": {
    "urls": [],
    "summaries": []
  },
  "python-nbformat": {
    "urls": [],
    "summaries": []
  },
  "python-nbsphinx": {
    "urls": [],
    "summaries": []
  },
  "python-ndindex": {
    "urls": [],
    "summaries": []
  },
  "python-neatdend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341170"
    ],
    "summaries": [
      "python-neatdend: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-neo": {
    "urls": [],
    "summaries": []
  },
  "python-neovim": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336888"
    ],
    "summaries": [
      "python-neovim fails to build with Python 3.14: ImportError: cannot import name 'ThreadedChildWatcher' from 'asyncio.unix_events' (/usr/lib64/python3.14/asyncio/unix_events.py)"
    ]
  },
  "python-netaddr": {
    "urls": [],
    "summaries": []
  },
  "python-netpyne": {
    "urls": [],
    "summaries": []
  },
  "python-network-runner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341172"
    ],
    "summaries": [
      "python-network-runner: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-neurodsp": {
    "urls": [],
    "summaries": []
  },
  "python-neurotune": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341173"
    ],
    "summaries": [
      "python-neurotune: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-niaaml": {
    "urls": [],
    "summaries": []
  },
  "python-niaclass": {
    "urls": [],
    "summaries": []
  },
  "python-niapy": {
    "urls": [],
    "summaries": []
  },
  "python-nibabel": {
    "urls": [],
    "summaries": []
  },
  "python-nikola": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341174"
    ],
    "summaries": [
      "python-nikola: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-nipy": {
    "urls": [],
    "summaries": []
  },
  "python-nitime": {
    "urls": [],
    "summaries": []
  },
  "python-nixio": {
    "urls": [],
    "summaries": []
  },
  "python-nmrglue": {
    "urls": [],
    "summaries": []
  },
  "python-notebook": {
    "urls": [],
    "summaries": []
  },
  "python-notebook-shim": {
    "urls": [],
    "summaries": []
  },
  "python-notify2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341175"
    ],
    "summaries": [
      "python-notify2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-numcodecs": {
    "urls": [],
    "summaries": []
  },
  "python-numexpr": {
    "urls": [],
    "summaries": []
  },
  "python-numpoly": {
    "urls": [],
    "summaries": []
  },
  "python-numpy-stl": {
    "urls": [],
    "summaries": []
  },
  "python-odata-query": {
    "urls": [],
    "summaries": []
  },
  "python-ollama": {
    "urls": [],
    "summaries": []
  },
  "python-openapi-schema-validator": {
    "urls": [],
    "summaries": []
  },
  "python-openapi-spec-validator": {
    "urls": [],
    "summaries": []
  },
  "python-openctm": {
    "urls": [],
    "summaries": []
  },
  "python-openpaperwork-gtk": {
    "urls": [],
    "summaries": []
  },
  "python-opensearch-py": {
    "urls": [],
    "summaries": []
  },
  "python-openstacksdk": {
    "urls": [],
    "summaries": []
  },
  "python-opfunu": {
    "urls": [],
    "summaries": []
  },
  "python-opytimark": {
    "urls": [],
    "summaries": []
  },
  "python-opytimizer": {
    "urls": [],
    "summaries": []
  },
  "python-orjson": {
    "urls": [],
    "summaries": []
  },
  "python-osc-lib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351387"
    ],
    "summaries": [
      "python-osc-lib fails to build with Python 3.14: testtools.matchers._impl.MismatchError in 4 tests"
    ]
  },
  "python-oslo-config": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-serialization": {
    "urls": [],
    "summaries": []
  },
  "python-packvers": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341178"
    ],
    "summaries": [
      "python-packvers: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-paginate": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354116"
    ],
    "summaries": [
      "python-paginate FTBFS due to missing tox configuration"
    ]
  },
  "python-pamela": {
    "urls": [],
    "summaries": []
  },
  "python-pandas": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341179"
    ],
    "summaries": [
      "python-pandas: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pandas-datareader": {
    "urls": [],
    "summaries": []
  },
  "python-paperwork-backend": {
    "urls": [],
    "summaries": []
  },
  "python-pari-jupyter": {
    "urls": [],
    "summaries": []
  },
  "python-pathos": {
    "urls": [],
    "summaries": []
  },
  "python-patsy": {
    "urls": [],
    "summaries": []
  },
  "python-peewee": {
    "urls": [],
    "summaries": []
  },
  "python-pendulum": {
    "urls": [],
    "summaries": []
  },
  "python-periodictable": {
    "urls": [],
    "summaries": []
  },
  "python-persist-queue": {
    "urls": [],
    "summaries": []
  },
  "python-pexpect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341180"
    ],
    "summaries": [
      "python-pexpect: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-photutils": {
    "urls": [],
    "summaries": []
  },
  "python-pika": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351384"
    ],
    "summaries": [
      "python-pika fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pikepdf": {
    "urls": [],
    "summaries": []
  },
  "python-pip": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335909"
    ],
    "summaries": [
      "python-pip fails to build with Python 3.14: AssertionError: assert 'file:/tmp/file' == 'file:///tmp/file'"
    ]
  },
  "python-pkg-depgraph": {
    "urls": [],
    "summaries": []
  },
  "python-pkginfo": {
    "urls": [],
    "summaries": []
  },
  "python-poi-tracker": {
    "urls": [],
    "summaries": []
  },
  "python-praw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342562"
    ],
    "summaries": [
      "python-praw fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-priority": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341182"
    ],
    "summaries": [
      "python-priority: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-prometheus_client": {
    "urls": [],
    "summaries": []
  },
  "python-proton-core": {
    "urls": [],
    "summaries": []
  },
  "python-pudb": {
    "urls": [],
    "summaries": []
  },
  "python-pulp": {
    "urls": [],
    "summaries": []
  },
  "python-pulp-glue": {
    "urls": [],
    "summaries": []
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-pyABF": {
    "urls": [],
    "summaries": []
  },
  "python-pyairvisual": {
    "urls": [],
    "summaries": []
  },
  "python-pybbi": {
    "urls": [],
    "summaries": []
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pydantic": {
    "urls": [],
    "summaries": []
  },
  "python-pydantic-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
    ],
    "summaries": [
      "python-pydantic-core fails to build with Python 3.14: AssertionError: Regex pattern did not match. + AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-pydantic-settings": {
    "urls": [],
    "summaries": []
  },
  "python-pydapsys": {
    "urls": [],
    "summaries": []
  },
  "python-pydepsdev": {
    "urls": [],
    "summaries": []
  },
  "python-pydicom": {
    "urls": [],
    "summaries": []
  },
  "python-pydoctor": {
    "urls": [],
    "summaries": []
  },
  "python-pyedflib": {
    "urls": [],
    "summaries": []
  },
  "python-pyelectro": {
    "urls": [],
    "summaries": []
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pyerfa": {
    "urls": [],
    "summaries": []
  },
  "python-pyforgejo": {
    "urls": [],
    "summaries": []
  },
  "python-pygmtools": {
    "urls": [],
    "summaries": []
  },
  "python-pygraphviz": {
    "urls": [],
    "summaries": []
  },
  "python-pygtkspellcheck": {
    "urls": [],
    "summaries": []
  },
  "python-pyinfra": {
    "urls": [],
    "summaries": []
  },
  "python-pykdtree": {
    "urls": [],
    "summaries": []
  },
  "python-pymapvbvd": {
    "urls": [],
    "summaries": []
  },
  "python-pymatreader": {
    "urls": [],
    "summaries": []
  },
  "python-pymdown-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350300",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336948"
    ],
    "summaries": [
      "Heads-up: python-pymdown-extensions fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-pymdown-extensions fails to build with Python 3.14: TestAbsolute.test_relative_path and TestAbsoluteFileScheme.test_relative_path AssertionErrors"
    ]
  },
  "python-pymeeus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341186"
    ],
    "summaries": [
      "python-pymeeus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pymemcache": {
    "urls": [],
    "summaries": []
  },
  "python-pymongo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356166",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341188"
    ],
    "summaries": [
      "python-pymongo fails to build with Python 3.14: DeprecationWarning: 'asyncio.iscoroutinefunction' and 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16",
      "python-pymongo: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pymssql": {
    "urls": [],
    "summaries": []
  },
  "python-pynamodb": {
    "urls": [],
    "summaries": []
  },
  "python-pynetdicom": {
    "urls": [],
    "summaries": []
  },
  "python-pynn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341189"
    ],
    "summaries": [
      "python-pynn: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyongc": {
    "urls": [],
    "summaries": []
  },
  "python-pyopencl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341190"
    ],
    "summaries": [
      "python-pyopencl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyopengl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341191"
    ],
    "summaries": [
      "python-pyopengl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyopengltk": {
    "urls": [],
    "summaries": []
  },
  "python-pypet": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341192"
    ],
    "summaries": [
      "python-pypet: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyphi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341193"
    ],
    "summaries": [
      "python-pyphi: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyqtgraph": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid-tm": {
    "urls": [],
    "summaries": []
  },
  "python-pyriemann": {
    "urls": [],
    "summaries": []
  },
  "python-pysaml2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341199"
    ],
    "summaries": [
      "python-pysaml2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pysdl2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339020"
    ],
    "summaries": [
      "python-pysdl2: FTBFS in Fedora Rawhide"
    ]
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pyspike": {
    "urls": [],
    "summaries": []
  },
  "python-pysqueezebox": {
    "urls": [],
    "summaries": []
  },
  "python-pytesseract": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341201"
    ],
    "summaries": [
      "python-pytesseract: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pytest-aiohttp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339466"
    ],
    "summaries": [
      "python-pytest-aiohttp fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-pytest-arraydiff": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342564"
    ],
    "summaries": [
      "python-pytest-asyncio fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-pytest-dependency": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354118"
    ],
    "summaries": [
      "python-pytest-dependency FTBFS due to missing tox configuration"
    ]
  },
  "python-pytest-doctestplus": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-jupyter": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-lsp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349451"
    ],
    "summaries": [
      "python-pytest-lsp fails to build with Python 3.14: warnings counts differ, resulting in AssertionError in 3 tests"
    ]
  },
  "python-pytest-mpl": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-param-files": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-randomly": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-regressions": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-testinfra": {
    "urls": [],
    "summaries": []
  },
  "python-python-fcl": {
    "urls": [],
    "summaries": []
  },
  "python-python-ulid": {
    "urls": [],
    "summaries": []
  },
  "python-pytools": {
    "urls": [],
    "summaries": []
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-pyvirtualize": {
    "urls": [],
    "summaries": []
  },
  "python-pyvlx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
    ],
    "summaries": [
      "python-pyvlx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pyvo": {
    "urls": [],
    "summaries": []
  },
  "python-pywt": {
    "urls": [],
    "summaries": []
  },
  "python-pyxdf": {
    "urls": [],
    "summaries": []
  },
  "python-quantities": {
    "urls": [],
    "summaries": []
  },
  "python-qudida": {
    "urls": [],
    "summaries": []
  },
  "python-rapidfuzz": {
    "urls": [],
    "summaries": []
  },
  "python-rdflib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343978",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336891"
    ],
    "summaries": [
      "python-rdflib fails to build with Python 3.14: AttributeError: term 'value' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'",
      "python-rdflib fails to build with Python 3.14: \"TypeError: '<' not supported between instances of 'Literal' and 'Literal'\""
    ]
  },
  "python-reactivex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
    ],
    "summaries": [
      "python-reactivex fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-redis": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345526"
    ],
    "summaries": [
      "python-redis fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f10027f31c0>"
    ]
  },
  "python-referencing": {
    "urls": [],
    "summaries": []
  },
  "python-remoto": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341205"
    ],
    "summaries": [
      "python-remoto: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-requests-gssapi": {
    "urls": [],
    "summaries": []
  },
  "python-requests-kerberos": {
    "urls": [],
    "summaries": []
  },
  "python-requests-unixsocket": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354121"
    ],
    "summaries": [
      "python-requests-unixsocket FTBFS due to missing tox configuration"
    ]
  },
  "python-rich": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350303",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339510"
    ],
    "summaries": [
      "Heads-up: python-rich fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-rich fails to build with Python 3.14: 5 test fail"
    ]
  },
  "python-robotframework": {
    "urls": [],
    "summaries": []
  },
  "python-rope": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351391"
    ],
    "summaries": [
      "python-rope fails to build with Python 3.14: ImportError while loading conftest '/builddir/build/BUILD/python-rope-1.13.0-build/rope-1.13.0/ropetest/conftest.py'.: AssertionError: assert sys.version_info < (3, 8)"
    ]
  },
  "python-rosdep": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341207"
    ],
    "summaries": [
      "python-rosdep: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-rpds-py": {
    "urls": [],
    "summaries": []
  },
  "python-rpmautospec-koji": {
    "urls": [],
    "summaries": []
  },
  "python-rq": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342234"
    ],
    "summaries": [
      "python-rq fails to build with Python 3.14: test_worker.py::HerokuWorkerShutdownTestCase::test_handle_shutdown_request shuts down the whole build"
    ]
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rstcheck-core": {
    "urls": [],
    "summaries": []
  },
  "python-ruamel-yaml": {
    "urls": [],
    "summaries": []
  },
  "python-rust-update-set": {
    "urls": [],
    "summaries": []
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-s3transfer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326933"
    ],
    "summaries": [
      "python-s3transfer fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <class 'tests.unit.test_compat.TestBaseManager.create_pid_manager.<locals>.PIDManager'>"
    ]
  },
  "python-saneyaml": {
    "urls": [],
    "summaries": []
  },
  "python-scantree": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328021"
    ],
    "summaries": [
      "python-scantree fails to build with Python 3.14: AssertionError: assert 1.2218716144561768 < (2.0 / 2)"
    ]
  },
  "python-scikit-build": {
    "urls": [],
    "summaries": []
  },
  "python-scikit-build-core": {
    "urls": [],
    "summaries": []
  },
  "python-scikit-learn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353125"
    ],
    "summaries": [
      "python-scikit-learn fails to build with Python 3.14: AssertionError in test_warn_if_metric_bool_data_no_bool and test_open_openml_url_retry_on_network_error"
    ]
  },
  "python-scikit-misc": {
    "urls": [],
    "summaries": []
  },
  "python-sciunit": {
    "urls": [],
    "summaries": []
  },
  "python-scooby": {
    "urls": [],
    "summaries": []
  },
  "python-seaborn": {
    "urls": [],
    "summaries": []
  },
  "python-sep": {
    "urls": [],
    "summaries": []
  },
  "python-sgp4": {
    "urls": [],
    "summaries": []
  },
  "python-shapely": {
    "urls": [],
    "summaries": []
  },
  "python-shortuuid": {
    "urls": [],
    "summaries": []
  },
  "python-simframe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352552"
    ],
    "summaries": [
      "python-simframe fails to build with Python 3.14: TypeError: cannot pickle 'itertools.cycle' object"
    ]
  },
  "python-simpleline": {
    "urls": [],
    "summaries": []
  },
  "python-sklearn-genetic": {
    "urls": [],
    "summaries": []
  },
  "python-sklearn-genetic-opt": {
    "urls": [],
    "summaries": []
  },
  "python-slackclient": {
    "urls": [],
    "summaries": []
  },
  "python-smart_open": {
    "urls": [],
    "summaries": []
  },
  "python-snuggs": {
    "urls": [],
    "summaries": []
  },
  "python-socks": {
    "urls": [],
    "summaries": []
  },
  "python-sortedcontainers": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-gallery": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-websupport": {
    "urls": [],
    "summaries": []
  },
  "python-spyder-kernels": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy-collectd": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy1.4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
    ],
    "summaries": [
      "python-sqlalchemy1.4 fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-sqlalchemy_schemadisplay": {
    "urls": [],
    "summaries": []
  },
  "python-ssh-python": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350333"
    ],
    "summaries": [
      "python-ssh-python fails to build with Python 3.14: SessionTest.test_set_timeout: ssh.exceptions.SSHError: (-1, b'Invalid argument in ssh_options_set')"
    ]
  },
  "python-stack-data": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350304",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345532"
    ],
    "summaries": [
      "Heads-up: python-stack-data fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-stack-data fails to build with Python 3.14: test_example: IndexError: list index out of range"
    ]
  },
  "python-stackprinter": {
    "urls": [],
    "summaries": []
  },
  "python-statsmodels": {
    "urls": [],
    "summaries": []
  },
  "python-stdlibs": {
    "urls": [],
    "summaries": []
  },
  "python-steam": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341218"
    ],
    "summaries": [
      "python-steam: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-steps": {
    "urls": [],
    "summaries": []
  },
  "python-streamlink": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353127"
    ],
    "summaries": [
      "python-streamlink fails to build with Python 3.14: test_deprecated: AssetionError: Left contains one more item: <warnings.WarningMessage object at 0x7fd80afa3410>"
    ]
  },
  "python-succulent": {
    "urls": [],
    "summaries": []
  },
  "python-supersmoother": {
    "urls": [],
    "summaries": []
  },
  "python-svg2tikz": {
    "urls": [],
    "summaries": []
  },
  "python-swagger-spec-validator": {
    "urls": [],
    "summaries": []
  },
  "python-tables": {
    "urls": [],
    "summaries": []
  },
  "python-tabulate": {
    "urls": [],
    "summaries": []
  },
  "python-telnetlib3": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354126"
    ],
    "summaries": [
      "python-telnetlib3 FTBFS due to missing tox configuration"
    ]
  },
  "python-tenacity": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
    ],
    "summaries": [
      "python-tenacity fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-teslajsonpy": {
    "urls": [],
    "summaries": []
  },
  "python-testing.postgresql": {
    "urls": [],
    "summaries": []
  },
  "python-texext": {
    "urls": [],
    "summaries": []
  },
  "python-textdistance": {
    "urls": [],
    "summaries": []
  },
  "python-textile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354127"
    ],
    "summaries": [
      "python-textile FTBFS due to missing tox configuration"
    ]
  },
  "python-textual": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341224"
    ],
    "summaries": [
      "python-textual: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-threadpoolctl": {
    "urls": [],
    "summaries": []
  },
  "python-tifffile": {
    "urls": [],
    "summaries": []
  },
  "python-tilestache": {
    "urls": [],
    "summaries": []
  },
  "python-timeout-decorator": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354129"
    ],
    "summaries": [
      "python-timeout-decorator FTBFS due to missing tox configuration"
    ]
  },
  "python-tinygrad": {
    "urls": [],
    "summaries": []
  },
  "python-toml": {
    "urls": [],
    "summaries": []
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-tornado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
    ],
    "summaries": [
      "python-tornado fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-towncrier": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354131"
    ],
    "summaries": [
      "python-towncrier FTBFS due to missing tox configuration"
    ]
  },
  "python-traitsui": {
    "urls": [],
    "summaries": []
  },
  "python-transforms3d": {
    "urls": [],
    "summaries": []
  },
  "python-treq": {
    "urls": [],
    "summaries": []
  },
  "python-trio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345516"
    ],
    "summaries": [
      "python-trio fails to build with Python 3.14: test_ki_protection_doesnt_leave_cyclic_garbage: Left contains one more item: <coroutine object test_ki_protection_doesnt_leave_cyclic_garbage at 0x7fbaa2f162c0>"
    ]
  },
  "python-triton": {
    "urls": [],
    "summaries": []
  },
  "python-trx-python": {
    "urls": [],
    "summaries": []
  },
  "python-ttfautohint-py": {
    "urls": [],
    "summaries": []
  },
  "python-tvb-gdist": {
    "urls": [],
    "summaries": []
  },
  "python-twilio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341229"
    ],
    "summaries": [
      "python-twilio: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-twisted": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342754"
    ],
    "summaries": [
      "python-twisted fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'. + more"
    ]
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-txws": {
    "urls": [],
    "summaries": []
  },
  "python-txzmq": {
    "urls": [],
    "summaries": []
  },
  "python-typeguard": {
    "urls": [],
    "summaries": []
  },
  "python-typing-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336937"
    ],
    "summaries": [
      "python-typing-extensions fails to build with Python 3.14: test_drop_in_for_typing: AssertionError: self.assertGreaterEqual(te_all, t_all - exceptions)"
    ]
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-ufoLib2": {
    "urls": [],
    "summaries": []
  },
  "python-urllib-gssapi": {
    "urls": [],
    "summaries": []
  },
  "python-urwid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
    ],
    "summaries": [
      "python-urwid fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-usort": {
    "urls": [],
    "summaries": []
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341233",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop: FTBFS in Fedora rawhide/f42",
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-validator-collection": {
    "urls": [],
    "summaries": []
  },
  "python-valkey": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349444"
    ],
    "summaries": [
      "python-valkey fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f5aa68cddd0>"
    ]
  },
  "python-vascpy": {
    "urls": [],
    "summaries": []
  },
  "python-vcrpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342566"
    ],
    "summaries": [
      "python-vcrpy fails to build with Python 3.14: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-versioningit": {
    "urls": [],
    "summaries": []
  },
  "python-vhacdx": {
    "urls": [],
    "summaries": []
  },
  "python-virtualbmc": {
    "urls": [],
    "summaries": []
  },
  "python-vpoller": {
    "urls": [],
    "summaries": []
  },
  "python-warlock": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354135"
    ],
    "summaries": [
      "python-warlock FTBFS due to missing tox configuration"
    ]
  },
  "python-watchfiles": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339462"
    ],
    "summaries": [
      "python-watchfiles fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-wavio": {
    "urls": [],
    "summaries": []
  },
  "python-webob": {
    "urls": [],
    "summaries": []
  },
  "python-wheel": {
    "urls": [],
    "summaries": []
  },
  "python-willow": {
    "urls": [],
    "summaries": []
  },
  "python-wled": {
    "urls": [],
    "summaries": []
  },
  "python-wordcloud": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335908"
    ],
    "summaries": [
      "python-wordcloud fails to build with Python 3.14: test_cli_as_executable: AssertionError: assert expected_output in out if ret_code == 0 else err"
    ]
  },
  "python-x2go": {
    "urls": [],
    "summaries": []
  },
  "python-yamlloader": {
    "urls": [],
    "summaries": []
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-yarl": {
    "urls": [],
    "summaries": []
  },
  "python-yfinance": {
    "urls": [],
    "summaries": []
  },
  "python-yte": {
    "urls": [],
    "summaries": []
  },
  "python-zeep": {
    "urls": [],
    "summaries": []
  },
  "python-zict": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328012"
    ],
    "summaries": [
      "python-zict fails to build with Python 3.14: test_stress_different_keys_threadsafe Timeout"
    ]
  },
  "python-zmq": {
    "urls": [],
    "summaries": []
  },
  "python-zoidberg": {
    "urls": [],
    "summaries": []
  },
  "python-zope-configuration": {
    "urls": [],
    "summaries": []
  },
  "python-zope-exceptions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341240"
    ],
    "summaries": [
      "python-zope-exceptions: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-zope-hookable": {
    "urls": [],
    "summaries": []
  },
  "python-zope-testrunner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335907"
    ],
    "summaries": [
      "python-zope-testrunner fails to build with Python 3.14: difference in the asserted content in testrunner-edge-cases.rst"
    ]
  },
  "python3-exiv2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354137"
    ],
    "summaries": [
      "python3-exiv2 FTBFS due to missing tox configuration"
    ]
  },
  "python3-saml": {
    "urls": [],
    "summaries": []
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "quodlibet": {
    "urls": [],
    "summaries": []
  },
  "rebase-helper": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352551"
    ],
    "summaries": [
      "rebase-helper fails to build with Python 3.14: AssertionError in TestCLI.test_cli_unit and TestConfig.test_merge"
    ]
  },
  "resalloc": {
    "urls": [],
    "summaries": []
  },
  "root": {
    "urls": [],
    "summaries": []
  },
  "rpkg": {
    "urls": [],
    "summaries": []
  },
  "rust2rpm": {
    "urls": [],
    "summaries": []
  },
  "salt": {
    "urls": [],
    "summaries": []
  },
  "satyr": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
    ],
    "summaries": [
      "satyr fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestDistances.test_distances_part_parallel.<locals>.do_test.<locals>.compute_part at 0x7f7f845f2560>"
    ]
  },
  "scipy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341927"
    ],
    "summaries": [
      "scipy fails to build with Python 3.14: TestSystematic::test_bessely, TestSystematic::test_bessely_int and TestSystematic::test_wrightomega fail"
    ]
  },
  "secrets": {
    "urls": [],
    "summaries": []
  },
  "sgtk-menu": {
    "urls": [],
    "summaries": []
  },
  "sherlock-project": {
    "urls": [],
    "summaries": []
  },
  "showtime": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350334"
    ],
    "summaries": [
      "showtime fails to build with Python 3.14: ValueError: Namespace GIRepository not available for version 2.0"
    ]
  },
  "shybrid": {
    "urls": [],
    "summaries": []
  },
  "signon-glib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341348"
    ],
    "summaries": [
      "signon-glib: FTBFS in Fedora rawhide/f42"
    ]
  },
  "smoldyn": {
    "urls": [],
    "summaries": []
  },
  "solaar": {
    "urls": [],
    "summaries": []
  },
  "spglib": {
    "urls": [],
    "summaries": []
  },
  "subversion": {
    "urls": [],
    "summaries": []
  },
  "swift-lang": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341403"
    ],
    "summaries": [
      "swift-lang: FTBFS in Fedora rawhide/f42"
    ]
  },
  "sympy": {
    "urls": [],
    "summaries": []
  },
  "sysmontask": {
    "urls": [],
    "summaries": []
  },
  "tree-sitter-java": {
    "urls": [],
    "summaries": []
  },
  "trelby": {
    "urls": [],
    "summaries": []
  },
  "tuned": {
    "urls": [],
    "summaries": []
  },
  "ufw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341477"
    ],
    "summaries": [
      "ufw: FTBFS in Fedora rawhide/f42"
    ]
  },
  "uhd": {
    "urls": [],
    "summaries": []
  },
  "ulauncher": {
    "urls": [],
    "summaries": []
  },
  "urh": {
    "urls": [],
    "summaries": []
  },
  "ursa-major": {
    "urls": [],
    "summaries": []
  },
  "vapoursynth": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2354141"
    ],
    "summaries": [
      "vapoursynth FTBFS due to missing tox configuration"
    ]
  },
  "variety": {
    "urls": [],
    "summaries": []
  },
  "veusz": {
    "urls": [],
    "summaries": []
  },
  "vigra": {
    "urls": [],
    "summaries": []
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "weasyprint": {
    "urls": [],
    "summaries": []
  },
  "whatip": {
    "urls": [],
    "summaries": []
  },
  "xcfun": {
    "urls": [],
    "summaries": []
  },
  "xpra": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350289"
    ],
    "summaries": [
      "xpra fails to build from source with Python 3.14: RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase."
    ]
  },
  "yt-dlp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2345522"
    ],
    "summaries": [
      "yt-dlp fails to build with Python 3.14: TestTraversal.test_traversal_morsel: AssertionError: `...` should yield all values: Left contains one more item: 'item_value'"
    ]
  },
  "zeek": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341601"
    ],
    "summaries": [
      "zeek: FTBFS in Fedora rawhide/f42"
    ]
  },
  "zfp": {
    "urls": [],
    "summaries": []
  }
}