{
  "Mayavi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351390"
    ],
    "summaries": [
      "Mayavi fails to build with Python 3.14: TestMayaviGarbageCollection.test_mlab_scene_model_with_gui: IndexError: list index out of range"
    ]
  },
  "ansible": {
    "urls": [],
    "summaries": []
  },
  "asv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339908"
    ],
    "summaries": [
      "asv: FTBFS in Fedora rawhide/f42"
    ]
  },
  "avogadro2-libs": {
    "urls": [],
    "summaries": []
  },
  "bandit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351393"
    ],
    "summaries": [
      "bandit fails to build with Python 3.14: TypeError: Error: Str is not a valid node type in AST"
    ]
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "cantor": {
    "urls": [],
    "summaries": []
  },
  "ceph": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336913"
    ],
    "summaries": [
      "ceph fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "chirp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2361634"
    ],
    "summaries": [
      "chirp FTBFS in rawhide"
    ]
  },
  "conda-build": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356162"
    ],
    "summaries": [
      "conda-build fails to build with Python 3.14: TypeError: _WorkItem.__init__() takes 3 positional arguments but 5 were given"
    ]
  },
  "copr-backend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351386"
    ],
    "summaries": [
      "copr-backend fails to build with Python 3.14: TestActionWorkerManager.test_add_task_for_running_worker: TypeError: cannot pickle 'itertools.count' object"
    ]
  },
  "criu": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2365821"
    ],
    "summaries": [
      "criu fails to build with Python 3.14: protobuf - TypeError: Metaclasses with custom tp_new are not supported."
    ]
  },
  "gedit": {
    "urls": [],
    "summaries": []
  },
  "gfal2-python": {
    "urls": [],
    "summaries": []
  },
  "gnofract4d": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339539"
    ],
    "summaries": [
      "gnofract4d fails to build with Python 3.14: AssertionError: 'ct_sin6 = (0.841471,-0)' != 'ct_sin6 = (0.841471,0)'"
    ]
  },
  "httpie": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350335"
    ],
    "summaries": [
      "httpie fails to build with Python 3.14: test_lazy_choices_help: AssertionError: Expected 'getter' to not have been called. Called 1 times."
    ]
  },
  "kitty": {
    "urls": [],
    "summaries": []
  },
  "kmymoney": {
    "urls": [],
    "summaries": []
  },
  "kvirc": {
    "urls": [],
    "summaries": []
  },
  "libreoffice": {
    "urls": [],
    "summaries": []
  },
  "ocrmypdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357508"
    ],
    "summaries": [
      "ocrmypdf fails to build with Python 3.14: multiprocessing.Process now starts with forkserver method instead of fork, causing pickling error"
    ]
  },
  "onnx": {
    "urls": [],
    "summaries": []
  },
  "openapi-python-client": {
    "urls": [],
    "summaries": []
  },
  "openvino": {
    "urls": [],
    "summaries": []
  },
  "paraview": {
    "urls": [],
    "summaries": []
  },
  "pcs": {
    "urls": [],
    "summaries": []
  },
  "poetry": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351383"
    ],
    "summaries": [
      "poetry fails to build with Python 3.14: AssertionError in test_isolated_env_install_discards_requirements_not_needed_by_env and test_python_get_preferred_default"
    ]
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pychromecast": {
    "urls": [],
    "summaries": []
  },
  "pylint": {
    "urls": [],
    "summaries": []
  },
  "python-TestSlide": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350306",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343971"
    ],
    "summaries": [
      "Heads-up: python-TestSlide fails to build with python-pygments 2.19.1 on Fedora 43",
      "python-TestSlide fails to build with Python 3.14: ERROR collecting tests/mock_callable_testslide.py: RuntimeError: dictionary changed size during iteration"
    ]
  },
  "python-aioesphomeapi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366202"
    ],
    "summaries": [
      "python-aioesphomeapi fails to build with Python 3.14: protobuf: TypeError: Metaclasses with custom tp_new are not supported"
    ]
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-apsw": {
    "urls": [],
    "summaries": []
  },
  "python-astdoc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349452"
    ],
    "summaries": [
      "python-astdoc fails to build with Python 3.14: 3 doctests fail, e.g.: Expected: <ast.Name object at 0x...> Got: Name(id='int', ctx=Load())"
    ]
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341130",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado: FTBFS in Fedora rawhide/f42",
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-aws-sam-translator": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353126"
    ],
    "summaries": [
      "python-aws-sam-translator fails to build with Python 3.14: 77 test failures, 4 error"
    ]
  },
  "python-axolotl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366200"
    ],
    "summaries": [
      "python-axolotl fails to build with Python 3.14: protobuf: TypeError: Metaclasses with custom tp_new are not supported."
    ]
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341131",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype: FTBFS in Fedora rawhide/f42",
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-behave": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339094"
    ],
    "summaries": [
      "python-behave fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-boutdata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352553"
    ],
    "summaries": [
      "python-boutdata fails to build with Python 3.14: NotImplementedError: Dataset is not picklable"
    ]
  },
  "python-bsmschema": {
    "urls": [],
    "summaries": []
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-carbon": {
    "urls": [],
    "summaries": []
  },
  "python-chalice": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342568"
    ],
    "summaries": [
      "python-chalice fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-dnspython": {
    "urls": [],
    "summaries": []
  },
  "python-doubleratchet": {
    "urls": [],
    "summaries": []
  },
  "python-efel": {
    "urls": [],
    "summaries": []
  },
  "python-flake8-comprehensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351385"
    ],
    "summaries": [
      "python-flake8-comprehensions fails to build with Python 3.14: Unnecessary reversed call around sorted() in 10 tests"
    ]
  },
  "python-fsleyes-widgets": {
    "urls": [],
    "summaries": []
  },
  "python-fsspec": {
    "urls": [],
    "summaries": []
  },
  "python-giacpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341608"
    ],
    "summaries": [
      "python-giacpy: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-googleapis-common-protos": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2365822"
    ],
    "summaries": [
      "python-googleapis-common-protos fails to build with Python 3.14: protobuf: TypeError: Metaclasses with custom tp_new are not supported."
    ]
  },
  "python-howdoi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342558"
    ],
    "summaries": [
      "python-howdoi fails to build with Python 3.14: AssertionError: 'ERROR: Unable to reach google. Do you need to use a proxy? + json.decoder.JSONDecodeError"
    ]
  },
  "python-imbalanced-learn": {
    "urls": [],
    "summaries": []
  },
  "python-josepy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2359514"
    ],
    "summaries": [
      "python-josepy fails to build with Python 3.14: ValueError: Field `alg` in JSONObject `Header` has no type annotation."
    ]
  },
  "python-jupytext": {
    "urls": [],
    "summaries": []
  },
  "python-lfpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341168"
    ],
    "summaries": [
      "python-lfpy: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-llama-cpp-python": {
    "urls": [],
    "summaries": []
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-metakernel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357903"
    ],
    "summaries": [
      "python-metakernel fails to build with Python 3.14: AssertionError in test_parallel_magic"
    ]
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-neatdend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341170"
    ],
    "summaries": [
      "python-neatdend: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-network-runner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341172"
    ],
    "summaries": [
      "python-network-runner: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-niaarmts": {
    "urls": [],
    "summaries": []
  },
  "python-nikola": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341174"
    ],
    "summaries": [
      "python-nikola: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-ollama": {
    "urls": [],
    "summaries": []
  },
  "python-osc-lib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351387"
    ],
    "summaries": [
      "python-osc-lib fails to build with Python 3.14: testtools.matchers._impl.MismatchError in 4 tests"
    ]
  },
  "python-packvers": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341178"
    ],
    "summaries": [
      "python-packvers: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pika": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351384"
    ],
    "summaries": [
      "python-pika fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-praw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342562"
    ],
    "summaries": [
      "python-praw fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-pydantic-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
    ],
    "summaries": [
      "python-pydantic-core fails to build with Python 3.14: AssertionError: Regex pattern did not match. + AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-pydantic-settings": {
    "urls": [],
    "summaries": []
  },
  "python-pyforgejo": {
    "urls": [],
    "summaries": []
  },
  "python-pymeeus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341186"
    ],
    "summaries": [
      "python-pymeeus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pypet": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341192"
    ],
    "summaries": [
      "python-pypet: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyphi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341193"
    ],
    "summaries": [
      "python-pyphi: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyregion": {
    "urls": [],
    "summaries": []
  },
  "python-pysaml2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341199"
    ],
    "summaries": [
      "python-pysaml2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pytest-lsp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349451"
    ],
    "summaries": [
      "python-pytest-lsp fails to build with Python 3.14: warnings counts differ, resulting in AssertionError in 3 tests"
    ]
  },
  "python-pytest-testinfra": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2361631"
    ],
    "summaries": [
      "python-pytest-testinfra FTBFS in rawhide"
    ]
  },
  "python-python-ulid": {
    "urls": [],
    "summaries": []
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-rasterio": {
    "urls": [],
    "summaries": []
  },
  "python-rdflib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343978",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336891"
    ],
    "summaries": [
      "python-rdflib fails to build with Python 3.14: AttributeError: term 'value' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'",
      "python-rdflib fails to build with Python 3.14: \"TypeError: '<' not supported between instances of 'Literal' and 'Literal'\""
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-remoto": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341205"
    ],
    "summaries": [
      "python-remoto: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-rope": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351391"
    ],
    "summaries": [
      "python-rope fails to build with Python 3.14: ImportError while loading conftest '/builddir/build/BUILD/python-rope-1.13.0-build/rope-1.13.0/ropetest/conftest.py'.: AssertionError: assert sys.version_info < (3, 8)"
    ]
  },
  "python-rq": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342234"
    ],
    "summaries": [
      "python-rq fails to build with Python 3.14: test_worker.py::HerokuWorkerShutdownTestCase::test_handle_shutdown_request shuts down the whole build"
    ]
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-scikit-build": {
    "urls": [],
    "summaries": []
  },
  "python-scipy-doctest": {
    "urls": [],
    "summaries": []
  },
  "python-sentry-sdk": {
    "urls": [],
    "summaries": []
  },
  "python-simframe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352552"
    ],
    "summaries": [
      "python-simframe fails to build with Python 3.14: TypeError: cannot pickle 'itertools.cycle' object"
    ]
  },
  "python-smart_open": {
    "urls": [],
    "summaries": []
  },
  "python-steam": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341218"
    ],
    "summaries": [
      "python-steam: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-streamlink": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353127"
    ],
    "summaries": [
      "python-streamlink fails to build with Python 3.14: test_deprecated: AssetionError: Left contains one more item: <warnings.WarningMessage object at 0x7fd80afa3410>"
    ]
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-torch": {
    "urls": [],
    "summaries": []
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-ufoLib2": {
    "urls": [],
    "summaries": []
  },
  "python-uranium": {
    "urls": [],
    "summaries": []
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341233",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop: FTBFS in Fedora rawhide/f42",
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-wordcloud": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335908"
    ],
    "summaries": [
      "python-wordcloud fails to build with Python 3.14: test_cli_as_executable: AssertionError: assert expected_output in out if ret_code == 0 else err"
    ]
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-zarr": {
    "urls": [],
    "summaries": []
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "rebase-helper": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352551"
    ],
    "summaries": [
      "rebase-helper fails to build with Python 3.14: AssertionError in TestCLI.test_cli_unit and TestConfig.test_merge"
    ]
  },
  "swift-lang": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341403"
    ],
    "summaries": [
      "swift-lang: FTBFS in Fedora rawhide/f42"
    ]
  },
  "tree-sitter-java": {
    "urls": [],
    "summaries": []
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "xpra": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2350289"
    ],
    "summaries": [
      "xpra fails to build from source with Python 3.14: RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase."
    ]
  }
}