{
  "GeographicLib": {
    "urls": [],
    "summaries": []
  },
  "adapt": {
    "urls": [],
    "summaries": []
  },
  "alot": {
    "urls": [],
    "summaries": []
  },
  "ara": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331346"
    ],
    "summaries": [
      "ara fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "awscli2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336910"
    ],
    "summaries": [
      "awscli2 fails to build with Python 3.14: ValueError('badly formed help string'),  KeyError: 'PATH'"
    ]
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "bluechi": {
    "urls": [],
    "summaries": []
  },
  "boom-boot": {
    "urls": [],
    "summaries": []
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "botan": {
    "urls": [],
    "summaries": []
  },
  "brltty": {
    "urls": [],
    "summaries": []
  },
  "ceph": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336913"
    ],
    "summaries": [
      "ceph fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "chirp": {
    "urls": [],
    "summaries": []
  },
  "cjdns": {
    "urls": [],
    "summaries": []
  },
  "cmake": {
    "urls": [],
    "summaries": []
  },
  "cockpit": {
    "urls": [],
    "summaries": []
  },
  "colin": {
    "urls": [],
    "summaries": []
  },
  "compizconfig-python": {
    "urls": [],
    "summaries": []
  },
  "condor": {
    "urls": [],
    "summaries": []
  },
  "conu": {
    "urls": [],
    "summaries": []
  },
  "copr-keygen": {
    "urls": [],
    "summaries": []
  },
  "cryptlib": {
    "urls": [],
    "summaries": []
  },
  "debconf": {
    "urls": [],
    "summaries": []
  },
  "dee": {
    "urls": [],
    "summaries": []
  },
  "diceware": {
    "urls": [],
    "summaries": []
  },
  "did": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328006"
    ],
    "summaries": [
      "did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'"
    ]
  },
  "dionaea": {
    "urls": [],
    "summaries": []
  },
  "dlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328014"
    ],
    "summaries": [
      "dlib fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "dnfdragora": {
    "urls": [],
    "summaries": []
  },
  "dnsconfd": {
    "urls": [],
    "summaries": []
  },
  "dogtag-pki": {
    "urls": [],
    "summaries": []
  },
  "dxf2gcode": {
    "urls": [],
    "summaries": []
  },
  "electron-cash": {
    "urls": [],
    "summaries": []
  },
  "elements-alexandria": {
    "urls": [],
    "summaries": []
  },
  "enki": {
    "urls": [],
    "summaries": []
  },
  "espresso": {
    "urls": [],
    "summaries": []
  },
  "esptool": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331345"
    ],
    "summaries": [
      "esptool fails to build with Python 3.14: AssertionError: assert 'usage: __main__.py [-h]' in 'espefuse.py v4.8.1\\nusage: python3 -m espefuse [-h]\\n                           [--chip {auto,esp32,esp32c2,esp32c3,e... --extend-efuse-table EXTEND_EFUSE_TABLE\\"
    ]
  },
  "fedfind": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336945"
    ],
    "summaries": [
      "fedfind: FTBFS in Fedora Rawhide: AssertionError in TestRelease.test_all_stable"
    ]
  },
  "fedora-business-cards": {
    "urls": [],
    "summaries": []
  },
  "fedscm-admin": {
    "urls": [],
    "summaries": []
  },
  "flent": {
    "urls": [],
    "summaries": []
  },
  "fontforge": {
    "urls": [],
    "summaries": []
  },
  "freeradius": {
    "urls": [],
    "summaries": []
  },
  "fros": {
    "urls": [],
    "summaries": []
  },
  "gdl": {
    "urls": [],
    "summaries": []
  },
  "gns3-server": {
    "urls": [],
    "summaries": []
  },
  "gnuradio": {
    "urls": [],
    "summaries": []
  },
  "gom": {
    "urls": [],
    "summaries": []
  },
  "h5py": {
    "urls": [],
    "summaries": []
  },
  "hokuyoaist": {
    "urls": [],
    "summaries": []
  },
  "home-assistant-cli": {
    "urls": [],
    "summaries": []
  },
  "hplip": {
    "urls": [],
    "summaries": []
  },
  "i2c-tools": {
    "urls": [],
    "summaries": []
  },
  "ibus": {
    "urls": [],
    "summaries": []
  },
  "ikiwiki": {
    "urls": [],
    "summaries": []
  },
  "insight": {
    "urls": [],
    "summaries": []
  },
  "intelhex": {
    "urls": [],
    "summaries": []
  },
  "ioc-writer": {
    "urls": [],
    "summaries": []
  },
  "ipa-hcc": {
    "urls": [],
    "summaries": []
  },
  "ipsilon": {
    "urls": [],
    "summaries": []
  },
  "iscsi-initiator-utils": {
    "urls": [],
    "summaries": []
  },
  "jc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331343"
    ],
    "summaries": [
      "jc fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "kernel": {
    "urls": [],
    "summaries": []
  },
  "kicad": {
    "urls": [],
    "summaries": []
  },
  "kitty": {
    "urls": [],
    "summaries": []
  },
  "kiwi": {
    "urls": [],
    "summaries": []
  },
  "koji": {
    "urls": [],
    "summaries": []
  },
  "lammps": {
    "urls": [],
    "summaries": []
  },
  "lasso": {
    "urls": [],
    "summaries": []
  },
  "lecm": {
    "urls": [],
    "summaries": []
  },
  "lector": {
    "urls": [],
    "summaries": []
  },
  "lhapdf": {
    "urls": [],
    "summaries": []
  },
  "libarrow": {
    "urls": [],
    "summaries": []
  },
  "libcamera": {
    "urls": [],
    "summaries": []
  },
  "libcomps": {
    "urls": [],
    "summaries": []
  },
  "libdnet": {
    "urls": [],
    "summaries": []
  },
  "libfreenect": {
    "urls": [],
    "summaries": []
  },
  "libgit2-glib": {
    "urls": [],
    "summaries": []
  },
  "libgpiod": {
    "urls": [],
    "summaries": []
  },
  "libiio": {
    "urls": [],
    "summaries": []
  },
  "libnl3": {
    "urls": [],
    "summaries": []
  },
  "libnuml": {
    "urls": [],
    "summaries": []
  },
  "libnvme": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325194"
    ],
    "summaries": [
      "libnvme fails to build with Python 3.14: /usr/include/python3.14/pyport.h:629:35: error: missing ')' after \"__has_attribute\""
    ]
  },
  "libpst": {
    "urls": [],
    "summaries": []
  },
  "libstoragemgmt": {
    "urls": [],
    "summaries": []
  },
  "libvirt-python": {
    "urls": [],
    "summaries": []
  },
  "libvirt-test-API": {
    "urls": [],
    "summaries": []
  },
  "link-grammar": {
    "urls": [],
    "summaries": []
  },
  "linode-cli": {
    "urls": [],
    "summaries": []
  },
  "llvm": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336915"
    ],
    "summaries": [
      "llvm fails to build with Python 3.14: tools/opt-viewer/suppress.test: AttributeError: type object 'Passed' has no attribute 'demangler_lock'"
    ]
  },
  "lorax": {
    "urls": [],
    "summaries": []
  },
  "lrcalc": {
    "urls": [],
    "summaries": []
  },
  "mathgl": {
    "urls": [],
    "summaries": []
  },
  "med": {
    "urls": [],
    "summaries": []
  },
  "mkdocs-bootswatch": {
    "urls": [],
    "summaries": []
  },
  "mlpack": {
    "urls": [],
    "summaries": []
  },
  "mlt": {
    "urls": [],
    "summaries": []
  },
  "mod_wsgi": {
    "urls": [],
    "summaries": []
  },
  "mogui": {
    "urls": [],
    "summaries": []
  },
  "moose": {
    "urls": [],
    "summaries": []
  },
  "mopidy": {
    "urls": [],
    "summaries": []
  },
  "mopidy-mpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336892"
    ],
    "summaries": [
      "mopidy-mpd: FTBFS in Fedora Rawhide"
    ]
  },
  "morphio": {
    "urls": [],
    "summaries": []
  },
  "mpi4py": {
    "urls": [],
    "summaries": []
  },
  "nanovna-saver": {
    "urls": [],
    "summaries": []
  },
  "needrestart": {
    "urls": [],
    "summaries": []
  },
  "netcdf4-python": {
    "urls": [],
    "summaries": []
  },
  "nextpnr": {
    "urls": [],
    "summaries": []
  },
  "nfs-ganesha": {
    "urls": [],
    "summaries": []
  },
  "nordugrid-arc-nagios-plugins": {
    "urls": [],
    "summaries": []
  },
  "numpy": {
    "urls": [],
    "summaries": []
  },
  "nut": {
    "urls": [],
    "summaries": []
  },
  "nvmetcli": {
    "urls": [],
    "summaries": []
  },
  "nwchem": {
    "urls": [],
    "summaries": []
  },
  "obs-studio": {
    "urls": [],
    "summaries": []
  },
  "offlineimap": {
    "urls": [],
    "summaries": []
  },
  "openbabel": {
    "urls": [],
    "summaries": []
  },
  "openmeeg": {
    "urls": [],
    "summaries": []
  },
  "openmpi": {
    "urls": [],
    "summaries": []
  },
  "openscap-report": {
    "urls": [],
    "summaries": []
  },
  "openshot": {
    "urls": [],
    "summaries": []
  },
  "opentrep": {
    "urls": [],
    "summaries": []
  },
  "openwsman": {
    "urls": [],
    "summaries": []
  },
  "osh": {
    "urls": [],
    "summaries": []
  },
  "oz": {
    "urls": [],
    "summaries": []
  },
  "pcs": {
    "urls": [],
    "summaries": []
  },
  "pdc-client": {
    "urls": [],
    "summaries": []
  },
  "plplot": {
    "urls": [],
    "summaries": []
  },
  "pocketsphinx": {
    "urls": [],
    "summaries": []
  },
  "poezio": {
    "urls": [],
    "summaries": []
  },
  "portmidi": {
    "urls": [],
    "summaries": []
  },
  "postgresql15": {
    "urls": [],
    "summaries": []
  },
  "postgresql16": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332981"
    ],
    "summaries": [
      "postgresql16-16.3-7.fc42 FTBFS: tests fail with tzdata-2024b"
    ]
  },
  "postgresql17": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332978",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327967"
    ],
    "summaries": [
      "postgresql17-17.0-1.fc42 FTBFS: RPM build errors: line 227: second Description",
      "postgresql17 fails to build with Python 3.14: jsonb_jsonpath fails: - \"12:34:56-07:00\" != + \"12:34:56-08:00\""
    ]
  },
  "powerline": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336943"
    ],
    "summaries": [
      "powerline fails to build with Python 3.14: ValueError: argument groups cannot be nested"
    ]
  },
  "prewikka": {
    "urls": [],
    "summaries": []
  },
  "printrun": {
    "urls": [],
    "summaries": []
  },
  "profanity": {
    "urls": [],
    "summaries": []
  },
  "protobuf": {
    "urls": [],
    "summaries": []
  },
  "protonvpn-cli": {
    "urls": [],
    "summaries": []
  },
  "pybind11": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336889"
    ],
    "summaries": [
      "pybind11 fails to build with Python 3.14: AttributeError: 'pybind11_tests.pickling.PickleableWithDict' object has no attribute 'dynamic' + AssertionError"
    ]
  },
  "pycairo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322709"
    ],
    "summaries": [
      "pycairo fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pygame": {
    "urls": [],
    "summaries": []
  },
  "pygsl": {
    "urls": [],
    "summaries": []
  },
  "pykka": {
    "urls": [],
    "summaries": []
  },
  "pymilia": {
    "urls": [],
    "summaries": []
  },
  "pyproj": {
    "urls": [],
    "summaries": []
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pystatgrab": {
    "urls": [],
    "summaries": []
  },
  "pysubnettree": {
    "urls": [],
    "summaries": []
  },
  "python-APScheduler": {
    "urls": [],
    "summaries": []
  },
  "python-AppTools": {
    "urls": [],
    "summaries": []
  },
  "python-Automat": {
    "urls": [],
    "summaries": []
  },
  "python-Bottleneck": {
    "urls": [],
    "summaries": []
  },
  "python-XStatic-roboto-fontface": {
    "urls": [],
    "summaries": []
  },
  "python-abimap": {
    "urls": [],
    "summaries": []
  },
  "python-accuweather": {
    "urls": [],
    "summaries": []
  },
  "python-adafruit-pureio": {
    "urls": [],
    "summaries": []
  },
  "python-advisory-parser": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-cors": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-oauthlib": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-sse-client": {
    "urls": [],
    "summaries": []
  },
  "python-aioresponses": {
    "urls": [],
    "summaries": []
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-ansible-pylibssh": {
    "urls": [],
    "summaries": []
  },
  "python-ansicolor": {
    "urls": [],
    "summaries": []
  },
  "python-anyconfig": {
    "urls": [],
    "summaries": []
  },
  "python-anyio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328710"
    ],
    "summaries": [
      "python-anyio fails to build with Python 3.14: AttributeError: '_UnixDefaultEventLoopPolicy' object has no attribute 'get_child_watcher' && TypeError: PurePath.relative_to() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-apsw": {
    "urls": [],
    "summaries": []
  },
  "python-aresponses": {
    "urls": [],
    "summaries": []
  },
  "python-ase": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336912"
    ],
    "summaries": [
      "python-ase: FTBFS in Fedora Rawhide: ImportError: cannot import name 'VisibleDeprecationWarning' from 'numpy' (/usr/lib64/python3.13/site-packages/numpy/__init__.py)"
    ]
  },
  "python-asteval": {
    "urls": [],
    "summaries": []
  },
  "python-astroid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
    ],
    "summaries": [
      "python-astroid fails to build with Python 3.14: astroid.exceptions.InferenceError: StopIteration raised without any error information."
    ]
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-attrs": {
    "urls": [],
    "summaries": []
  },
  "python-auth-credential": {
    "urls": [],
    "summaries": []
  },
  "python-autocommand": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
    ],
    "summaries": [
      "python-autocommand fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-automaton": {
    "urls": [],
    "summaries": []
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-backrefs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325184"
    ],
    "summaries": [
      "python-backrefs fails to build with Python 3.14: Failed to acquire all needed Unicode files!"
    ]
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-beautifulsoup4": {
    "urls": [],
    "summaries": []
  },
  "python-behave": {
    "urls": [],
    "summaries": []
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-biscuits": {
    "urls": [],
    "summaries": []
  },
  "python-blinker": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325193"
    ],
    "summaries": [
      "python-blinker fails to build with Python 3.14: pluggy.PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown."
    ]
  },
  "python-bravado": {
    "urls": [],
    "summaries": []
  },
  "python-btrfs": {
    "urls": [],
    "summaries": []
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-catkin_lint": {
    "urls": [],
    "summaries": []
  },
  "python-catkin_pkg": {
    "urls": [],
    "summaries": []
  },
  "python-catkin_tools": {
    "urls": [],
    "summaries": []
  },
  "python-cattrs": {
    "urls": [],
    "summaries": []
  },
  "python-cbor2": {
    "urls": [],
    "summaries": []
  },
  "python-cffi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336935"
    ],
    "summaries": [
      "python-cffi fails to build with Python 3.14:  TestNewFFI1.test_import_from_lib: TypeError: bad argument type for built-in operation + multiple Warnings"
    ]
  },
  "python-cftime": {
    "urls": [],
    "summaries": []
  },
  "python-cinderclient": {
    "urls": [],
    "summaries": []
  },
  "python-citeproc-py": {
    "urls": [],
    "summaries": []
  },
  "python-cliff-tablib": {
    "urls": [],
    "summaries": []
  },
  "python-colcon-cmake": {
    "urls": [],
    "summaries": []
  },
  "python-colcon-core": {
    "urls": [],
    "summaries": []
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-commoncode": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325197"
    ],
    "summaries": [
      "python-commoncode fails to build with Python 3.14: tarfile.SpecialFileError: '6-FIFOTYPE' is a special file"
    ]
  },
  "python-compal": {
    "urls": [],
    "summaries": []
  },
  "python-conda-libmamba-solver": {
    "urls": [],
    "summaries": []
  },
  "python-confuse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
    ],
    "summaries": [
      "python-confuse fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-contourpy": {
    "urls": [],
    "summaries": []
  },
  "python-cornice": {
    "urls": [],
    "summaries": []
  },
  "python-cotyledon": {
    "urls": [],
    "summaries": []
  },
  "python-cradox": {
    "urls": [],
    "summaries": []
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-cssselect": {
    "urls": [],
    "summaries": []
  },
  "python-cvxopt": {
    "urls": [],
    "summaries": []
  },
  "python-cwcwidth": {
    "urls": [],
    "summaries": []
  },
  "python-cysignals": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325457"
    ],
    "summaries": [
      "python-cysignals fails to build with Python 3.14: Doctest src/cysignals/pselect.pyx terminated. Timeout limit exceeded (>2400s)"
    ]
  },
  "python-daikin": {
    "urls": [],
    "summaries": []
  },
  "python-daiquiri": {
    "urls": [],
    "summaries": []
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-dateparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336931"
    ],
    "summaries": [
      "python-dateparser: FTBFS in Fedora Rawhide: AssertionError in TestTranslateSearch.test_relative_base_setting_2_en"
    ]
  },
  "python-dateutil": {
    "urls": [],
    "summaries": []
  },
  "python-dbfread": {
    "urls": [],
    "summaries": []
  },
  "python-defcon": {
    "urls": [],
    "summaries": []
  },
  "python-dict-sorted": {
    "urls": [],
    "summaries": []
  },
  "python-dictdiffer": {
    "urls": [],
    "summaries": []
  },
  "python-diff-cover": {
    "urls": [],
    "summaries": []
  },
  "python-dill": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323157"
    ],
    "summaries": [
      "python-dill fails to build with Python 3.14: TypeError: _Pickler._batch_setitems() missing 1 required positional argument: 'obj'"
    ]
  },
  "python-django-allauth": {
    "urls": [],
    "summaries": []
  },
  "python-django-angular": {
    "urls": [],
    "summaries": []
  },
  "python-django-contrib-comments": {
    "urls": [],
    "summaries": []
  },
  "python-django-debreach": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328003"
    ],
    "summaries": [
      "python-django-debreach fails to build with Python 3.14: AttributeError: 'super' object has no attribute 'dicts' and no __dict__ for setting new attributes"
    ]
  },
  "python-django-filter": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336944"
    ],
    "summaries": [
      "python-django-filter fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "python-django-mailman3": {
    "urls": [],
    "summaries": []
  },
  "python-djangoql": {
    "urls": [],
    "summaries": []
  },
  "python-doit": {
    "urls": [],
    "summaries": []
  },
  "python-eccodes": {
    "urls": [],
    "summaries": []
  },
  "python-ephem": {
    "urls": [],
    "summaries": []
  },
  "python-epub": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319654"
    ],
    "summaries": [
      "python-epub fails to build with setuptools 74+"
    ]
  },
  "python-et_xmlfile": {
    "urls": [],
    "summaries": []
  },
  "python-etcd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
    ],
    "summaries": [
      "python-etcd fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestWatch.test_watch_indexed_generator.<locals>.watch_value at 0x7f0d39f71dd0>"
    ]
  },
  "python-ethtool": {
    "urls": [],
    "summaries": []
  },
  "python-events": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319655"
    ],
    "summaries": [
      "python-events fails to build with setuptools 74+"
    ]
  },
  "python-fastbencode": {
    "urls": [],
    "summaries": []
  },
  "python-fedora": {
    "urls": [],
    "summaries": []
  },
  "python-feedparser": {
    "urls": [],
    "summaries": []
  },
  "python-fields": {
    "urls": [],
    "summaries": []
  },
  "python-flask": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327965"
    ],
    "summaries": [
      "python-flask fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-flask-httpauth": {
    "urls": [],
    "summaries": []
  },
  "python-flask-login": {
    "urls": [],
    "summaries": []
  },
  "python-flask-oidc": {
    "urls": [],
    "summaries": []
  },
  "python-flask-paranoid": {
    "urls": [],
    "summaries": []
  },
  "python-flask-principal": {
    "urls": [],
    "summaries": []
  },
  "python-fontconfig": {
    "urls": [],
    "summaries": []
  },
  "python-freecell_solver": {
    "urls": [],
    "summaries": []
  },
  "python-fs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336951"
    ],
    "summaries": [
      "python-fs fails to build with Python 3.14: AssertionError: 'osfs://///tmp/tmppauy69swfstestosfs/foo' != 'osfs:///tmp/tmppauy69swfstestosfs/foo'"
    ]
  },
  "python-fsleyes-widgets": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336911"
    ],
    "summaries": [
      "python-fsleyes-widgets fails to build with Python 3.14: AssertionError: assert 'file:/home/b...htmlfile.html' == 'file:///home...htmlfile.html'"
    ]
  },
  "python-funcsigs": {
    "urls": [],
    "summaries": []
  },
  "python-futurist": {
    "urls": [],
    "summaries": []
  },
  "python-gbinder": {
    "urls": [],
    "summaries": []
  },
  "python-genty": {
    "urls": [],
    "summaries": []
  },
  "python-gevent": {
    "urls": [],
    "summaries": []
  },
  "python-giacpy": {
    "urls": [],
    "summaries": []
  },
  "python-gilt": {
    "urls": [],
    "summaries": []
  },
  "python-gios": {
    "urls": [],
    "summaries": []
  },
  "python-git-revise": {
    "urls": [],
    "summaries": []
  },
  "python-glyphsLib": {
    "urls": [],
    "summaries": []
  },
  "python-gphoto2": {
    "urls": [],
    "summaries": []
  },
  "python-graph-tool": {
    "urls": [],
    "summaries": []
  },
  "python-gssapi": {
    "urls": [],
    "summaries": []
  },
  "python-h5netcdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325222"
    ],
    "summaries": [
      "python-h5netcdf fails to build with Python 3.14: test_no_circular_references: AssertionError"
    ]
  },
  "python-hamcrest": {
    "urls": [],
    "summaries": []
  },
  "python-hidapi": {
    "urls": [],
    "summaries": []
  },
  "python-hl7": {
    "urls": [],
    "summaries": []
  },
  "python-html-text": {
    "urls": [],
    "summaries": []
  },
  "python-html5-parser": {
    "urls": [],
    "summaries": []
  },
  "python-httpretty": {
    "urls": [],
    "summaries": []
  },
  "python-httptools": {
    "urls": [],
    "summaries": []
  },
  "python-icalendar": {
    "urls": [],
    "summaries": []
  },
  "python-img2pdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328707"
    ],
    "summaries": [
      "python-img2pdf fails to build in rawhide: 48 AssertionErrors"
    ]
  },
  "python-iniparse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
    ],
    "summaries": [
      "python-iniparse fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestIni.test_queue.<locals>.getxy at 0x7f86659a7740>"
    ]
  },
  "python-inject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
    ],
    "summaries": [
      "python-inject fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-inkex": {
    "urls": [],
    "summaries": []
  },
  "python-interrogate": {
    "urls": [],
    "summaries": []
  },
  "python-ipyparallel": {
    "urls": [],
    "summaries": []
  },
  "python-irc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
    ],
    "summaries": [
      "python-irc fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-jack-client": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319666"
    ],
    "summaries": [
      "python-jack-client fails to build with setuptools 74+"
    ]
  },
  "python-jaraco-text": {
    "urls": [],
    "summaries": []
  },
  "python-jeepney": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327982"
    ],
    "summaries": [
      "python-jeepney fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-jinja2": {
    "urls": [],
    "summaries": []
  },
  "python-joblib": {
    "urls": [],
    "summaries": []
  },
  "python-josepy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323171"
    ],
    "summaries": [
      "python-josepy fails to build with Python 3.14: 6x ValueError: Field `alg` in JSONObject `Header` has no type annotation."
    ]
  },
  "python-jsonpath-rw-ext": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-c-kernel": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-client": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-kernel-singular": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-polymake": {
    "urls": [],
    "summaries": []
  },
  "python-kadmin": {
    "urls": [],
    "summaries": []
  },
  "python-kazoo": {
    "urls": [],
    "summaries": []
  },
  "python-keystoneauth1": {
    "urls": [],
    "summaries": []
  },
  "python-kmod": {
    "urls": [],
    "summaries": []
  },
  "python-libcst": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328019"
    ],
    "summaries": [
      "python-libcst fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-libdiscid": {
    "urls": [],
    "summaries": []
  },
  "python-libnacl": {
    "urls": [],
    "summaries": []
  },
  "python-listparser": {
    "urls": [],
    "summaries": []
  },
  "python-llfuse": {
    "urls": [],
    "summaries": []
  },
  "python-lockfile": {
    "urls": [],
    "summaries": []
  },
  "python-lz4": {
    "urls": [],
    "summaries": []
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-mako": {
    "urls": [],
    "summaries": []
  },
  "python-manuel": {
    "urls": [],
    "summaries": []
  },
  "python-mapbox-earcut": {
    "urls": [],
    "summaries": []
  },
  "python-markups": {
    "urls": [],
    "summaries": []
  },
  "python-matplotlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328713"
    ],
    "summaries": [
      "python-matplotlib fails to build with Python 3.14: RecursionError: maximum recursion depth exceeded"
    ]
  },
  "python-mccabe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328016"
    ],
    "summaries": [
      "python-mccabe fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-mechanicalsoup": {
    "urls": [],
    "summaries": []
  },
  "python-mercantile": {
    "urls": [],
    "summaries": []
  },
  "python-messaging": {
    "urls": [],
    "summaries": []
  },
  "python-micawber": {
    "urls": [],
    "summaries": []
  },
  "python-mido": {
    "urls": [],
    "summaries": []
  },
  "python-mistune": {
    "urls": [],
    "summaries": []
  },
  "python-moddb": {
    "urls": [],
    "summaries": []
  },
  "python-mrcrowbar": {
    "urls": [],
    "summaries": []
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-msgpack": {
    "urls": [],
    "summaries": []
  },
  "python-msgspec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325169"
    ],
    "summaries": [
      "python-msgspec fails to build with Python 3.14: error: \u2018_Py_IMMORTAL_REFCNT\u2019 undeclared here"
    ]
  },
  "python-multidict": {
    "urls": [],
    "summaries": []
  },
  "python-murmurhash": {
    "urls": [],
    "summaries": []
  },
  "python-mutagen": {
    "urls": [],
    "summaries": []
  },
  "python-mysqlclient": {
    "urls": [],
    "summaries": []
  },
  "python-ndindex": {
    "urls": [],
    "summaries": []
  },
  "python-nose": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323163"
    ],
    "summaries": [
      "python-nose fails to build with Python 3.14: multiple AssertionErrors related to timeouts in test outputs"
    ]
  },
  "python-notify2": {
    "urls": [],
    "summaries": []
  },
  "python-numpydoc": {
    "urls": [],
    "summaries": []
  },
  "python-ofxparse": {
    "urls": [],
    "summaries": []
  },
  "python-openshift": {
    "urls": [],
    "summaries": []
  },
  "python-openstackdocstheme": {
    "urls": [],
    "summaries": []
  },
  "python-opnsense": {
    "urls": [],
    "summaries": []
  },
  "python-os-service-types": {
    "urls": [],
    "summaries": []
  },
  "python-os-testr": {
    "urls": [],
    "summaries": []
  },
  "python-oscrypto": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-concurrency": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-i18n": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-serialization": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-utils": {
    "urls": [],
    "summaries": []
  },
  "python-oslotest": {
    "urls": [],
    "summaries": []
  },
  "python-osrf-pycommon": {
    "urls": [],
    "summaries": []
  },
  "python-overpy": {
    "urls": [],
    "summaries": []
  },
  "python-pandas": {
    "urls": [],
    "summaries": []
  },
  "python-paramiko": {
    "urls": [],
    "summaries": []
  },
  "python-parsel": {
    "urls": [],
    "summaries": []
  },
  "python-pathtools": {
    "urls": [],
    "summaries": []
  },
  "python-periodictable": {
    "urls": [],
    "summaries": []
  },
  "python-pexpect": {
    "urls": [],
    "summaries": []
  },
  "python-photutils": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336893"
    ],
    "summaries": [
      "python-photutils: FTBFS in Fedora Rawhide: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments."
    ]
  },
  "python-pip": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335909"
    ],
    "summaries": [
      "python-pip fails to build with Python 3.14: AssertionError: assert 'file:/tmp/file' == 'file:///tmp/file'"
    ]
  },
  "python-plaster": {
    "urls": [],
    "summaries": []
  },
  "python-psycogreen": {
    "urls": [],
    "summaries": []
  },
  "python-psycopg2": {
    "urls": [],
    "summaries": []
  },
  "python-psycopg3": {
    "urls": [],
    "summaries": []
  },
  "python-pulp-glue": {
    "urls": [],
    "summaries": []
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-py3nvml": {
    "urls": [],
    "summaries": []
  },
  "python-pyarlo": {
    "urls": [],
    "summaries": []
  },
  "python-pyasn1": {
    "urls": [],
    "summaries": []
  },
  "python-pybtex": {
    "urls": [],
    "summaries": []
  },
  "python-pybtex-docutils": {
    "urls": [],
    "summaries": []
  },
  "python-pycares": {
    "urls": [],
    "summaries": []
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pydantic-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
    ],
    "summaries": [
      "python-pydantic-core fails to build with Python 3.14: AssertionError: Regex pattern did not match. + AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pyfim": {
    "urls": [],
    "summaries": []
  },
  "python-pyghmi": {
    "urls": [],
    "summaries": []
  },
  "python-pygit2": {
    "urls": [],
    "summaries": []
  },
  "python-pygmtools": {
    "urls": [],
    "summaries": []
  },
  "python-pyliblo3": {
    "urls": [],
    "summaries": []
  },
  "python-pymacaroons-pynacl": {
    "urls": [],
    "summaries": []
  },
  "python-pymdown-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336948"
    ],
    "summaries": [
      "python-pymdown-extensions fails to build with Python 3.14: TestAbsolute.test_relative_path and TestAbsoluteFileScheme.test_relative_path AssertionErrors"
    ]
  },
  "python-pymeeus": {
    "urls": [],
    "summaries": []
  },
  "python-pymilter": {
    "urls": [],
    "summaries": []
  },
  "python-pymongo": {
    "urls": [],
    "summaries": []
  },
  "python-pyopencl": {
    "urls": [],
    "summaries": []
  },
  "python-pyopengl": {
    "urls": [],
    "summaries": []
  },
  "python-pyperclip": {
    "urls": [],
    "summaries": []
  },
  "python-pyqt-feedback-flow": {
    "urls": [],
    "summaries": []
  },
  "python-pyqtgraph": {
    "urls": [],
    "summaries": []
  },
  "python-pyquery": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid-mako": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid-tm": {
    "urls": [],
    "summaries": []
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pysqueezebox": {
    "urls": [],
    "summaries": []
  },
  "python-pystemd": {
    "urls": [],
    "summaries": []
  },
  "python-pystray": {
    "urls": [],
    "summaries": []
  },
  "python-pytaglib": {
    "urls": [],
    "summaries": []
  },
  "python-pyte": {
    "urls": [],
    "summaries": []
  },
  "python-pytesseract": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-aiohttp": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-asyncio": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-django": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-httpserver": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-ordering": {
    "urls": [],
    "summaries": []
  },
  "python-pytz-deprecation-shim": {
    "urls": [],
    "summaries": []
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-pyvlx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
    ],
    "summaries": [
      "python-pyvlx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pywt": {
    "urls": [],
    "summaries": []
  },
  "python-qpageview": {
    "urls": [],
    "summaries": []
  },
  "python-qutepart": {
    "urls": [],
    "summaries": []
  },
  "python-rdflib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336891"
    ],
    "summaries": [
      "python-rdflib fails to build with Python 3.14: \"TypeError: '<' not supported between instances of 'Literal' and 'Literal'\""
    ]
  },
  "python-reactivex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
    ],
    "summaries": [
      "python-reactivex fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-redis": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326927"
    ],
    "summaries": [
      "python-redis fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_redis_client.<locals>.target at 0x7fd5f829efb0>"
    ]
  },
  "python-reflink": {
    "urls": [],
    "summaries": []
  },
  "python-relatorio": {
    "urls": [],
    "summaries": []
  },
  "python-remoto": {
    "urls": [],
    "summaries": []
  },
  "python-rencode": {
    "urls": [],
    "summaries": []
  },
  "python-renderspec": {
    "urls": [],
    "summaries": []
  },
  "python-repomd": {
    "urls": [],
    "summaries": []
  },
  "python-reportlab": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331341"
    ],
    "summaries": [
      "python-reportlab fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-requests": {
    "urls": [],
    "summaries": []
  },
  "python-requests-toolbelt": {
    "urls": [],
    "summaries": []
  },
  "python-rich": {
    "urls": [],
    "summaries": []
  },
  "python-rosdep": {
    "urls": [],
    "summaries": []
  },
  "python-rosdistro": {
    "urls": [],
    "summaries": []
  },
  "python-rospkg": {
    "urls": [],
    "summaries": []
  },
  "python-routes": {
    "urls": [],
    "summaries": []
  },
  "python-rpmfluff": {
    "urls": [],
    "summaries": []
  },
  "python-rq": {
    "urls": [],
    "summaries": []
  },
  "python-rsd-lib": {
    "urls": [],
    "summaries": []
  },
  "python-rsdclient": {
    "urls": [],
    "summaries": []
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-s3transfer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326933"
    ],
    "summaries": [
      "python-s3transfer fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <class 'tests.unit.test_compat.TestBaseManager.create_pid_manager.<locals>.PIDManager'>"
    ]
  },
  "python-sane": {
    "urls": [],
    "summaries": []
  },
  "python-scantree": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328021"
    ],
    "summaries": [
      "python-scantree fails to build with Python 3.14: AssertionError: assert 1.2218716144561768 < (2.0 / 2)"
    ]
  },
  "python-seaborn": {
    "urls": [],
    "summaries": []
  },
  "python-sep": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336965"
    ],
    "summaries": [
      "python-sep: FTBFS in Fedora Rawhide: Error compiling Cython file: 'int_t' is not a type identifier"
    ]
  },
  "python-serpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319716"
    ],
    "summaries": [
      "python-serpy fails to build with setuptools 74+"
    ]
  },
  "python-setuptools-rust": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336950"
    ],
    "summaries": [
      "python-setuptools-rust fails to build with Python 3.14: /builddir/build/BUILD/python-setuptools-rust-1.10.2-build/setuptools_rust-1.10.2/examples/hello-world/venv/bin/python: No module named pytest"
    ]
  },
  "python-shodan": {
    "urls": [],
    "summaries": []
  },
  "python-simplegeneric": {
    "urls": [],
    "summaries": []
  },
  "python-simplevisor": {
    "urls": [],
    "summaries": []
  },
  "python-singledispatch": {
    "urls": [],
    "summaries": []
  },
  "python-slixmpp": {
    "urls": [],
    "summaries": []
  },
  "python-smartypants": {
    "urls": [],
    "summaries": []
  },
  "python-snuggs": {
    "urls": [],
    "summaries": []
  },
  "python-social-auth-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328010"
    ],
    "summaries": [
      "python-social-auth-core fails to build with Python 3.14: 'SSLContext' object has no attribute 'close'"
    ]
  },
  "python-sphinx-bootstrap-theme": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-documatt-theme": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-gallery": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-intl": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-kr-theme": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-last-updated-by-git": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-markdown-tables": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-math-dollar": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-multiversion": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-notfound-page": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-press-theme": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-pytest": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-tabs": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx-theme-py3doc-enhanced": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx_lv2_theme": {
    "urls": [],
    "summaries": []
  },
  "python-sphinx_selective_exclude": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-asyncio": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-autoprogram": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-blockdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-github-alt": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-httpdomain": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-jquery": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-log-cabinet": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-pecanwsme": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-phpdomain": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-programoutput": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-seqdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-spelling": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-trio": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxygen": {
    "urls": [],
    "summaries": []
  },
  "python-sphobjinv": {
    "urls": [],
    "summaries": []
  },
  "python-spnego": {
    "urls": [],
    "summaries": []
  },
  "python-spur": {
    "urls": [],
    "summaries": []
  },
  "python-sql": {
    "urls": [],
    "summaries": []
  },
  "python-sqlacodegen": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy-filters": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy1.3": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy1.4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
    ],
    "summaries": [
      "python-sqlalchemy1.4 fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-sqlglot": {
    "urls": [],
    "summaries": []
  },
  "python-sqlparse": {
    "urls": [],
    "summaries": []
  },
  "python-ssdeep": {
    "urls": [],
    "summaries": []
  },
  "python-ssdp": {
    "urls": [],
    "summaries": []
  },
  "python-sseclient": {
    "urls": [],
    "summaries": []
  },
  "python-sseclient-py": {
    "urls": [],
    "summaries": []
  },
  "python-ssh-python": {
    "urls": [],
    "summaries": []
  },
  "python-sshpubkeys": {
    "urls": [],
    "summaries": []
  },
  "python-stackprinter": {
    "urls": [],
    "summaries": []
  },
  "python-statsmodels": {
    "urls": [],
    "summaries": []
  },
  "python-stdiomask": {
    "urls": [],
    "summaries": []
  },
  "python-stdlibs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336938"
    ],
    "summaries": [
      "python-stdlibs fails to build with Python 3.14: test_all_my_modules_are_there: AssertionError: Items in the second set but not the first: '_apple_support'"
    ]
  },
  "python-stdnum": {
    "urls": [],
    "summaries": []
  },
  "python-stem": {
    "urls": [],
    "summaries": []
  },
  "python-stestr": {
    "urls": [],
    "summaries": []
  },
  "python-stevedore": {
    "urls": [],
    "summaries": []
  },
  "python-stone": {
    "urls": [],
    "summaries": []
  },
  "python-stopit": {
    "urls": [],
    "summaries": []
  },
  "python-straight-plugin": {
    "urls": [],
    "summaries": []
  },
  "python-strict-rfc3339": {
    "urls": [],
    "summaries": []
  },
  "python-string_utils": {
    "urls": [],
    "summaries": []
  },
  "python-stuf": {
    "urls": [],
    "summaries": []
  },
  "python-subarulink": {
    "urls": [],
    "summaries": []
  },
  "python-succulent": {
    "urls": [],
    "summaries": []
  },
  "python-suds": {
    "urls": [],
    "summaries": []
  },
  "python-sushy": {
    "urls": [],
    "summaries": []
  },
  "python-svg": {
    "urls": [],
    "summaries": []
  },
  "python-svg2tikz": {
    "urls": [],
    "summaries": []
  },
  "python-svgwrite": {
    "urls": [],
    "summaries": []
  },
  "python-sybil": {
    "urls": [],
    "summaries": []
  },
  "python-syrupy": {
    "urls": [],
    "summaries": []
  },
  "python-syslog-rfc5424-formatter": {
    "urls": [],
    "summaries": []
  },
  "python-systemd": {
    "urls": [],
    "summaries": []
  },
  "python-sysv_ipc": {
    "urls": [],
    "summaries": []
  },
  "python-tablib": {
    "urls": [],
    "summaries": []
  },
  "python-tasmotadevicecontroller": {
    "urls": [],
    "summaries": []
  },
  "python-tbtrim": {
    "urls": [],
    "summaries": []
  },
  "python-tcolorpy": {
    "urls": [],
    "summaries": []
  },
  "python-tcxparser": {
    "urls": [],
    "summaries": []
  },
  "python-tcxreader": {
    "urls": [],
    "summaries": []
  },
  "python-teamcity-messages": {
    "urls": [],
    "summaries": []
  },
  "python-tempdir": {
    "urls": [],
    "summaries": []
  },
  "python-tempita": {
    "urls": [],
    "summaries": []
  },
  "python-templated-dictionary": {
    "urls": [],
    "summaries": []
  },
  "python-tempora": {
    "urls": [],
    "summaries": []
  },
  "python-tenacity": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
    ],
    "summaries": [
      "python-tenacity fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-terminado": {
    "urls": [],
    "summaries": []
  },
  "python-terminaltables": {
    "urls": [],
    "summaries": []
  },
  "python-teslajsonpy": {
    "urls": [],
    "summaries": []
  },
  "python-testrepository": {
    "urls": [],
    "summaries": []
  },
  "python-testresources": {
    "urls": [],
    "summaries": []
  },
  "python-text-unidecode": {
    "urls": [],
    "summaries": []
  },
  "python-textfsm": {
    "urls": [],
    "summaries": []
  },
  "python-textile": {
    "urls": [],
    "summaries": []
  },
  "python-textparser": {
    "urls": [],
    "summaries": []
  },
  "python-textwrap3": {
    "urls": [],
    "summaries": []
  },
  "python-tgscheduler": {
    "urls": [],
    "summaries": []
  },
  "python-tidy": {
    "urls": [],
    "summaries": []
  },
  "python-timelib": {
    "urls": [],
    "summaries": []
  },
  "python-tinycss2": {
    "urls": [],
    "summaries": []
  },
  "python-tinygrad": {
    "urls": [],
    "summaries": []
  },
  "python-tinyhtml5": {
    "urls": [],
    "summaries": []
  },
  "python-tkrzw": {
    "urls": [],
    "summaries": []
  },
  "python-tld": {
    "urls": [],
    "summaries": []
  },
  "python-tldextract": {
    "urls": [],
    "summaries": []
  },
  "python-token-bucket": {
    "urls": [],
    "summaries": []
  },
  "python-toml-adapt": {
    "urls": [],
    "summaries": []
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-tornado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
    ],
    "summaries": [
      "python-tornado fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-tpm2-pytss": {
    "urls": [],
    "summaries": []
  },
  "python-transaction": {
    "urls": [],
    "summaries": []
  },
  "python-translitcodec": {
    "urls": [],
    "summaries": []
  },
  "python-tree-format": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319731"
    ],
    "summaries": [
      "python-tree-format fails to build with setuptools 74+"
    ]
  },
  "python-trezor": {
    "urls": [],
    "summaries": []
  },
  "python-trololio": {
    "urls": [],
    "summaries": []
  },
  "python-trove-classifiers": {
    "urls": [],
    "summaries": []
  },
  "python-tvb-data": {
    "urls": [],
    "summaries": []
  },
  "python-tw2-core": {
    "urls": [],
    "summaries": []
  },
  "python-tw2-forms": {
    "urls": [],
    "summaries": []
  },
  "python-twilio": {
    "urls": [],
    "summaries": []
  },
  "python-twisted": {
    "urls": [],
    "summaries": []
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typedecorator": {
    "urls": [],
    "summaries": []
  },
  "python-typeguard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328015"
    ],
    "summaries": [
      "python-typeguard fails to build with Python 3.14: typeguard.TypeCheckError: argument \"x\" (class dummymodule.DummyClass) is not a subclass of dummymodule.DummyClass && AssertionError: Regex pattern did not match."
    ]
  },
  "python-typepy": {
    "urls": [],
    "summaries": []
  },
  "python-types-decorator": {
    "urls": [],
    "summaries": []
  },
  "python-types-mock": {
    "urls": [],
    "summaries": []
  },
  "python-typing-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336937"
    ],
    "summaries": [
      "python-typing-extensions fails to build with Python 3.14: test_drop_in_for_typing: AssertionError: self.assertGreaterEqual(te_all, t_all - exceptions)"
    ]
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-typogrify": {
    "urls": [],
    "summaries": []
  },
  "python-ua-parser": {
    "urls": [],
    "summaries": []
  },
  "python-uc-micro-py": {
    "urls": [],
    "summaries": []
  },
  "python-ufl": {
    "urls": [],
    "summaries": []
  },
  "python-uhashring": {
    "urls": [],
    "summaries": []
  },
  "python-uinput": {
    "urls": [],
    "summaries": []
  },
  "python-ujson": {
    "urls": [],
    "summaries": []
  },
  "python-ukkonen": {
    "urls": [],
    "summaries": []
  },
  "python-unicodedata2": {
    "urls": [],
    "summaries": []
  },
  "python-unidecode": {
    "urls": [],
    "summaries": []
  },
  "python-unidiff": {
    "urls": [],
    "summaries": []
  },
  "python-unipath": {
    "urls": [],
    "summaries": []
  },
  "python-unix-ar": {
    "urls": [],
    "summaries": []
  },
  "python-unpaddedbase64": {
    "urls": [],
    "summaries": []
  },
  "python-untangle": {
    "urls": [],
    "summaries": []
  },
  "python-upnpy": {
    "urls": [],
    "summaries": []
  },
  "python-uptime": {
    "urls": [],
    "summaries": []
  },
  "python-uri-template": {
    "urls": [],
    "summaries": []
  },
  "python-uritemplate": {
    "urls": [],
    "summaries": []
  },
  "python-url-normalize": {
    "urls": [],
    "summaries": []
  },
  "python-urlgrabber": {
    "urls": [],
    "summaries": []
  },
  "python-urllib-gssapi": {
    "urls": [],
    "summaries": []
  },
  "python-urwid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
    ],
    "summaries": [
      "python-urwid fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-urwid-readline": {
    "urls": [],
    "summaries": []
  },
  "python-urwidtrees": {
    "urls": [],
    "summaries": []
  },
  "python-user-agents": {
    "urls": [],
    "summaries": []
  },
  "python-utmp": {
    "urls": [],
    "summaries": []
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-validators": {
    "urls": [],
    "summaries": []
  },
  "python-valkey": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326934"
    ],
    "summaries": [
      "python-valkey fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f7d711b5dd0>"
    ]
  },
  "python-varlink": {
    "urls": [],
    "summaries": []
  },
  "python-vatnumber": {
    "urls": [],
    "summaries": []
  },
  "python-vcstool": {
    "urls": [],
    "summaries": []
  },
  "python-velbus": {
    "urls": [],
    "summaries": []
  },
  "python-verboselogs": {
    "urls": [],
    "summaries": []
  },
  "python-versioneer": {
    "urls": [],
    "summaries": []
  },
  "python-virtualbmc": {
    "urls": [],
    "summaries": []
  },
  "python-virtualenv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336936"
    ],
    "summaries": [
      "python-virtualenv fails to build with Python 3.14: AssertionError: common, \"\\n\".join(difflib.unified_diff(list_to_str(sys_path), list_to_str(system_sys_path)))"
    ]
  },
  "python-virtualenv-clone": {
    "urls": [],
    "summaries": []
  },
  "python-virtualenvwrapper": {
    "urls": [],
    "summaries": []
  },
  "python-visitor": {
    "urls": [],
    "summaries": []
  },
  "python-visvis": {
    "urls": [],
    "summaries": []
  },
  "python-vobject": {
    "urls": [],
    "summaries": []
  },
  "python-volatile": {
    "urls": [],
    "summaries": []
  },
  "python-volkszaehler": {
    "urls": [],
    "summaries": []
  },
  "python-voluptuous": {
    "urls": [],
    "summaries": []
  },
  "python-voluptuous-serialize": {
    "urls": [],
    "summaries": []
  },
  "python-vsts-cd-manager": {
    "urls": [],
    "summaries": []
  },
  "python-vsure": {
    "urls": [],
    "summaries": []
  },
  "python-w3lib": {
    "urls": [],
    "summaries": []
  },
  "python-walkdir": {
    "urls": [],
    "summaries": []
  },
  "python-waqiasync": {
    "urls": [],
    "summaries": []
  },
  "python-warlock": {
    "urls": [],
    "summaries": []
  },
  "python-watchfiles": {
    "urls": [],
    "summaries": []
  },
  "python-watchgod": {
    "urls": [],
    "summaries": []
  },
  "python-waterfurnace": {
    "urls": [],
    "summaries": []
  },
  "python-wcag-contrast-ratio": {
    "urls": [],
    "summaries": []
  },
  "python-wcmatch": {
    "urls": [],
    "summaries": []
  },
  "python-webencodings": {
    "urls": [],
    "summaries": []
  },
  "python-webob": {
    "urls": [],
    "summaries": []
  },
  "python-webscrapbook": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326915"
    ],
    "summaries": [
      "python-webscrapbook fails to build with Python 3.14: 60x AssertionError in the test suite"
    ]
  },
  "python-websocket-client": {
    "urls": [],
    "summaries": []
  },
  "python-websockify": {
    "urls": [],
    "summaries": []
  },
  "python-webtest": {
    "urls": [],
    "summaries": []
  },
  "python-webthing": {
    "urls": [],
    "summaries": []
  },
  "python-webthing-ws": {
    "urls": [],
    "summaries": []
  },
  "python-whichcraft": {
    "urls": [],
    "summaries": []
  },
  "python-whisper": {
    "urls": [],
    "summaries": []
  },
  "python-whitenoise": {
    "urls": [],
    "summaries": []
  },
  "python-whois": {
    "urls": [],
    "summaries": []
  },
  "python-whoosh": {
    "urls": [],
    "summaries": []
  },
  "python-wiffi": {
    "urls": [],
    "summaries": []
  },
  "python-wikipedia": {
    "urls": [],
    "summaries": []
  },
  "python-wikitcms": {
    "urls": [],
    "summaries": []
  },
  "python-winacl": {
    "urls": [],
    "summaries": []
  },
  "python-winrm": {
    "urls": [],
    "summaries": []
  },
  "python-winsspi": {
    "urls": [],
    "summaries": []
  },
  "python-wled": {
    "urls": [],
    "summaries": []
  },
  "python-wloc": {
    "urls": [],
    "summaries": []
  },
  "python-wordcloud": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335908"
    ],
    "summaries": [
      "python-wordcloud fails to build with Python 3.14: test_cli_as_executable: AssertionError: assert expected_output in out if ret_code == 0 else err"
    ]
  },
  "python-wsgi_intercept": {
    "urls": [],
    "summaries": []
  },
  "python-wtforms": {
    "urls": [],
    "summaries": []
  },
  "python-www-authenticate": {
    "urls": [],
    "summaries": []
  },
  "python-wxpython4": {
    "urls": [],
    "summaries": []
  },
  "python-x2go": {
    "urls": [],
    "summaries": []
  },
  "python-x3dh": {
    "urls": [],
    "summaries": []
  },
  "python-xapian-haystack": {
    "urls": [],
    "summaries": []
  },
  "python-xboxapi": {
    "urls": [],
    "summaries": []
  },
  "python-xdot": {
    "urls": [],
    "summaries": []
  },
  "python-xeddsa": {
    "urls": [],
    "summaries": []
  },
  "python-xiaomi-gateway": {
    "urls": [],
    "summaries": []
  },
  "python-xkbcommon": {
    "urls": [],
    "summaries": []
  },
  "python-xlib": {
    "urls": [],
    "summaries": []
  },
  "python-xlrd": {
    "urls": [],
    "summaries": []
  },
  "python-xlrd2": {
    "urls": [],
    "summaries": []
  },
  "python-xlsxwriter": {
    "urls": [],
    "summaries": []
  },
  "python-xlwt": {
    "urls": [],
    "summaries": []
  },
  "python-xml2rfc": {
    "urls": [],
    "summaries": []
  },
  "python-xmlsec": {
    "urls": [],
    "summaries": []
  },
  "python-xmltodict": {
    "urls": [],
    "summaries": []
  },
  "python-xmltramp": {
    "urls": [],
    "summaries": []
  },
  "python-xpath-expressions": {
    "urls": [],
    "summaries": []
  },
  "python-xunitparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319738"
    ],
    "summaries": [
      "python-xunitparser fails to build with setuptools 74+"
    ]
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-yarl": {
    "urls": [],
    "summaries": []
  },
  "python-yaswfp": {
    "urls": [],
    "summaries": []
  },
  "python-yattag": {
    "urls": [],
    "summaries": []
  },
  "python-ytmusicapi": {
    "urls": [],
    "summaries": []
  },
  "python-yubico": {
    "urls": [],
    "summaries": []
  },
  "python-zake": {
    "urls": [],
    "summaries": []
  },
  "python-zc-customdoctests": {
    "urls": [],
    "summaries": []
  },
  "python-zc-lockfile": {
    "urls": [],
    "summaries": []
  },
  "python-zict": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328012"
    ],
    "summaries": [
      "python-zict fails to build with Python 3.14: test_stress_different_keys_threadsafe Timeout"
    ]
  },
  "python-zipstream": {
    "urls": [],
    "summaries": []
  },
  "python-zm": {
    "urls": [],
    "summaries": []
  },
  "python-zombie-imp": {
    "urls": [],
    "summaries": []
  },
  "python-zope-component": {
    "urls": [],
    "summaries": []
  },
  "python-zope-deprecation": {
    "urls": [],
    "summaries": []
  },
  "python-zope-hookable": {
    "urls": [],
    "summaries": []
  },
  "python-zope-sqlalchemy": {
    "urls": [],
    "summaries": []
  },
  "python-zope-testing": {
    "urls": [],
    "summaries": []
  },
  "python-zope-testrunner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335907"
    ],
    "summaries": [
      "python-zope-testrunner fails to build with Python 3.14: difference in the asserted content in testrunner-edge-cases.rst"
    ]
  },
  "python-zopfli": {
    "urls": [],
    "summaries": []
  },
  "python-zstandard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326925"
    ],
    "summaries": [
      "python-zstandard fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-zstarfile": {
    "urls": [],
    "summaries": []
  },
  "python-zstd": {
    "urls": [],
    "summaries": []
  },
  "python-zuul-sphinx": {
    "urls": [],
    "summaries": []
  },
  "python-zxcvbn": {
    "urls": [],
    "summaries": []
  },
  "python3-iep": {
    "urls": [],
    "summaries": []
  },
  "python3-lxc": {
    "urls": [],
    "summaries": []
  },
  "python3-mallard-ducktype": {
    "urls": [],
    "summaries": []
  },
  "python3-mypy": {
    "urls": [],
    "summaries": []
  },
  "python3-openid": {
    "urls": [],
    "summaries": []
  },
  "python3-poppler-qt5": {
    "urls": [],
    "summaries": []
  },
  "python3-postgresql": {
    "urls": [],
    "summaries": []
  },
  "python3-py3dns": {
    "urls": [],
    "summaries": []
  },
  "python3-saml": {
    "urls": [],
    "summaries": []
  },
  "python3-simpletal": {
    "urls": [],
    "summaries": []
  },
  "pytz": {
    "urls": [],
    "summaries": []
  },
  "pyusb": {
    "urls": [],
    "summaries": []
  },
  "pywbem": {
    "urls": [],
    "summaries": []
  },
  "pywebdav": {
    "urls": [],
    "summaries": []
  },
  "pyxattr": {
    "urls": [],
    "summaries": []
  },
  "pyxdg": {
    "urls": [],
    "summaries": []
  },
  "pyzor": {
    "urls": [],
    "summaries": []
  },
  "qgis": {
    "urls": [],
    "summaries": []
  },
  "qhexedit2": {
    "urls": [],
    "summaries": []
  },
  "qpid-proton": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327999"
    ],
    "summaries": [
      "qpid-proton fails to build with Python 3.14: error: File not found: /builddir/build/BUILD/qpid-proton-0.38.0-build/BUILDROOT/usr/share/proton/docs/api-py"
    ]
  },
  "qr-code-generator": {
    "urls": [],
    "summaries": []
  },
  "qscintilla": {
    "urls": [],
    "summaries": []
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "quearcode": {
    "urls": [],
    "summaries": []
  },
  "quisk": {
    "urls": [],
    "summaries": []
  },
  "rabbitvcs": {
    "urls": [],
    "summaries": []
  },
  "radicale": {
    "urls": [],
    "summaries": []
  },
  "ranger": {
    "urls": [],
    "summaries": []
  },
  "rapid-photo-downloader": {
    "urls": [],
    "summaries": []
  },
  "rb_libtorrent": {
    "urls": [],
    "summaries": []
  },
  "rdiff-backup": {
    "urls": [],
    "summaries": []
  },
  "realtime-tests": {
    "urls": [],
    "summaries": []
  },
  "recoll": {
    "urls": [],
    "summaries": []
  },
  "rednotebook": {
    "urls": [],
    "summaries": []
  },
  "redshift": {
    "urls": [],
    "summaries": []
  },
  "remmina": {
    "urls": [],
    "summaries": []
  },
  "renderdoc": {
    "urls": [],
    "summaries": []
  },
  "reprotest": {
    "urls": [],
    "summaries": []
  },
  "resalloc-ibm-cloud": {
    "urls": [],
    "summaries": []
  },
  "resalloc-openstack": {
    "urls": [],
    "summaries": []
  },
  "restview": {
    "urls": [],
    "summaries": []
  },
  "resultsdb_conventions": {
    "urls": [],
    "summaries": []
  },
  "retext": {
    "urls": [],
    "summaries": []
  },
  "retrace-server": {
    "urls": [],
    "summaries": []
  },
  "rhythmbox-ampache": {
    "urls": [],
    "summaries": []
  },
  "rig": {
    "urls": [],
    "summaries": []
  },
  "rmol": {
    "urls": [],
    "summaries": []
  },
  "roca-detect": {
    "urls": [],
    "summaries": []
  },
  "root": {
    "urls": [],
    "summaries": []
  },
  "rpkg-util": {
    "urls": [],
    "summaries": []
  },
  "rpl": {
    "urls": [],
    "summaries": []
  },
  "rpm": {
    "urls": [],
    "summaries": []
  },
  "rpm-head-signing": {
    "urls": [],
    "summaries": []
  },
  "rpmconf": {
    "urls": [],
    "summaries": []
  },
  "rpy": {
    "urls": [],
    "summaries": []
  },
  "rrdtool": {
    "urls": [],
    "summaries": []
  },
  "rss2email": {
    "urls": [],
    "summaries": []
  },
  "rst2txt": {
    "urls": [],
    "summaries": []
  },
  "rteval": {
    "urls": [],
    "summaries": []
  },
  "rtlsdr-scanner": {
    "urls": [],
    "summaries": []
  },
  "rubber": {
    "urls": [],
    "summaries": []
  },
  "satyr": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
    ],
    "summaries": [
      "satyr fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestDistances.test_distances_part_parallel.<locals>.do_test.<locals>.compute_part at 0x7f7f845f2560>"
    ]
  },
  "setools": {
    "urls": [],
    "summaries": []
  },
  "signon-glib": {
    "urls": [],
    "summaries": []
  },
  "spectrographic": {
    "urls": [],
    "summaries": []
  },
  "speech-dispatcher": {
    "urls": [],
    "summaries": []
  },
  "strongswan": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332864"
    ],
    "summaries": [
      "strongswan-5.9.14-5.fc42 FTBFS: strongswan-5.9.14/missing: line 81: aclocal-1.16: command not found"
    ]
  },
  "syncplay": {
    "urls": [],
    "summaries": []
  },
  "system-storage-manager": {
    "urls": [],
    "summaries": []
  },
  "systemtap": {
    "urls": [],
    "summaries": []
  },
  "tbb": {
    "urls": [],
    "summaries": []
  },
  "tcl-snack": {
    "urls": [],
    "summaries": []
  },
  "thrift": {
    "urls": [],
    "summaries": []
  },
  "trac": {
    "urls": [],
    "summaries": []
  },
  "trademgen": {
    "urls": [],
    "summaries": []
  },
  "trash-cli": {
    "urls": [],
    "summaries": []
  },
  "ufw": {
    "urls": [],
    "summaries": []
  },
  "uhd": {
    "urls": [],
    "summaries": []
  },
  "urh": {
    "urls": [],
    "summaries": []
  },
  "uwsgi": {
    "urls": [],
    "summaries": []
  },
  "vapoursynth": {
    "urls": [],
    "summaries": []
  },
  "variety": {
    "urls": [],
    "summaries": []
  },
  "veusz": {
    "urls": [],
    "summaries": []
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "vtk": {
    "urls": [],
    "summaries": []
  },
  "waf": {
    "urls": [],
    "summaries": []
  },
  "weasyprint": {
    "urls": [],
    "summaries": []
  },
  "wfuzz": {
    "urls": [],
    "summaries": []
  },
  "xapian-bindings": {
    "urls": [],
    "summaries": []
  },
  "xen": {
    "urls": [],
    "summaries": []
  },
  "xmms2": {
    "urls": [],
    "summaries": []
  },
  "xonsh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336895"
    ],
    "summaries": [
      "xonsh fails to build with Python 3.14: ValueError: action 'store_true' is not valid for positional arguments"
    ]
  },
  "xpra": {
    "urls": [],
    "summaries": []
  },
  "xrootd": {
    "urls": [],
    "summaries": []
  },
  "yamllint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336947"
    ],
    "summaries": [
      "yamllint fails to build with Python 3.14: ValueError('I/O operation on closed file')"
    ]
  }
}