{
  "adapt": {
    "urls": [],
    "summaries": []
  },
  "alot": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339881"
    ],
    "summaries": [
      "alot: FTBFS in Fedora rawhide/f42"
    ]
  },
  "ara": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331346"
    ],
    "summaries": [
      "ara fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "awscli2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336910"
    ],
    "summaries": [
      "awscli2 fails to build with Python 3.14: ValueError('badly formed help string'),  KeyError: 'PATH'"
    ]
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "bluechi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339937"
    ],
    "summaries": [
      "bluechi: FTBFS in Fedora rawhide/f42"
    ]
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "brltty": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339947"
    ],
    "summaries": [
      "brltty: FTBFS in Fedora rawhide/f42"
    ]
  },
  "ceph": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336913"
    ],
    "summaries": [
      "ceph fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "chirp": {
    "urls": [],
    "summaries": []
  },
  "cjdns": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339969"
    ],
    "summaries": [
      "cjdns: FTBFS in Fedora rawhide/f42"
    ]
  },
  "cockpit": {
    "urls": [],
    "summaries": []
  },
  "condor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339993"
    ],
    "summaries": [
      "condor: FTBFS in Fedora rawhide/f42"
    ]
  },
  "cryptlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340016"
    ],
    "summaries": [
      "cryptlib: FTBFS in Fedora rawhide/f42"
    ]
  },
  "debconf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340035"
    ],
    "summaries": [
      "debconf: FTBFS in Fedora rawhide/f42"
    ]
  },
  "dee": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340038"
    ],
    "summaries": [
      "dee: FTBFS in Fedora rawhide/f42"
    ]
  },
  "diceware": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340075"
    ],
    "summaries": [
      "diceware: FTBFS in Fedora rawhide/f42"
    ]
  },
  "did": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328006"
    ],
    "summaries": [
      "did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'"
    ]
  },
  "dionaea": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340077"
    ],
    "summaries": [
      "dionaea: FTBFS in Fedora rawhide/f42"
    ]
  },
  "dlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340079",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328014"
    ],
    "summaries": [
      "dlib: FTBFS in Fedora rawhide/f42",
      "dlib fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "dnfdragora": {
    "urls": [],
    "summaries": []
  },
  "dnsconfd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340084"
    ],
    "summaries": [
      "dnsconfd: FTBFS in Fedora rawhide/f42"
    ]
  },
  "elements-alexandria": {
    "urls": [],
    "summaries": []
  },
  "espresso": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340139"
    ],
    "summaries": [
      "espresso: FTBFS in Fedora rawhide/f42"
    ]
  },
  "fedora-business-cards": {
    "urls": [],
    "summaries": []
  },
  "fedscm-admin": {
    "urls": [],
    "summaries": []
  },
  "fonttools": {
    "urls": [],
    "summaries": []
  },
  "gdb": {
    "urls": [],
    "summaries": []
  },
  "gdl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340199"
    ],
    "summaries": [
      "gdl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "gnofract4d": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339539"
    ],
    "summaries": [
      "gnofract4d fails to build with Python 3.14: AssertionError: 'ct_sin6 = (0.841471,-0)' != 'ct_sin6 = (0.841471,0)'"
    ]
  },
  "gnuradio": {
    "urls": [],
    "summaries": []
  },
  "h5py": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339470"
    ],
    "summaries": [
      "h5py fails to build with Python 3.14: ResourceWarning: TestFileObj.test_TemporaryFile: Implicitly cleaning up <_TemporaryFileWrapper file=<_io.BufferedRandom name='/tmp/tmp8pqafmzv'>>"
    ]
  },
  "hplip": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340616"
    ],
    "summaries": [
      "hplip: FTBFS in Fedora rawhide/f42"
    ]
  },
  "ikiwiki": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340642"
    ],
    "summaries": [
      "ikiwiki: FTBFS in Fedora rawhide/f42"
    ]
  },
  "ioc-writer": {
    "urls": [],
    "summaries": []
  },
  "ipa-hcc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340655"
    ],
    "summaries": [
      "ipa-hcc: FTBFS in Fedora rawhide/f42"
    ]
  },
  "jc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331343"
    ],
    "summaries": [
      "jc fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "kernel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340285"
    ],
    "summaries": [
      "kernel: FTBFS in Fedora rawhide/f42"
    ]
  },
  "kicad": {
    "urls": [],
    "summaries": []
  },
  "kitty": {
    "urls": [],
    "summaries": []
  },
  "koji": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340700"
    ],
    "summaries": [
      "koji: FTBFS in Fedora rawhide/f42"
    ]
  },
  "lammps": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340706"
    ],
    "summaries": [
      "lammps: FTBFS in Fedora rawhide/f42"
    ]
  },
  "lasso": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340708"
    ],
    "summaries": [
      "lasso: FTBFS in Fedora rawhide/f42"
    ]
  },
  "lecm": {
    "urls": [],
    "summaries": []
  },
  "libarrow": {
    "urls": [],
    "summaries": []
  },
  "libgpiod": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340738"
    ],
    "summaries": [
      "libgpiod: FTBFS in Fedora rawhide/f42"
    ]
  },
  "libiio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340741"
    ],
    "summaries": [
      "libiio: FTBFS in Fedora rawhide/f42"
    ]
  },
  "libnvme": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325194"
    ],
    "summaries": [
      "libnvme fails to build with Python 3.14: /usr/include/python3.14/pyport.h:629:35: error: missing ')' after \"__has_attribute\""
    ]
  },
  "link-grammar": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340774"
    ],
    "summaries": [
      "link-grammar: FTBFS in Fedora rawhide/f42"
    ]
  },
  "linode-cli": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340775"
    ],
    "summaries": [
      "linode-cli: FTBFS in Fedora rawhide/f42"
    ]
  },
  "llvm": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340786",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336915"
    ],
    "summaries": [
      "llvm: FTBFS in Fedora rawhide/f42",
      "llvm fails to build with Python 3.14: tools/opt-viewer/suppress.test: AttributeError: type object 'Passed' has no attribute 'demangler_lock'"
    ]
  },
  "lorax": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340795"
    ],
    "summaries": [
      "lorax: FTBFS in Fedora rawhide/f42"
    ]
  },
  "mathgl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340819"
    ],
    "summaries": [
      "mathgl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "mlpack": {
    "urls": [],
    "summaries": []
  },
  "morphio": {
    "urls": [],
    "summaries": []
  },
  "needrestart": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340913"
    ],
    "summaries": [
      "needrestart: FTBFS in Fedora rawhide/f42"
    ]
  },
  "nextpnr": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340929"
    ],
    "summaries": [
      "nextpnr: FTBFS in Fedora rawhide/f42"
    ]
  },
  "nut": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340946"
    ],
    "summaries": [
      "nut: FTBFS in Fedora rawhide/f42"
    ]
  },
  "nvmetcli": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340947"
    ],
    "summaries": [
      "nvmetcli: FTBFS in Fedora rawhide/f42"
    ]
  },
  "nwchem": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340948"
    ],
    "summaries": [
      "nwchem: FTBFS in Fedora rawhide/f42"
    ]
  },
  "obs-studio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340952"
    ],
    "summaries": [
      "obs-studio: FTBFS in Fedora rawhide/f42"
    ]
  },
  "openbabel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339472"
    ],
    "summaries": [
      "openbabel fails to build with Python 3.14: test_align_4 and test_align_5 fail"
    ]
  },
  "opentrep": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340980"
    ],
    "summaries": [
      "opentrep: FTBFS in Fedora rawhide/f42"
    ]
  },
  "osh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340988"
    ],
    "summaries": [
      "osh: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pcs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341012"
    ],
    "summaries": [
      "pcs: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pdc-client": {
    "urls": [],
    "summaries": []
  },
  "plplot": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341081"
    ],
    "summaries": [
      "plplot: FTBFS in Fedora rawhide/f42"
    ]
  },
  "postgresql15": {
    "urls": [],
    "summaries": []
  },
  "postgresql16": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332981"
    ],
    "summaries": [
      "postgresql16-16.3-7.fc42 FTBFS: tests fail with tzdata-2024b"
    ]
  },
  "postgresql17": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332978",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327967"
    ],
    "summaries": [
      "postgresql17-17.0-1.fc42 FTBFS: RPM build errors: line 227: second Description",
      "postgresql17 fails to build with Python 3.14: jsonb_jsonpath fails: - \"12:34:56-07:00\" != + \"12:34:56-08:00\""
    ]
  },
  "powerline": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336943"
    ],
    "summaries": [
      "powerline fails to build with Python 3.14: ValueError: argument groups cannot be nested"
    ]
  },
  "prewikka": {
    "urls": [],
    "summaries": []
  },
  "protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341106"
    ],
    "summaries": [
      "protobuf: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pybind11": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336889"
    ],
    "summaries": [
      "pybind11 fails to build with Python 3.14: AttributeError: 'pybind11_tests.pickling.PickleableWithDict' object has no attribute 'dynamic' + AssertionError"
    ]
  },
  "pycairo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322709"
    ],
    "summaries": [
      "pycairo fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pygsl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341119"
    ],
    "summaries": [
      "pygsl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pyproj": {
    "urls": [],
    "summaries": []
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pysubnettree": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341123"
    ],
    "summaries": [
      "pysubnettree: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-APScheduler": {
    "urls": [],
    "summaries": []
  },
  "python-AppTools": {
    "urls": [],
    "summaries": []
  },
  "python-Automat": {
    "urls": [],
    "summaries": []
  },
  "python-XStatic-roboto-fontface": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp": {
    "urls": [],
    "summaries": []
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-anyio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328710"
    ],
    "summaries": [
      "python-anyio fails to build with Python 3.14: AttributeError: '_UnixDefaultEventLoopPolicy' object has no attribute 'get_child_watcher' && TypeError: PurePath.relative_to() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-apsw": {
    "urls": [],
    "summaries": []
  },
  "python-aresponses": {
    "urls": [],
    "summaries": []
  },
  "python-ase": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336912"
    ],
    "summaries": [
      "python-ase: FTBFS in Fedora Rawhide: ImportError: cannot import name 'VisibleDeprecationWarning' from 'numpy' (/usr/lib64/python3.13/site-packages/numpy/__init__.py)"
    ]
  },
  "python-astroid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
    ],
    "summaries": [
      "python-astroid fails to build with Python 3.14: astroid.exceptions.InferenceError: StopIteration raised without any error information."
    ]
  },
  "python-astropy-iers-data": {
    "urls": [],
    "summaries": []
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-attrs": {
    "urls": [],
    "summaries": []
  },
  "python-auth-credential": {
    "urls": [],
    "summaries": []
  },
  "python-autocommand": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
    ],
    "summaries": [
      "python-autocommand fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341130",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado: FTBFS in Fedora rawhide/f42",
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-backrefs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325184"
    ],
    "summaries": [
      "python-backrefs fails to build with Python 3.14: Failed to acquire all needed Unicode files!"
    ]
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341131",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype: FTBFS in Fedora rawhide/f42",
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-behave": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339094"
    ],
    "summaries": [
      "python-behave fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-blinker": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325193"
    ],
    "summaries": [
      "python-blinker fails to build with Python 3.14: pluggy.PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown."
    ]
  },
  "python-bravado": {
    "urls": [],
    "summaries": []
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-catkin_tools": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341134"
    ],
    "summaries": [
      "python-catkin_tools: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-cattrs": {
    "urls": [],
    "summaries": []
  },
  "python-colcon-cmake": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339465"
    ],
    "summaries": [
      "python-colcon-cmake fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-colcon-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339464"
    ],
    "summaries": [
      "python-colcon-core fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-commoncode": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325197"
    ],
    "summaries": [
      "python-commoncode fails to build with Python 3.14: tarfile.SpecialFileError: '6-FIFOTYPE' is a special file"
    ]
  },
  "python-confuse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
    ],
    "summaries": [
      "python-confuse fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-contourpy": {
    "urls": [],
    "summaries": []
  },
  "python-cornice": {
    "urls": [],
    "summaries": []
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-cryptography": {
    "urls": [],
    "summaries": []
  },
  "python-cysignals": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325457"
    ],
    "summaries": [
      "python-cysignals fails to build with Python 3.14: Doctest src/cysignals/pselect.pyx terminated. Timeout limit exceeded (>2400s)"
    ]
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-dateparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336931"
    ],
    "summaries": [
      "python-dateparser: FTBFS in Fedora Rawhide: AssertionError in TestTranslateSearch.test_relative_base_setting_2_en"
    ]
  },
  "python-defcon": {
    "urls": [],
    "summaries": []
  },
  "python-dill": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323157"
    ],
    "summaries": [
      "python-dill fails to build with Python 3.14: TypeError: _Pickler._batch_setitems() missing 1 required positional argument: 'obj'"
    ]
  },
  "python-django-allauth": {
    "urls": [],
    "summaries": []
  },
  "python-django-contrib-comments": {
    "urls": [],
    "summaries": []
  },
  "python-django-debreach": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328003"
    ],
    "summaries": [
      "python-django-debreach fails to build with Python 3.14: AttributeError: 'super' object has no attribute 'dicts' and no __dict__ for setting new attributes"
    ]
  },
  "python-django-filter": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336944"
    ],
    "summaries": [
      "python-django-filter fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "python-django-mailman3": {
    "urls": [],
    "summaries": []
  },
  "python-djangoql": {
    "urls": [],
    "summaries": []
  },
  "python-epub": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319654"
    ],
    "summaries": [
      "python-epub fails to build with setuptools 74+"
    ]
  },
  "python-etcd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
    ],
    "summaries": [
      "python-etcd fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestWatch.test_watch_indexed_generator.<locals>.watch_value at 0x7f0d39f71dd0>"
    ]
  },
  "python-events": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319655"
    ],
    "summaries": [
      "python-events fails to build with setuptools 74+"
    ]
  },
  "python-executing": {
    "urls": [],
    "summaries": []
  },
  "python-fedora": {
    "urls": [],
    "summaries": []
  },
  "python-flask": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327965"
    ],
    "summaries": [
      "python-flask fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-fs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336951"
    ],
    "summaries": [
      "python-fs fails to build with Python 3.14: AssertionError: 'osfs://///tmp/tmppauy69swfstestosfs/foo' != 'osfs:///tmp/tmppauy69swfstestosfs/foo'"
    ]
  },
  "python-fsleyes-widgets": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336911"
    ],
    "summaries": [
      "python-fsleyes-widgets fails to build with Python 3.14: AssertionError: assert 'file:/home/b...htmlfile.html' == 'file:///home...htmlfile.html'"
    ]
  },
  "python-genty": {
    "urls": [],
    "summaries": []
  },
  "python-giacpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341608"
    ],
    "summaries": [
      "python-giacpy: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-git-revise": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341157"
    ],
    "summaries": [
      "python-git-revise: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-glyphsLib": {
    "urls": [],
    "summaries": []
  },
  "python-gphoto2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341158"
    ],
    "summaries": [
      "python-gphoto2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-graph-tool": {
    "urls": [],
    "summaries": []
  },
  "python-h5netcdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325222"
    ],
    "summaries": [
      "python-h5netcdf fails to build with Python 3.14: test_no_circular_references: AssertionError"
    ]
  },
  "python-hamcrest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341160"
    ],
    "summaries": [
      "python-hamcrest: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-hl7": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341161"
    ],
    "summaries": [
      "python-hl7: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-httpretty": {
    "urls": [],
    "summaries": []
  },
  "python-icalendar": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341163"
    ],
    "summaries": [
      "python-icalendar: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-img2pdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328707"
    ],
    "summaries": [
      "python-img2pdf fails to build in rawhide: 48 AssertionErrors"
    ]
  },
  "python-iniparse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
    ],
    "summaries": [
      "python-iniparse fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestIni.test_queue.<locals>.getxy at 0x7f86659a7740>"
    ]
  },
  "python-inject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
    ],
    "summaries": [
      "python-inject fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-ipyparallel": {
    "urls": [],
    "summaries": []
  },
  "python-irc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
    ],
    "summaries": [
      "python-irc fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-jack-client": {
    "urls": [],
    "summaries": []
  },
  "python-jeepney": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327982"
    ],
    "summaries": [
      "python-jeepney fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-joblib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339519"
    ],
    "summaries": [
      "python-joblib fails to build with Python 3.14: TypeError: Hasher._batch_setitems() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-josepy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323171"
    ],
    "summaries": [
      "python-josepy fails to build with Python 3.14: 6x ValueError: Field `alg` in JSONObject `Header` has no type annotation."
    ]
  },
  "python-jupyter-c-kernel": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-client": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-kernel-singular": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-polymake": {
    "urls": [],
    "summaries": []
  },
  "python-kadmin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341167"
    ],
    "summaries": [
      "python-kadmin: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-mapbox-earcut": {
    "urls": [],
    "summaries": []
  },
  "python-matplotlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341338",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328713"
    ],
    "summaries": [
      "python-matplotlib: FTBFS in Fedora rawhide/f42",
      "python-matplotlib fails to build with Python 3.14: RecursionError: maximum recursion depth exceeded"
    ]
  },
  "python-mccabe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328016"
    ],
    "summaries": [
      "python-mccabe fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-messaging": {
    "urls": [],
    "summaries": []
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-msgspec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325169"
    ],
    "summaries": [
      "python-msgspec fails to build with Python 3.14: error: \u2018_Py_IMMORTAL_REFCNT\u2019 undeclared here"
    ]
  },
  "python-ndindex": {
    "urls": [],
    "summaries": []
  },
  "python-nose": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323163"
    ],
    "summaries": [
      "python-nose fails to build with Python 3.14: multiple AssertionErrors related to timeouts in test outputs"
    ]
  },
  "python-notify2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341175"
    ],
    "summaries": [
      "python-notify2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-oscrypto": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341177"
    ],
    "summaries": [
      "python-oscrypto: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pandas": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341179"
    ],
    "summaries": [
      "python-pandas: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-photutils": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336893"
    ],
    "summaries": [
      "python-photutils: FTBFS in Fedora Rawhide: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments."
    ]
  },
  "python-pip": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335909"
    ],
    "summaries": [
      "python-pip fails to build with Python 3.14: AssertionError: assert 'file:/tmp/file' == 'file:///tmp/file'"
    ]
  },
  "python-psycogreen": {
    "urls": [],
    "summaries": []
  },
  "python-psycopg3": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339461"
    ],
    "summaries": [
      "python-psycopg3 fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-pulp-glue": {
    "urls": [],
    "summaries": []
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-pyairvisual": {
    "urls": [],
    "summaries": []
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pydantic-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
    ],
    "summaries": [
      "python-pydantic-core fails to build with Python 3.14: AssertionError: Regex pattern did not match. + AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pymdown-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336948"
    ],
    "summaries": [
      "python-pymdown-extensions fails to build with Python 3.14: TestAbsolute.test_relative_path and TestAbsoluteFileScheme.test_relative_path AssertionErrors"
    ]
  },
  "python-pymeeus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341186"
    ],
    "summaries": [
      "python-pymeeus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pymilter": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341187"
    ],
    "summaries": [
      "python-pymilter: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pymongo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341188"
    ],
    "summaries": [
      "python-pymongo: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pymssql": {
    "urls": [],
    "summaries": []
  },
  "python-pyopencl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341190"
    ],
    "summaries": [
      "python-pyopencl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyopengl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341191"
    ],
    "summaries": [
      "python-pyopengl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyqt-feedback-flow": {
    "urls": [],
    "summaries": []
  },
  "python-pyqtgraph": {
    "urls": [],
    "summaries": []
  },
  "python-pyquery": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341196"
    ],
    "summaries": [
      "python-pyquery: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pytesseract": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341201"
    ],
    "summaries": [
      "python-pytesseract: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pytest-aiohttp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339466"
    ],
    "summaries": [
      "python-pytest-aiohttp fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-pytest-asyncio": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-django": {
    "urls": [],
    "summaries": []
  },
  "python-pytz-deprecation-shim": {
    "urls": [],
    "summaries": []
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-pyvlx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
    ],
    "summaries": [
      "python-pyvlx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pywt": {
    "urls": [],
    "summaries": []
  },
  "python-qt5": {
    "urls": [],
    "summaries": []
  },
  "python-rdflib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341203",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336891"
    ],
    "summaries": [
      "python-rdflib: FTBFS in Fedora rawhide/f42",
      "python-rdflib fails to build with Python 3.14: \"TypeError: '<' not supported between instances of 'Literal' and 'Literal'\""
    ]
  },
  "python-reactivex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
    ],
    "summaries": [
      "python-reactivex fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-redis": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341204",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326927"
    ],
    "summaries": [
      "python-redis: FTBFS in Fedora rawhide/f42",
      "python-redis fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_redis_client.<locals>.target at 0x7fd5f829efb0>"
    ]
  },
  "python-remoto": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341205"
    ],
    "summaries": [
      "python-remoto: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-reportlab": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331341"
    ],
    "summaries": [
      "python-reportlab fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-requests-toolbelt": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341206"
    ],
    "summaries": [
      "python-requests-toolbelt: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-rich": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339510"
    ],
    "summaries": [
      "python-rich fails to build with Python 3.14: 5 test fail"
    ]
  },
  "python-rosdep": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341207"
    ],
    "summaries": [
      "python-rosdep: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-rq": {
    "urls": [],
    "summaries": []
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-s3transfer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326933"
    ],
    "summaries": [
      "python-s3transfer fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <class 'tests.unit.test_compat.TestBaseManager.create_pid_manager.<locals>.PIDManager'>"
    ]
  },
  "python-seaborn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341210"
    ],
    "summaries": [
      "python-seaborn: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-sep": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336965"
    ],
    "summaries": [
      "python-sep: FTBFS in Fedora Rawhide: Error compiling Cython file: 'int_t' is not a type identifier"
    ]
  },
  "python-serpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319716"
    ],
    "summaries": [
      "python-serpy fails to build with setuptools 74+"
    ]
  },
  "python-setuptools-rust": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336950"
    ],
    "summaries": [
      "python-setuptools-rust fails to build with Python 3.14: /builddir/build/BUILD/python-setuptools-rust-1.10.2-build/setuptools_rust-1.10.2/examples/hello-world/venv/bin/python: No module named pytest"
    ]
  },
  "python-simplegeneric": {
    "urls": [],
    "summaries": []
  },
  "python-simplevisor": {
    "urls": [],
    "summaries": []
  },
  "python-singledispatch": {
    "urls": [],
    "summaries": []
  },
  "python-social-auth-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341215",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328010"
    ],
    "summaries": [
      "python-social-auth-core: FTBFS in Fedora rawhide/f42",
      "python-social-auth-core fails to build with Python 3.14: 'SSLContext' object has no attribute 'close'"
    ]
  },
  "python-sphinxcontrib-blockdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-github-alt": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-programoutput": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-seqdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy1.4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
    ],
    "summaries": [
      "python-sqlalchemy1.4 fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-sshpubkeys": {
    "urls": [],
    "summaries": []
  },
  "python-stdlibs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336938"
    ],
    "summaries": [
      "python-stdlibs fails to build with Python 3.14: test_all_my_modules_are_there: AssertionError: Items in the second set but not the first: '_apple_support'"
    ]
  },
  "python-succulent": {
    "urls": [],
    "summaries": []
  },
  "python-svg2tikz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341220"
    ],
    "summaries": [
      "python-svg2tikz: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-tenacity": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
    ],
    "summaries": [
      "python-tenacity fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-terminado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341222"
    ],
    "summaries": [
      "python-terminado: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-tgscheduler": {
    "urls": [],
    "summaries": []
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-tornado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
    ],
    "summaries": [
      "python-tornado fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-tpm2-pytss": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341227"
    ],
    "summaries": [
      "python-tpm2-pytss: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-traitsui": {
    "urls": [],
    "summaries": []
  },
  "python-tree-format": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319731"
    ],
    "summaries": [
      "python-tree-format fails to build with setuptools 74+"
    ]
  },
  "python-twilio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341229"
    ],
    "summaries": [
      "python-twilio: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-twisted": {
    "urls": [],
    "summaries": []
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typeguard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328015"
    ],
    "summaries": [
      "python-typeguard fails to build with Python 3.14: typeguard.TypeCheckError: argument \"x\" (class dummymodule.DummyClass) is not a subclass of dummymodule.DummyClass && AssertionError: Regex pattern did not match."
    ]
  },
  "python-typing-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336937"
    ],
    "summaries": [
      "python-typing-extensions fails to build with Python 3.14: test_drop_in_for_typing: AssertionError: self.assertGreaterEqual(te_all, t_all - exceptions)"
    ]
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-urwid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
    ],
    "summaries": [
      "python-urwid fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341233",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop: FTBFS in Fedora rawhide/f42",
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-valkey": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341234",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326934"
    ],
    "summaries": [
      "python-valkey: FTBFS in Fedora rawhide/f42",
      "python-valkey fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f7d711b5dd0>"
    ]
  },
  "python-virtualbmc": {
    "urls": [],
    "summaries": []
  },
  "python-virtualenv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336936"
    ],
    "summaries": [
      "python-virtualenv fails to build with Python 3.14: AssertionError: common, \"\\n\".join(difflib.unified_diff(list_to_str(sys_path), list_to_str(system_sys_path)))"
    ]
  },
  "python-watchfiles": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339462"
    ],
    "summaries": [
      "python-watchfiles fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-webscrapbook": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341237",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326915"
    ],
    "summaries": [
      "python-webscrapbook: FTBFS in Fedora rawhide/f42",
      "python-webscrapbook fails to build with Python 3.14: 60x AssertionError in the test suite"
    ]
  },
  "python-wled": {
    "urls": [],
    "summaries": []
  },
  "python-wordcloud": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335908"
    ],
    "summaries": [
      "python-wordcloud fails to build with Python 3.14: test_cli_as_executable: AssertionError: assert expected_output in out if ret_code == 0 else err"
    ]
  },
  "python-wsgi_intercept": {
    "urls": [],
    "summaries": []
  },
  "python-xunitparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319738"
    ],
    "summaries": [
      "python-xunitparser fails to build with setuptools 74+"
    ]
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-zake": {
    "urls": [],
    "summaries": []
  },
  "python-zc-lockfile": {
    "urls": [],
    "summaries": []
  },
  "python-zope-deprecation": {
    "urls": [],
    "summaries": []
  },
  "python-zope-testing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341242"
    ],
    "summaries": [
      "python-zope-testing: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-zope-testrunner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335907"
    ],
    "summaries": [
      "python-zope-testrunner fails to build with Python 3.14: difference in the asserted content in testrunner-edge-cases.rst"
    ]
  },
  "python-zstandard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326925"
    ],
    "summaries": [
      "python-zstandard fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "qpid-proton": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341251",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327999"
    ],
    "summaries": [
      "qpid-proton: FTBFS in Fedora rawhide/f42",
      "qpid-proton fails to build with Python 3.14: error: File not found: /builddir/build/BUILD/qpid-proton-0.38.0-build/BUILDROOT/usr/share/proton/docs/api-py"
    ]
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "realtime-tests": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341270"
    ],
    "summaries": [
      "realtime-tests: FTBFS in Fedora rawhide/f42"
    ]
  },
  "recoll": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341273"
    ],
    "summaries": [
      "recoll: FTBFS in Fedora rawhide/f42"
    ]
  },
  "remmina": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341277"
    ],
    "summaries": [
      "remmina: FTBFS in Fedora rawhide/f42"
    ]
  },
  "renderdoc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341279"
    ],
    "summaries": [
      "renderdoc: FTBFS in Fedora rawhide/f42"
    ]
  },
  "rmol": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341283"
    ],
    "summaries": [
      "rmol: FTBFS in Fedora rawhide/f42"
    ]
  },
  "root": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341287"
    ],
    "summaries": [
      "root: FTBFS in Fedora rawhide/f42"
    ]
  },
  "satyr": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
    ],
    "summaries": [
      "satyr fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestDistances.test_distances_part_parallel.<locals>.do_test.<locals>.compute_part at 0x7f7f845f2560>"
    ]
  },
  "scipy": {
    "urls": [],
    "summaries": []
  },
  "signon-glib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341348"
    ],
    "summaries": [
      "signon-glib: FTBFS in Fedora rawhide/f42"
    ]
  },
  "speech-dispatcher": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341370"
    ],
    "summaries": [
      "speech-dispatcher: FTBFS in Fedora rawhide/f42"
    ]
  },
  "strongswan": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332864"
    ],
    "summaries": [
      "strongswan-5.9.14-5.fc42 FTBFS: strongswan-5.9.14/missing: line 81: aclocal-1.16: command not found"
    ]
  },
  "syncplay": {
    "urls": [],
    "summaries": []
  },
  "tcl-snack": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341418"
    ],
    "summaries": [
      "tcl-snack: FTBFS in Fedora rawhide/f42"
    ]
  },
  "thrift": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341433"
    ],
    "summaries": [
      "thrift: FTBFS in Fedora rawhide/f42"
    ]
  },
  "trac": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341454"
    ],
    "summaries": [
      "trac: FTBFS in Fedora rawhide/f42"
    ]
  },
  "trademgen": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341457"
    ],
    "summaries": [
      "trademgen: FTBFS in Fedora rawhide/f42"
    ]
  },
  "trash-cli": {
    "urls": [],
    "summaries": []
  },
  "ufw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341477"
    ],
    "summaries": [
      "ufw: FTBFS in Fedora rawhide/f42"
    ]
  },
  "uhd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341478"
    ],
    "summaries": [
      "uhd: FTBFS in Fedora rawhide/f42"
    ]
  },
  "uwsgi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341497"
    ],
    "summaries": [
      "uwsgi: FTBFS in Fedora rawhide/f42"
    ]
  },
  "veusz": {
    "urls": [],
    "summaries": []
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "vtk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341520"
    ],
    "summaries": [
      "vtk: FTBFS in Fedora rawhide/f42"
    ]
  },
  "weasyprint": {
    "urls": [],
    "summaries": []
  },
  "xen": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341566"
    ],
    "summaries": [
      "xen: FTBFS in Fedora rawhide/f42"
    ]
  },
  "xonsh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336895"
    ],
    "summaries": [
      "xonsh fails to build with Python 3.14: ValueError: action 'store_true' is not valid for positional arguments"
    ]
  },
  "xpra": {
    "urls": [],
    "summaries": []
  },
  "yamllint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336947"
    ],
    "summaries": [
      "yamllint fails to build with Python 3.14: ValueError('I/O operation on closed file')"
    ]
  }
}