{
  "RBTools": {
    "urls": [],
    "summaries": []
  },
  "adapt": {
    "urls": [],
    "summaries": []
  },
  "alot": {
    "urls": [],
    "summaries": []
  },
  "ara": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331346"
    ],
    "summaries": [
      "ara fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "bids-schema": {
    "urls": [],
    "summaries": []
  },
  "binwalk": {
    "urls": [],
    "summaries": []
  },
  "boost": {
    "urls": [],
    "summaries": []
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "ceph": {
    "urls": [],
    "summaries": []
  },
  "chirp": {
    "urls": [],
    "summaries": []
  },
  "cockpit": {
    "urls": [],
    "summaries": []
  },
  "collectd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332982"
    ],
    "summaries": [
      "collectd-5.12.0-45.fc42 FTBFS: collectd-5.12.0/build-aux/missing: line 81: aclocal-1.16: command not found"
    ]
  },
  "did": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328006"
    ],
    "summaries": [
      "did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'"
    ]
  },
  "dlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328014"
    ],
    "summaries": [
      "dlib fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "dnf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323186"
    ],
    "summaries": [
      "dnf fails to build with Python 3.14: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "elements-alexandria": {
    "urls": [],
    "summaries": []
  },
  "espresso": {
    "urls": [],
    "summaries": []
  },
  "esptool": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331345"
    ],
    "summaries": [
      "esptool fails to build with Python 3.14: AssertionError: assert 'usage: __main__.py [-h]' in 'espefuse.py v4.8.1\\nusage: python3 -m espefuse [-h]\\n                           [--chip {auto,esp32,esp32c2,esp32c3,e... --extend-efuse-table EXTEND_EFUSE_TABLE\\"
    ]
  },
  "fedfind": {
    "urls": [],
    "summaries": []
  },
  "fedscm-admin": {
    "urls": [],
    "summaries": []
  },
  "flann": {
    "urls": [],
    "summaries": []
  },
  "ioc-writer": {
    "urls": [],
    "summaries": []
  },
  "jc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331343"
    ],
    "summaries": [
      "jc fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "kicad": {
    "urls": [],
    "summaries": []
  },
  "libarrow": {
    "urls": [],
    "summaries": []
  },
  "libgpiod": {
    "urls": [],
    "summaries": []
  },
  "libnvme": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325194"
    ],
    "summaries": [
      "libnvme fails to build with Python 3.14: /usr/include/python3.14/pyport.h:629:35: error: missing ')' after \"__has_attribute\""
    ]
  },
  "linode-cli": {
    "urls": [],
    "summaries": []
  },
  "llvm": {
    "urls": [],
    "summaries": []
  },
  "mathgl": {
    "urls": [],
    "summaries": []
  },
  "mlpack": {
    "urls": [],
    "summaries": []
  },
  "mopidy-mpd": {
    "urls": [],
    "summaries": []
  },
  "nox": {
    "urls": [],
    "summaries": []
  },
  "nwchem": {
    "urls": [],
    "summaries": []
  },
  "opentrep": {
    "urls": [],
    "summaries": []
  },
  "pacemaker": {
    "urls": [],
    "summaries": []
  },
  "pcs": {
    "urls": [],
    "summaries": []
  },
  "petsc": {
    "urls": [],
    "summaries": []
  },
  "plplot": {
    "urls": [],
    "summaries": []
  },
  "postgresql15": {
    "urls": [],
    "summaries": []
  },
  "postgresql16": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332981"
    ],
    "summaries": [
      "postgresql16-16.3-7.fc42 FTBFS: tests fail with tzdata-2024b"
    ]
  },
  "postgresql17": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332978",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327967"
    ],
    "summaries": [
      "postgresql17-17.0-1.fc42 FTBFS: RPM build errors: line 227: second Description",
      "postgresql17 fails to build with Python 3.14: jsonb_jsonpath fails: - \"12:34:56-07:00\" != + \"12:34:56-08:00\""
    ]
  },
  "powerline": {
    "urls": [],
    "summaries": []
  },
  "prewikka": {
    "urls": [],
    "summaries": []
  },
  "protobuf": {
    "urls": [],
    "summaries": []
  },
  "pybind11": {
    "urls": [],
    "summaries": []
  },
  "pycairo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322709"
    ],
    "summaries": [
      "pycairo fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pygsl": {
    "urls": [],
    "summaries": []
  },
  "pyproj": {
    "urls": [],
    "summaries": []
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-APScheduler": {
    "urls": [],
    "summaries": []
  },
  "python-PyGithub": {
    "urls": [],
    "summaries": []
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-anyio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328710"
    ],
    "summaries": [
      "python-anyio fails to build with Python 3.14: AttributeError: '_UnixDefaultEventLoopPolicy' object has no attribute 'get_child_watcher' && TypeError: PurePath.relative_to() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-apsw": {
    "urls": [],
    "summaries": []
  },
  "python-astroid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
    ],
    "summaries": [
      "python-astroid fails to build with Python 3.14: astroid.exceptions.InferenceError: StopIteration raised without any error information."
    ]
  },
  "python-asttokens": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331375"
    ],
    "summaries": [
      "python-asttokens fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-async-lru": {
    "urls": [],
    "summaries": []
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-attrs": {
    "urls": [],
    "summaries": []
  },
  "python-auth-credential": {
    "urls": [],
    "summaries": []
  },
  "python-autocommand": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
    ],
    "summaries": [
      "python-autocommand fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-autograd": {
    "urls": [],
    "summaries": []
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-backrefs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325184"
    ],
    "summaries": [
      "python-backrefs fails to build with Python 3.14: Failed to acquire all needed Unicode files!"
    ]
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-behave": {
    "urls": [],
    "summaries": []
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-binaryornot": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319640"
    ],
    "summaries": [
      "python-binaryornot fails to build with setuptools 74+"
    ]
  },
  "python-bioread": {
    "urls": [],
    "summaries": []
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-cccolutils": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319642"
    ],
    "summaries": [
      "python-cccolutils fails to build with setuptools 74+"
    ]
  },
  "python-cffi": {
    "urls": [],
    "summaries": []
  },
  "python-chameleon": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322715"
    ],
    "summaries": [
      "python-chameleon fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-collada": {
    "urls": [],
    "summaries": []
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-commoncode": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325197"
    ],
    "summaries": [
      "python-commoncode fails to build with Python 3.14: tarfile.SpecialFileError: '6-FIFOTYPE' is a special file"
    ]
  },
  "python-confuse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
    ],
    "summaries": [
      "python-confuse fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-contourpy": {
    "urls": [],
    "summaries": []
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-cysignals": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325457"
    ],
    "summaries": [
      "python-cysignals fails to build with Python 3.14: Doctest src/cysignals/pselect.pyx terminated. Timeout limit exceeded (>2400s)"
    ]
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-dateparser": {
    "urls": [],
    "summaries": []
  },
  "python-defcon": {
    "urls": [],
    "summaries": []
  },
  "python-dill": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323157"
    ],
    "summaries": [
      "python-dill fails to build with Python 3.14: TypeError: _Pickler._batch_setitems() missing 1 required positional argument: 'obj'"
    ]
  },
  "python-django-allauth": {
    "urls": [],
    "summaries": []
  },
  "python-django-contrib-comments": {
    "urls": [],
    "summaries": []
  },
  "python-django-debreach": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328003"
    ],
    "summaries": [
      "python-django-debreach fails to build with Python 3.14: AttributeError: 'super' object has no attribute 'dicts' and no __dict__ for setting new attributes"
    ]
  },
  "python-django-filter": {
    "urls": [],
    "summaries": []
  },
  "python-django-mailman3": {
    "urls": [],
    "summaries": []
  },
  "python-djangoql": {
    "urls": [],
    "summaries": []
  },
  "python-dunamai": {
    "urls": [],
    "summaries": []
  },
  "python-emcee": {
    "urls": [],
    "summaries": []
  },
  "python-epub": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319654"
    ],
    "summaries": [
      "python-epub fails to build with setuptools 74+"
    ]
  },
  "python-etcd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
    ],
    "summaries": [
      "python-etcd fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestWatch.test_watch_indexed_generator.<locals>.watch_value at 0x7f0d39f71dd0>"
    ]
  },
  "python-events": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319655"
    ],
    "summaries": [
      "python-events fails to build with setuptools 74+"
    ]
  },
  "python-exdir": {
    "urls": [],
    "summaries": []
  },
  "python-flask": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327965"
    ],
    "summaries": [
      "python-flask fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-flufl-i18n": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319659"
    ],
    "summaries": [
      "python-flufl-i18n fails to build with setuptools 74+"
    ]
  },
  "python-fs": {
    "urls": [],
    "summaries": []
  },
  "python-genty": {
    "urls": [],
    "summaries": []
  },
  "python-giacpy": {
    "urls": [],
    "summaries": []
  },
  "python-glyphsLib": {
    "urls": [],
    "summaries": []
  },
  "python-gradunwarp": {
    "urls": [],
    "summaries": []
  },
  "python-gunicorn": {
    "urls": [],
    "summaries": []
  },
  "python-h5netcdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325222"
    ],
    "summaries": [
      "python-h5netcdf fails to build with Python 3.14: test_no_circular_references: AssertionError"
    ]
  },
  "python-hamcrest": {
    "urls": [],
    "summaries": []
  },
  "python-httpretty": {
    "urls": [],
    "summaries": []
  },
  "python-icalendar": {
    "urls": [],
    "summaries": []
  },
  "python-img2pdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328707"
    ],
    "summaries": [
      "python-img2pdf fails to build in rawhide: 48 AssertionErrors"
    ]
  },
  "python-iniparse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
    ],
    "summaries": [
      "python-iniparse fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestIni.test_queue.<locals>.getxy at 0x7f86659a7740>"
    ]
  },
  "python-inject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
    ],
    "summaries": [
      "python-inject fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-inkex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331350"
    ],
    "summaries": [
      "python-inkex fails to build with Python 3.14: InxTestCase.test_inx_files: ValueError: badly formed help string"
    ]
  },
  "python-irc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
    ],
    "summaries": [
      "python-irc fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-jack-client": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319666"
    ],
    "summaries": [
      "python-jack-client fails to build with setuptools 74+"
    ]
  },
  "python-jeepney": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327982"
    ],
    "summaries": [
      "python-jeepney fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-joblib": {
    "urls": [],
    "summaries": []
  },
  "python-josepy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323171"
    ],
    "summaries": [
      "python-josepy fails to build with Python 3.14: 6x ValueError: Field `alg` in JSONObject `Header` has no type annotation."
    ]
  },
  "python-jupyter-client": {
    "urls": [],
    "summaries": []
  },
  "python-klusta": {
    "urls": [],
    "summaries": []
  },
  "python-lazyarray": {
    "urls": [],
    "summaries": []
  },
  "python-libarchive-c": {
    "urls": [],
    "summaries": []
  },
  "python-libcst": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328019"
    ],
    "summaries": [
      "python-libcst fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-lqrt": {
    "urls": [],
    "summaries": []
  },
  "python-lxml": {
    "urls": [],
    "summaries": []
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-matplotlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328713"
    ],
    "summaries": [
      "python-matplotlib fails to build with Python 3.14: RecursionError: maximum recursion depth exceeded"
    ]
  },
  "python-mccabe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328016"
    ],
    "summaries": [
      "python-mccabe fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-meson-python": {
    "urls": [],
    "summaries": []
  },
  "python-messaging": {
    "urls": [],
    "summaries": []
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-msgspec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325169"
    ],
    "summaries": [
      "python-msgspec fails to build with Python 3.14: error: \u2018_Py_IMMORTAL_REFCNT\u2019 undeclared here"
    ]
  },
  "python-ndindex": {
    "urls": [],
    "summaries": []
  },
  "python-neovim": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326224"
    ],
    "summaries": [
      "python-neovim fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'get_child_watcher'"
    ]
  },
  "python-nibabel": {
    "urls": [],
    "summaries": []
  },
  "python-nmrglue": {
    "urls": [],
    "summaries": []
  },
  "python-nose": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323163"
    ],
    "summaries": [
      "python-nose fails to build with Python 3.14: multiple AssertionErrors related to timeouts in test outputs"
    ]
  },
  "python-numpy-stl": {
    "urls": [],
    "summaries": []
  },
  "python-openidc-client": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319685"
    ],
    "summaries": [
      "python-openidc-client fails to build with setuptools 74+"
    ]
  },
  "python-orjson": {
    "urls": [],
    "summaries": []
  },
  "python-oscrypto": {
    "urls": [],
    "summaries": []
  },
  "python-pandas": {
    "urls": [],
    "summaries": []
  },
  "python-pandas-datareader": {
    "urls": [],
    "summaries": []
  },
  "python-parsel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319689"
    ],
    "summaries": [
      "python-parsel fails to build with setuptools 74+"
    ]
  },
  "python-patsy": {
    "urls": [],
    "summaries": []
  },
  "python-pdfkit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319690"
    ],
    "summaries": [
      "python-pdfkit fails to build with setuptools 74+"
    ]
  },
  "python-pdm-backend": {
    "urls": [],
    "summaries": []
  },
  "python-periodictable": {
    "urls": [],
    "summaries": []
  },
  "python-pexpect": {
    "urls": [],
    "summaries": []
  },
  "python-pillow": {
    "urls": [],
    "summaries": []
  },
  "python-pip": {
    "urls": [],
    "summaries": []
  },
  "python-psycogreen": {
    "urls": [],
    "summaries": []
  },
  "python-pulp-glue": {
    "urls": [],
    "summaries": []
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-pybbi": {
    "urls": [],
    "summaries": []
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pyclipper": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319696"
    ],
    "summaries": [
      "python-pyclipper fails to build with setuptools 74+"
    ]
  },
  "python-pydantic-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
    ],
    "summaries": [
      "python-pydantic-core fails to build with Python 3.14: AssertionError: Regex pattern did not match. + AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pyface": {
    "urls": [],
    "summaries": []
  },
  "python-pygit2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328023"
    ],
    "summaries": [
      "python-pygit2 fails to build with Python 3.14: TypeError: 'GenericIterator' object is not iterable"
    ]
  },
  "python-pygmtools": {
    "urls": [],
    "summaries": []
  },
  "python-pymatreader": {
    "urls": [],
    "summaries": []
  },
  "python-pymdown-extensions": {
    "urls": [],
    "summaries": []
  },
  "python-pymeeus": {
    "urls": [],
    "summaries": []
  },
  "python-pymongo": {
    "urls": [],
    "summaries": []
  },
  "python-pyongc": {
    "urls": [],
    "summaries": []
  },
  "python-pyopencl": {
    "urls": [],
    "summaries": []
  },
  "python-pyopengl": {
    "urls": [],
    "summaries": []
  },
  "python-pyqt-feedback-flow": {
    "urls": [],
    "summaries": []
  },
  "python-pyqtgraph": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid_sawing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319702"
    ],
    "summaries": [
      "python-pyramid_sawing fails to build with setuptools 74+"
    ]
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pyspike": {
    "urls": [],
    "summaries": []
  },
  "python-pytaglib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319705"
    ],
    "summaries": [
      "python-pytaglib fails to build with setuptools 74+"
    ]
  },
  "python-pytesseract": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-arraydiff": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-asyncio": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-django": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-flakes": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319708"
    ],
    "summaries": [
      "python-pytest-flakes fails to build with setuptools 74+"
    ]
  },
  "python-pytz-deprecation-shim": {
    "urls": [],
    "summaries": []
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-pyvlx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
    ],
    "summaries": [
      "python-pyvlx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-rdflib": {
    "urls": [],
    "summaries": []
  },
  "python-reactivex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
    ],
    "summaries": [
      "python-reactivex fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-redis": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326927"
    ],
    "summaries": [
      "python-redis fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_redis_client.<locals>.target at 0x7fd5f829efb0>"
    ]
  },
  "python-remoto": {
    "urls": [],
    "summaries": []
  },
  "python-reportlab": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331341"
    ],
    "summaries": [
      "python-reportlab fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-repoze-lru": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319711"
    ],
    "summaries": [
      "python-repoze-lru fails to build with setuptools 74+"
    ]
  },
  "python-requests-toolbelt": {
    "urls": [],
    "summaries": []
  },
  "python-rich": {
    "urls": [],
    "summaries": []
  },
  "python-rpmfluff": {
    "urls": [],
    "summaries": []
  },
  "python-rq": {
    "urls": [],
    "summaries": []
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-s3transfer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326933"
    ],
    "summaries": [
      "python-s3transfer fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <class 'tests.unit.test_compat.TestBaseManager.create_pid_manager.<locals>.PIDManager'>"
    ]
  },
  "python-sep": {
    "urls": [],
    "summaries": []
  },
  "python-serpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319716"
    ],
    "summaries": [
      "python-serpy fails to build with setuptools 74+"
    ]
  },
  "python-setuptools-rust": {
    "urls": [],
    "summaries": []
  },
  "python-simplegeneric": {
    "urls": [],
    "summaries": []
  },
  "python-simplevisor": {
    "urls": [],
    "summaries": []
  },
  "python-singledispatch": {
    "urls": [],
    "summaries": []
  },
  "python-social-auth-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328010"
    ],
    "summaries": [
      "python-social-auth-core fails to build with Python 3.14: 'SSLContext' object has no attribute 'close'"
    ]
  },
  "python-sphinxcontrib-blockdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-programoutput": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-seqdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy1.4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
    ],
    "summaries": [
      "python-sqlalchemy1.4 fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-sshpubkeys": {
    "urls": [],
    "summaries": []
  },
  "python-statsmodels": {
    "urls": [],
    "summaries": []
  },
  "python-stdlibs": {
    "urls": [],
    "summaries": []
  },
  "python-surt": {
    "urls": [],
    "summaries": []
  },
  "python-svg2tikz": {
    "urls": [],
    "summaries": []
  },
  "python-tabulate": {
    "urls": [],
    "summaries": []
  },
  "python-tenacity": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
    ],
    "summaries": [
      "python-tenacity fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-terminado": {
    "urls": [],
    "summaries": []
  },
  "python-tgscheduler": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319728"
    ],
    "summaries": [
      "python-tgscheduler fails to build with setuptools 74+"
    ]
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-tornado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
    ],
    "summaries": [
      "python-tornado fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-tpm2-pytss": {
    "urls": [],
    "summaries": []
  },
  "python-tree-format": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319731"
    ],
    "summaries": [
      "python-tree-format fails to build with setuptools 74+"
    ]
  },
  "python-tvb-gdist": {
    "urls": [],
    "summaries": []
  },
  "python-twisted": {
    "urls": [],
    "summaries": []
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typeguard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328015"
    ],
    "summaries": [
      "python-typeguard fails to build with Python 3.14: typeguard.TypeCheckError: argument \"x\" (class dummymodule.DummyClass) is not a subclass of dummymodule.DummyClass && AssertionError: Regex pattern did not match."
    ]
  },
  "python-typing-extensions": {
    "urls": [],
    "summaries": []
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-urwid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
    ],
    "summaries": [
      "python-urwid fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-valkey": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326934"
    ],
    "summaries": [
      "python-valkey fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f7d711b5dd0>"
    ]
  },
  "python-virtualenv": {
    "urls": [],
    "summaries": []
  },
  "python-webscrapbook": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326915"
    ],
    "summaries": [
      "python-webscrapbook fails to build with Python 3.14: 60x AssertionError in the test suite"
    ]
  },
  "python-xunitparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319738"
    ],
    "summaries": [
      "python-xunitparser fails to build with setuptools 74+"
    ]
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-zc-lockfile": {
    "urls": [],
    "summaries": []
  },
  "python-zict": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328012"
    ],
    "summaries": [
      "python-zict fails to build with Python 3.14: test_stress_different_keys_threadsafe Timeout"
    ]
  },
  "python-zmq": {
    "urls": [],
    "summaries": []
  },
  "python-zope-deprecation": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319742"
    ],
    "summaries": [
      "python-zope-deprecation fails to build with setuptools 74+"
    ]
  },
  "python-zope-testing": {
    "urls": [],
    "summaries": []
  },
  "python-zope-testrunner": {
    "urls": [],
    "summaries": []
  },
  "python-zstandard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326925"
    ],
    "summaries": [
      "python-zstandard fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "realtime-tests": {
    "urls": [],
    "summaries": []
  },
  "rmol": {
    "urls": [],
    "summaries": []
  },
  "root": {
    "urls": [],
    "summaries": []
  },
  "satyr": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
    ],
    "summaries": [
      "satyr fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestDistances.test_distances_part_parallel.<locals>.do_test.<locals>.compute_part at 0x7f7f845f2560>"
    ]
  },
  "sentencepiece": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319749"
    ],
    "summaries": [
      "sentencepiece fails to build with setuptools 74+"
    ]
  },
  "sherlock-project": {
    "urls": [],
    "summaries": []
  },
  "strongswan": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332864"
    ],
    "summaries": [
      "strongswan-5.9.14-5.fc42 FTBFS: strongswan-5.9.14/missing: line 81: aclocal-1.16: command not found"
    ]
  },
  "syncplay": {
    "urls": [],
    "summaries": []
  },
  "trademgen": {
    "urls": [],
    "summaries": []
  },
  "urh": {
    "urls": [],
    "summaries": []
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "vtk": {
    "urls": [],
    "summaries": []
  },
  "weasyprint": {
    "urls": [],
    "summaries": []
  },
  "xpra": {
    "urls": [],
    "summaries": []
  },
  "yamllint": {
    "urls": [],
    "summaries": []
  }
}