{
  "alot": {
    "urls": [],
    "summaries": []
  },
  "ara": {
    "urls": [],
    "summaries": []
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "brltty": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328699"
    ],
    "summaries": [
      "brltty: FTBFS in Fedora Rawhide: error: File not found: /builddir/build/BUILD/brltty-6.7-build/BUILDROOT/usr/lib64/tcl8.6/brlapi-0.8.6"
    ]
  },
  "chirp": {
    "urls": [],
    "summaries": []
  },
  "did": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328006"
    ],
    "summaries": [
      "did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'"
    ]
  },
  "dlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328014"
    ],
    "summaries": [
      "dlib fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "dnf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323186"
    ],
    "summaries": [
      "dnf fails to build with Python 3.14: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "grammalecte": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319629"
    ],
    "summaries": [
      "grammalecte fails to build with setuptools 74+"
    ]
  },
  "hivex": {
    "urls": [],
    "summaries": []
  },
  "jc": {
    "urls": [],
    "summaries": []
  },
  "kicad": {
    "urls": [],
    "summaries": []
  },
  "lammps": {
    "urls": [],
    "summaries": []
  },
  "lasso": {
    "urls": [],
    "summaries": []
  },
  "libgpiod": {
    "urls": [],
    "summaries": []
  },
  "libnvme": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325194"
    ],
    "summaries": [
      "libnvme fails to build with Python 3.14: /usr/include/python3.14/pyport.h:629:35: error: missing ')' after \"__has_attribute\""
    ]
  },
  "libselinux": {
    "urls": [],
    "summaries": []
  },
  "libsemanage": {
    "urls": [],
    "summaries": []
  },
  "link-grammar": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2329827"
    ],
    "summaries": [
      "link-grammar-5.12.3-10.fc42 FTBFS:File not found: /builddir/build/BUILD/link-grammar-5.12.3-build/BUILDROOT/usr/lib64/liblink-grammar-java.so.5*"
    ]
  },
  "linode-cli": {
    "urls": [],
    "summaries": []
  },
  "mopidy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328700"
    ],
    "summaries": [
      "mopidy fails to build with Python 3.14: AssertionError: expected call not found"
    ]
  },
  "nemo-extensions": {
    "urls": [],
    "summaries": []
  },
  "openmeeg": {
    "urls": [],
    "summaries": []
  },
  "openvswitch": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328018"
    ],
    "summaries": [
      "openvswitch fails to build with Python 3.14: 3 tests failure"
    ]
  },
  "pcs": {
    "urls": [],
    "summaries": []
  },
  "policycoreutils": {
    "urls": [],
    "summaries": []
  },
  "postgresql17": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327967"
    ],
    "summaries": [
      "postgresql17 fails to build with Python 3.14: jsonb_jsonpath fails: - \"12:34:56-07:00\" != + \"12:34:56-08:00\""
    ]
  },
  "protobuf": {
    "urls": [],
    "summaries": []
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pygsl": {
    "urls": [],
    "summaries": []
  },
  "pyproj": {
    "urls": [],
    "summaries": []
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-APScheduler": {
    "urls": [],
    "summaries": []
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-anyio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328710"
    ],
    "summaries": [
      "python-anyio fails to build with Python 3.14: AttributeError: '_UnixDefaultEventLoopPolicy' object has no attribute 'get_child_watcher' && TypeError: PurePath.relative_to() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-argcomplete": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328704"
    ],
    "summaries": [
      "python-argcomplete fails to build with Python 3.14: Many test failures"
    ]
  },
  "python-astor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322712"
    ],
    "summaries": [
      "python-astor fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Num' / 'Str'"
    ]
  },
  "python-astroid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
    ],
    "summaries": [
      "python-astroid fails to build with Python 3.14: astroid.exceptions.InferenceError: StopIteration raised without any error information."
    ]
  },
  "python-async-lru": {
    "urls": [],
    "summaries": []
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-autocommand": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
    ],
    "summaries": [
      "python-autocommand fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-awscrt": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322714"
    ],
    "summaries": [
      "python-awscrt fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'collections.abc'"
    ]
  },
  "python-backrefs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325184"
    ],
    "summaries": [
      "python-backrefs fails to build with Python 3.14: Failed to acquire all needed Unicode files!"
    ]
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-binaryornot": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319640"
    ],
    "summaries": [
      "python-binaryornot fails to build with setuptools 74+"
    ]
  },
  "python-bowler": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328013"
    ],
    "summaries": [
      "python-bowler fails to build with Python 3.14: test_run_bowler_modifier_ferries_exception: AssertionError: AssertionError not raised by <lambda>"
    ]
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-cccolutils": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319642"
    ],
    "summaries": [
      "python-cccolutils fails to build with setuptools 74+"
    ]
  },
  "python-chameleon": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322715"
    ],
    "summaries": [
      "python-chameleon fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-cloudpickle": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328024"
    ],
    "summaries": [
      "python-cloudpickle fails to build with Python 3.14: CloudPickleFileTests.test_empty_file: RecursionError: maximum recursion depth exceeded in comparison"
    ]
  },
  "python-cmd2": {
    "urls": [],
    "summaries": []
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-commoncode": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325197"
    ],
    "summaries": [
      "python-commoncode fails to build with Python 3.14: tarfile.SpecialFileError: '6-FIFOTYPE' is a special file"
    ]
  },
  "python-confuse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
    ],
    "summaries": [
      "python-confuse fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-cramjam": {
    "urls": [],
    "summaries": []
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-cysignals": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325457"
    ],
    "summaries": [
      "python-cysignals fails to build with Python 3.14: Doctest src/cysignals/pselect.pyx terminated. Timeout limit exceeded (>2400s)"
    ]
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-dill": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323157"
    ],
    "summaries": [
      "python-dill fails to build with Python 3.14: TypeError: _Pickler._batch_setitems() missing 1 required positional argument: 'obj'"
    ]
  },
  "python-django-allauth": {
    "urls": [],
    "summaries": []
  },
  "python-django-compressor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322719"
    ],
    "summaries": [
      "python-django-compressor fails to build with Python 3.14: 'Constant' object has no attribute 's'"
    ]
  },
  "python-django-contrib-comments": {
    "urls": [],
    "summaries": []
  },
  "python-django-debreach": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328003"
    ],
    "summaries": [
      "python-django-debreach fails to build with Python 3.14: AttributeError: 'super' object has no attribute 'dicts' and no __dict__ for setting new attributes"
    ]
  },
  "python-django-filter": {
    "urls": [],
    "summaries": []
  },
  "python-django-mailman3": {
    "urls": [],
    "summaries": []
  },
  "python-djangoql": {
    "urls": [],
    "summaries": []
  },
  "python-docstring-parser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325441"
    ],
    "summaries": [
      "python-docstring-parser fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'NameConstant'"
    ]
  },
  "python-drgn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325185"
    ],
    "summaries": [
      "python-drgn fails to build with Python 3.14: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-engineio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327989"
    ],
    "summaries": [
      "python-engineio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-epub": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319654"
    ],
    "summaries": [
      "python-epub fails to build with setuptools 74+"
    ]
  },
  "python-etcd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
    ],
    "summaries": [
      "python-etcd fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestWatch.test_watch_indexed_generator.<locals>.watch_value at 0x7f0d39f71dd0>"
    ]
  },
  "python-events": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319655"
    ],
    "summaries": [
      "python-events fails to build with setuptools 74+"
    ]
  },
  "python-flask": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327965"
    ],
    "summaries": [
      "python-flask fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-flufl-i18n": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319659"
    ],
    "summaries": [
      "python-flufl-i18n fails to build with setuptools 74+"
    ]
  },
  "python-freecell_solver": {
    "urls": [],
    "summaries": []
  },
  "python-genty": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319661"
    ],
    "summaries": [
      "python-genty fails to build with setuptools 74+: uses removed setup.py test"
    ]
  },
  "python-giacpy": {
    "urls": [],
    "summaries": []
  },
  "python-gunicorn": {
    "urls": [],
    "summaries": []
  },
  "python-h2": {
    "urls": [],
    "summaries": []
  },
  "python-h5netcdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325222"
    ],
    "summaries": [
      "python-h5netcdf fails to build with Python 3.14: test_no_circular_references: AssertionError"
    ]
  },
  "python-img2pdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328707"
    ],
    "summaries": [
      "python-img2pdf fails to build in rawhide: 48 AssertionErrors"
    ]
  },
  "python-iniparse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
    ],
    "summaries": [
      "python-iniparse fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestIni.test_queue.<locals>.getxy at 0x7f86659a7740>"
    ]
  },
  "python-inject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
    ],
    "summaries": [
      "python-inject fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-inkex": {
    "urls": [],
    "summaries": []
  },
  "python-irc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
    ],
    "summaries": [
      "python-irc fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-jack-client": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319666"
    ],
    "summaries": [
      "python-jack-client fails to build with setuptools 74+"
    ]
  },
  "python-jcconv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319667"
    ],
    "summaries": [
      "python-jcconv fails to build with setuptools 74+"
    ]
  },
  "python-jeepney": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327982"
    ],
    "summaries": [
      "python-jeepney fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-jiter": {
    "urls": [],
    "summaries": []
  },
  "python-josepy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323171"
    ],
    "summaries": [
      "python-josepy fails to build with Python 3.14: 6x ValueError: Field `alg` in JSONObject `Header` has no type annotation."
    ]
  },
  "python-klusta": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319674"
    ],
    "summaries": [
      "python-klusta fails to build with setuptools 74+"
    ]
  },
  "python-libarchive-c": {
    "urls": [],
    "summaries": []
  },
  "python-libcst": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328019"
    ],
    "summaries": [
      "python-libcst fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-matplotlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328713"
    ],
    "summaries": [
      "python-matplotlib fails to build with Python 3.14: RecursionError: maximum recursion depth exceeded"
    ]
  },
  "python-mccabe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328016"
    ],
    "summaries": [
      "python-mccabe fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-msgspec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325169"
    ],
    "summaries": [
      "python-msgspec fails to build with Python 3.14: error: \u2018_Py_IMMORTAL_REFCNT\u2019 undeclared here"
    ]
  },
  "python-neovim": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326224"
    ],
    "summaries": [
      "python-neovim fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'get_child_watcher'"
    ]
  },
  "python-nose": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323163"
    ],
    "summaries": [
      "python-nose fails to build with Python 3.14: multiple AssertionErrors related to timeouts in test outputs"
    ]
  },
  "python-openidc-client": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319685"
    ],
    "summaries": [
      "python-openidc-client fails to build with setuptools 74+"
    ]
  },
  "python-orjson": {
    "urls": [],
    "summaries": []
  },
  "python-oscrypto": {
    "urls": [],
    "summaries": []
  },
  "python-parsel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319689"
    ],
    "summaries": [
      "python-parsel fails to build with setuptools 74+"
    ]
  },
  "python-pdfkit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319690"
    ],
    "summaries": [
      "python-pdfkit fails to build with setuptools 74+"
    ]
  },
  "python-pexpect": {
    "urls": [],
    "summaries": []
  },
  "python-precis_i18n": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325183"
    ],
    "summaries": [
      "python-precis_i18n fails to build with Python 3.14: FileNotFoundError: [Errno 2] No such file or directory: '/builddir/build/BUILD/python-precis_i18n-1.1.0-build/precis_i18n-1.1.0/test/derived-props-16.0.txt'"
    ]
  },
  "python-pulp-glue": {
    "urls": [],
    "summaries": []
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pyclipper": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319696"
    ],
    "summaries": [
      "python-pyclipper fails to build with setuptools 74+"
    ]
  },
  "python-pydantic-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
    ],
    "summaries": [
      "python-pydantic-core fails to build with Python 3.14: AssertionError: Regex pattern did not match. + AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-pydispatcher": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319697"
    ],
    "summaries": [
      "python-pydispatcher fails to build with setuptools 74+"
    ]
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pygit2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328023"
    ],
    "summaries": [
      "python-pygit2 fails to build with Python 3.14: TypeError: 'GenericIterator' object is not iterable"
    ]
  },
  "python-pymdown-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325198"
    ],
    "summaries": [
      "python-pymdown-extensions fails to build with Python 3.14: TestWindowsAbsFileScheme.test_windows_root_conversion: AssertionError"
    ]
  },
  "python-pymediainfo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319700"
    ],
    "summaries": [
      "python-pymediainfo fails to build with setuptools 74+"
    ]
  },
  "python-pymeeus": {
    "urls": [],
    "summaries": []
  },
  "python-pymongo": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid_sawing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319702"
    ],
    "summaries": [
      "python-pyramid_sawing fails to build with setuptools 74+"
    ]
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pytaglib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319705"
    ],
    "summaries": [
      "python-pytaglib fails to build with setuptools 74+"
    ]
  },
  "python-pytesseract": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-asyncio": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-django": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-flakes": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319708"
    ],
    "summaries": [
      "python-pytest-flakes fails to build with setuptools 74+"
    ]
  },
  "python-pytest-rerunfailures": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327998"
    ],
    "summaries": [
      "python-pytest-rerunfailures fails to build with Python 3.14: remains unmatched: 'session teardown'"
    ]
  },
  "python-pytest-runner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319709"
    ],
    "summaries": [
      "python-pytest-runner fails to build with setuptools 74+"
    ]
  },
  "python-pytest-split": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325447"
    ],
    "summaries": [
      "python-pytest-split fails to build with Python 3.14: TestRaisesUsageErrors.test_returns_nonzero_when_invalid_algorithm_name:  AssertionError"
    ]
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-pyvlx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
    ],
    "summaries": [
      "python-pyvlx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-reactivex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
    ],
    "summaries": [
      "python-reactivex fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-remoto": {
    "urls": [],
    "summaries": []
  },
  "python-reportlab": {
    "urls": [],
    "summaries": []
  },
  "python-repoze-lru": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319711"
    ],
    "summaries": [
      "python-repoze-lru fails to build with setuptools 74+"
    ]
  },
  "python-requests-toolbelt": {
    "urls": [],
    "summaries": []
  },
  "python-resumable-urlretrieve": {
    "urls": [],
    "summaries": []
  },
  "python-rmtest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319712"
    ],
    "summaries": [
      "python-rmtest fails to build with setuptools 74+"
    ]
  },
  "python-rpmfluff": {
    "urls": [],
    "summaries": []
  },
  "python-rq": {
    "urls": [],
    "summaries": []
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-s3transfer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326933"
    ],
    "summaries": [
      "python-s3transfer fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <class 'tests.unit.test_compat.TestBaseManager.create_pid_manager.<locals>.PIDManager'>"
    ]
  },
  "python-scantree": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328021"
    ],
    "summaries": [
      "python-scantree fails to build with Python 3.14: AssertionError: assert 1.2218716144561768 < (2.0 / 2)"
    ]
  },
  "python-scp": {
    "urls": [],
    "summaries": []
  },
  "python-serpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319716"
    ],
    "summaries": [
      "python-serpy fails to build with setuptools 74+"
    ]
  },
  "python-sh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327986"
    ],
    "summaries": [
      "python-sh fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-simplegeneric": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319717"
    ],
    "summaries": [
      "python-simplegeneric fails to build with setuptools 74+: uses removed setup.py test"
    ]
  },
  "python-singledispatch": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319718"
    ],
    "summaries": [
      "python-singledispatch fails to build with setuptools 74+"
    ]
  },
  "python-social-auth-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328010"
    ],
    "summaries": [
      "python-social-auth-core fails to build with Python 3.14: 'SSLContext' object has no attribute 'close'"
    ]
  },
  "python-sphinxcontrib-autoprogram": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319720"
    ],
    "summaries": [
      "python-sphinxcontrib-autoprogram fails to build with setuptools 74+"
    ]
  },
  "python-sphinxcontrib-blockdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-seqdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy1.4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
    ],
    "summaries": [
      "python-sqlalchemy1.4 fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-surt": {
    "urls": [],
    "summaries": []
  },
  "python-tenacity": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
    ],
    "summaries": [
      "python-tenacity fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-terminado": {
    "urls": [],
    "summaries": []
  },
  "python-tgscheduler": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319728"
    ],
    "summaries": [
      "python-tgscheduler fails to build with setuptools 74+"
    ]
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-tornado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
    ],
    "summaries": [
      "python-tornado fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-tpm2-pytss": {
    "urls": [],
    "summaries": []
  },
  "python-tree-format": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319731"
    ],
    "summaries": [
      "python-tree-format fails to build with setuptools 74+"
    ]
  },
  "python-twisted": {
    "urls": [],
    "summaries": []
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typeguard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328015"
    ],
    "summaries": [
      "python-typeguard fails to build with Python 3.14: typeguard.TypeCheckError: argument \"x\" (class dummymodule.DummyClass) is not a subclass of dummymodule.DummyClass && AssertionError: Regex pattern did not match."
    ]
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-urwid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
    ],
    "summaries": [
      "python-urwid fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-valkey": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326934"
    ],
    "summaries": [
      "python-valkey fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f7d711b5dd0>"
    ]
  },
  "python-webscrapbook": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326915"
    ],
    "summaries": [
      "python-webscrapbook fails to build with Python 3.14: 60x AssertionError in the test suite"
    ]
  },
  "python-xunitparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319738"
    ],
    "summaries": [
      "python-xunitparser fails to build with setuptools 74+"
    ]
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-zc-lockfile": {
    "urls": [],
    "summaries": []
  },
  "python-zict": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328012"
    ],
    "summaries": [
      "python-zict fails to build with Python 3.14: test_stress_different_keys_threadsafe Timeout"
    ]
  },
  "python-zope-deprecation": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319742"
    ],
    "summaries": [
      "python-zope-deprecation fails to build with setuptools 74+"
    ]
  },
  "python-zope-testing": {
    "urls": [],
    "summaries": []
  },
  "python-zstandard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326925"
    ],
    "summaries": [
      "python-zstandard fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "realtime-tests": {
    "urls": [],
    "summaries": []
  },
  "rmol": {
    "urls": [],
    "summaries": []
  },
  "rrdtool": {
    "urls": [],
    "summaries": []
  },
  "ruff": {
    "urls": [],
    "summaries": []
  },
  "satyr": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
    ],
    "summaries": [
      "satyr fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestDistances.test_distances_part_parallel.<locals>.do_test.<locals>.compute_part at 0x7f7f845f2560>"
    ]
  },
  "sentencepiece": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319749"
    ],
    "summaries": [
      "sentencepiece fails to build with setuptools 74+"
    ]
  },
  "syncplay": {
    "urls": [],
    "summaries": []
  },
  "trademgen": {
    "urls": [],
    "summaries": []
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "watchman": {
    "urls": [],
    "summaries": []
  },
  "xpra": {
    "urls": [],
    "summaries": []
  }
}