{
  "APLpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384432",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371672"
    ],
    "summaries": [
      "APLpy: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-APLpy"
    ]
  },
  "Mayavi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351390"
    ],
    "summaries": [
      "Mayavi fails to build with Python 3.14: TestMayaviGarbageCollection.test_mlab_scene_model_with_gui: IndexError: list index out of range"
    ]
  },
  "ara": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331346"
    ],
    "summaries": [
      "ara fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "asv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2367256"
    ],
    "summaries": [
      "asv fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "bandit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351393"
    ],
    "summaries": [
      "bandit fails to build with Python 3.14: TypeError: Error: Str is not a valid node type in AST"
    ]
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "bout++": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384484",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371685"
    ],
    "summaries": [
      "bout++: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-bout++-mpich, python3-bout++-openmpi"
    ]
  },
  "buildbot": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384488",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371686"
    ],
    "summaries": [
      "buildbot: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: buildbot-master, buildbot-master-container, buildbot-master-ec2, buildbot-master-libvirt, buildbot-master-openstack, buildbot-worker, buildbot-www"
    ]
  },
  "buildstream": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384490",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371687"
    ],
    "summaries": [
      "buildstream: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: buildstream"
    ]
  },
  "cantera": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384495",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371689"
    ],
    "summaries": [
      "cantera: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-cantera"
    ]
  },
  "cfn-lint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384496",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371692"
    ],
    "summaries": [
      "cfn-lint: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: cfn-lint+full, cfn-lint+graph, cfn-lint+junit, cfn-lint+sarif, cfn-lint"
    ]
  },
  "cjdns": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339969"
    ],
    "summaries": [
      "cjdns: FTBFS in Fedora rawhide/f42"
    ]
  },
  "conda-build": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2356162"
    ],
    "summaries": [
      "conda-build fails to build with Python 3.14: TypeError: _WorkItem.__init__() takes 3 positional arguments but 5 were given"
    ]
  },
  "copr-backend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351386"
    ],
    "summaries": [
      "copr-backend fails to build with Python 3.14: TestActionWorkerManager.test_add_task_for_running_worker: TypeError: cannot pickle 'itertools.count' object"
    ]
  },
  "distro-info": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384546",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371705"
    ],
    "summaries": [
      "distro-info: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-distro-info"
    ]
  },
  "dlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366197"
    ],
    "summaries": [
      "dlib fails to build with Python 3.14: AssertionError in tests checking refcounting"
    ]
  },
  "dolfin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2384554",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371707"
    ],
    "summaries": [
      "dolfin: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-dolfin"
    ]
  },
  "libpeas": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385122",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366247"
    ],
    "summaries": [
      "libpeas: FTBFS in Fedora rawhide/f43",
      "libpeas fails to build with Python 3.14: test-extension-py  TIMEOUT"
    ]
  },
  "linode-cli": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2368974"
    ],
    "summaries": [
      "linode-cli fails to build with Python 3.14: The current dist-git state is unbuildable"
    ]
  },
  "mailman3-fedmsg-plugin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385168",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2304216"
    ],
    "summaries": [
      "mailman3-fedmsg-plugin: FTBFS in Fedora rawhide/f43",
      "F41FailsToInstall: python3-mailman3-fedmsg-plugin"
    ]
  },
  "matrix-synapse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385171",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371743"
    ],
    "summaries": [
      "matrix-synapse: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: Multiple packages built from matrix-synapse"
    ]
  },
  "mirrormanager2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385192",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2347031"
    ],
    "summaries": [
      "mirrormanager2: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: mirrormanager2"
    ]
  },
  "ocrmypdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2357508"
    ],
    "summaries": [
      "ocrmypdf fails to build with Python 3.14: multiprocessing.Process now starts with forkserver method instead of fork, causing pickling error"
    ]
  },
  "openms": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385366",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371763"
    ],
    "summaries": [
      "openms: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-openms"
    ]
  },
  "paraview": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385379"
    ],
    "summaries": [
      "paraview: FTBFS in Fedora rawhide/f43"
    ]
  },
  "patool": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366470"
    ],
    "summaries": [
      "patool fails to build with Python 3.14: Codec Load Error: /usr/bin/7z.so : errno=25 : Inappropriate ioctl for device"
    ]
  },
  "psi4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385428",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371776"
    ],
    "summaries": [
      "psi4: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: psi4"
    ]
  },
  "pylint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2368703"
    ],
    "summaries": [
      "pylint fails to build with Python 3.14: AssertionError tests/test_functional.py::test_functional"
    ]
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pysubnettree": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366464"
    ],
    "summaries": [
      "pysubnettree fails to build with Python 3.14/Fedora Rawhide: error: too many arguments to function \u2018func\u2019; expected 0, have 1"
    ]
  },
  "python-aiokafka": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2346517"
    ],
    "summaries": [
      "python-aiokafka fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-arm-preprocessing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385433",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371796"
    ],
    "summaries": [
      "python-arm-preprocessing: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-arm-preprocessing"
    ]
  },
  "python-arviz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385434",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371797"
    ],
    "summaries": [
      "python-arviz: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-arviz"
    ]
  },
  "python-autobahn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385437",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371802"
    ],
    "summaries": [
      "python-autobahn: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-autobahn+twisted, python3-autobahn"
    ]
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-aws-sam-translator": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2353126"
    ],
    "summaries": [
      "python-aws-sam-translator fails to build with Python 3.14: 77 test failures, 4 error"
    ]
  },
  "python-beancount": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2359530"
    ],
    "summaries": [
      "python-beancount fails to build with Python 3.14: TestReferenceCounting and TestLexer fail with AssertionError"
    ]
  },
  "python-beangulp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385439",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371815"
    ],
    "summaries": [
      "python-beangulp: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-beangulp"
    ]
  },
  "python-beanprice": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385440",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371816"
    ],
    "summaries": [
      "python-beanprice: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-beanprice"
    ]
  },
  "python-bluepyopt": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385444",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371820"
    ],
    "summaries": [
      "python-bluepyopt: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-bluepyopt"
    ]
  },
  "python-catkin_tools": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2329848"
    ],
    "summaries": [
      "python-catkin_tools fails to build with sphinx 8.x:  ERROR: Invalid value `None` in intersphinx_mapping['http://docs.python.org/']."
    ]
  },
  "python-ccdproc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385447",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371827"
    ],
    "summaries": [
      "python-ccdproc: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-ccdproc"
    ]
  },
  "python-chalice": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342568"
    ],
    "summaries": [
      "python-chalice fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-colcon-meson": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2368744"
    ],
    "summaries": [
      "python-colcon-meson fails to build with Python 3.14: test_capital_case: TypeError: InterpreterBase.__init__() missing 2 required positional arguments: 'subproject_dir' and 'env'"
    ]
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-daphne": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385451",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371851"
    ],
    "summaries": [
      "python-daphne: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-daphne"
    ]
  },
  "python-dask": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371852"
    ],
    "summaries": [
      "F43FailsToInstall: python3-dask+array, python3-dask+bag, python3-dask+dataframe, python3-dask+delayed, python3-dask+distributed, python3-dask"
    ]
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-datalad": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385452",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371854"
    ],
    "summaries": [
      "python-datalad: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-datalad"
    ]
  },
  "python-distributed": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385458",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371862"
    ],
    "summaries": [
      "python-distributed: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-distributed"
    ]
  },
  "python-django-cacheops": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385459",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371864"
    ],
    "summaries": [
      "python-django-cacheops: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-django-cacheops"
    ]
  },
  "python-django-contrib-comments": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366520"
    ],
    "summaries": [
      "python-django-contrib-comments fails to build with Python 3.14: ImportError: Module \"django.contrib.auth.hashers\" does not define a \"UnsaltedMD5PasswordHasher\" attribute/class"
    ]
  },
  "python-earthpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385460",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371875"
    ],
    "summaries": [
      "python-earthpy: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-earthpy"
    ]
  },
  "python-einops": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385461",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371876"
    ],
    "summaries": [
      "python-einops: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-einops"
    ]
  },
  "python-elastic-transport": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385462",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371877"
    ],
    "summaries": [
      "python-elastic-transport: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-elastic-transport"
    ]
  },
  "python-elasticsearch": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385463",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371878"
    ],
    "summaries": [
      "python-elasticsearch: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-elasticsearch"
    ]
  },
  "python-esbonio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385465",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371883"
    ],
    "summaries": [
      "python-esbonio: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-esbonio+dev, python3-esbonio+typecheck, python3-esbonio"
    ]
  },
  "python-eventlet": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385466",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371893"
    ],
    "summaries": [
      "python-eventlet: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-eventlet"
    ]
  },
  "python-ffc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385467",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371902"
    ],
    "summaries": [
      "python-ffc: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-ffc"
    ]
  },
  "python-fiat": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385468",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371903"
    ],
    "summaries": [
      "python-fiat: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-fiat"
    ]
  },
  "python-flake8-comprehensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2351385"
    ],
    "summaries": [
      "python-flake8-comprehensions fails to build with Python 3.14: Unnecessary reversed call around sorted() in 10 tests"
    ]
  },
  "python-fsleyes": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385470",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371912"
    ],
    "summaries": [
      "python-fsleyes: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-fsleyes"
    ]
  },
  "python-fsleyes-props": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385472",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371913"
    ],
    "summaries": [
      "python-fsleyes-props: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-fsleyes-props"
    ]
  },
  "python-fsleyes-widgets": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336911"
    ],
    "summaries": [
      "python-fsleyes-widgets fails to build with Python 3.14: AssertionError: assert 'file:/home/b...htmlfile.html' == 'file:///home...htmlfile.html'"
    ]
  },
  "python-gphoto2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366465"
    ],
    "summaries": [
      "python-gphoto2 fails to build with Python 3.14: ModuleNotFoundError: No module named 'distutils.command.upload'"
    ]
  },
  "python-howdoi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342558"
    ],
    "summaries": [
      "python-howdoi fails to build with Python 3.14: AssertionError: 'ERROR: Unable to reach google. Do you need to use a proxy? + json.decoder.JSONDecodeError"
    ]
  },
  "python-janus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385476",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371953"
    ],
    "summaries": [
      "python-janus: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-janus"
    ]
  },
  "python-jsons": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385477",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371957"
    ],
    "summaries": [
      "python-jsons: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-jsons"
    ]
  },
  "python-libpysal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385481",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371962"
    ],
    "summaries": [
      "python-libpysal: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-libpysal"
    ]
  },
  "python-lion-pytorch": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385482",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371963"
    ],
    "summaries": [
      "python-lion-pytorch: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-lion-pytorch"
    ]
  },
  "python-mapclassify": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385485",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371972"
    ],
    "summaries": [
      "python-mapclassify: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-mapclassify"
    ]
  },
  "python-markups": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366489"
    ],
    "summaries": [
      "python-markups fails to build with Python 3.14: AssertionError in test_get_pygments_stylesheet"
    ]
  },
  "python-mkapi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342559"
    ],
    "summaries": [
      "python-mkapi fails to build with Python 3.14: Expected: [None, <ast.Constant object at 0x...>, <ast.Constant object at 0x...>] Got: [None, Constant(value=2, kind=None), Constant(value=3, kind=None)]"
    ]
  },
  "python-mkdocs-rss-plugin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385490",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371984"
    ],
    "summaries": [
      "python-mkdocs-rss-plugin: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-mkdocs-rss-plugin"
    ]
  },
  "python-mne": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385491",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371986"
    ],
    "summaries": [
      "python-mne: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-mne"
    ]
  },
  "python-mne-bids": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385492",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371987"
    ],
    "summaries": [
      "python-mne-bids: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-mne-bids+full, python3-mne-bids"
    ]
  },
  "python-neatdend": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341170"
    ],
    "summaries": [
      "python-neatdend: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-network-runner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385495",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371996"
    ],
    "summaries": [
      "python-network-runner: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-network-runner"
    ]
  },
  "python-neurom": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385497",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371997"
    ],
    "summaries": [
      "python-neurom: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-neurom+plotly, python3-neurom"
    ]
  },
  "python-niaarm": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385498",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2371999"
    ],
    "summaries": [
      "python-niaarm: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-niaarm"
    ]
  },
  "python-niaarmts": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2369421"
    ],
    "summaries": [
      "python-niaarmts fails to build with Python 3.14: ERROR: Package 'niaarmts' requires a different Python: 3.14.0 not in '<3.14,>=3.11'"
    ]
  },
  "python-nilearn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385500",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372003"
    ],
    "summaries": [
      "python-nilearn: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-nilearn"
    ]
  },
  "python-nipype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385502",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372004"
    ],
    "summaries": [
      "python-nipype: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-nipype+data, python3-nipype+duecredit, python3-nipype+nipy, python3-nipype+pybids, python3-nipype+ssh, python3-nipype"
    ]
  },
  "python-octave-kernel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341176"
    ],
    "summaries": [
      "python-octave-kernel: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-optking": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385505",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372017"
    ],
    "summaries": [
      "python-optking: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-optking"
    ]
  },
  "python-oslo-middleware": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385506",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2347032"
    ],
    "summaries": [
      "python-oslo-middleware: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-oslo-middleware"
    ]
  },
  "python-pamela": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366474"
    ],
    "summaries": [
      "python-pamela fails to build with Python 3.14: pamela.PAMError: [PAM Error 26] Critical error - immediate abort"
    ]
  },
  "python-pandas-flavor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385508",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372024"
    ],
    "summaries": [
      "python-pandas-flavor: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pandas-flavor"
    ]
  },
  "python-pingouin": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385509",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372029"
    ],
    "summaries": [
      "python-pingouin: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pingouin"
    ]
  },
  "python-pkginfo2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366490"
    ],
    "summaries": [
      "python-pkginfo2: FTBFS in Fedora Rawhide: AssertionError: None != '30.0.0'"
    ]
  },
  "python-plotly": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385510",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372034"
    ],
    "summaries": [
      "python-plotly: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-plotly"
    ]
  },
  "python-plotnine": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385511",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372035"
    ],
    "summaries": [
      "python-plotnine: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-plotnine+extra, python3-plotnine"
    ]
  },
  "python-pocketlint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385512",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372037"
    ],
    "summaries": [
      "python-pocketlint: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pocketlint"
    ]
  },
  "python-praw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342562"
    ],
    "summaries": [
      "python-praw fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-pybids": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385515",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372050"
    ],
    "summaries": [
      "python-pybids: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pybids+plotting, python3-pybids+test, python3-pybids+tests, python3-pybids"
    ]
  },
  "python-pybv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385516",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372051"
    ],
    "summaries": [
      "python-pybv: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pybv"
    ]
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pycomfoair": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385517",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372053"
    ],
    "summaries": [
      "python-pycomfoair: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pycomfoair"
    ]
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pylint-venv": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385521",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372061"
    ],
    "summaries": [
      "python-pylint-venv: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pylint-venv"
    ]
  },
  "python-pyopencl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341190"
    ],
    "summaries": [
      "python-pyopencl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyphi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385522",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372070"
    ],
    "summaries": [
      "python-pyphi: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pyphi"
    ]
  },
  "python-pysaml2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385525",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372073"
    ],
    "summaries": [
      "python-pysaml2: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pysaml2"
    ]
  },
  "python-pyshtools": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385526",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372075"
    ],
    "summaries": [
      "python-pyshtools: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-pyshtools+cartopy, python3-pyshtools+ducc, python3-pyshtools"
    ]
  },
  "python-pytest-twisted": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2368594"
    ],
    "summaries": [
      "python-pytest-twisted fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-qcelemental": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385528",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372089"
    ],
    "summaries": [
      "python-qcelemental: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-qcelemental"
    ]
  },
  "python-qcengine": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385529",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372090"
    ],
    "summaries": [
      "python-qcengine: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-qcengine"
    ]
  },
  "python-qemu-qmp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385531",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372091"
    ],
    "summaries": [
      "python-qemu-qmp: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-qemu-qmp"
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-remoto": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366491"
    ],
    "summaries": [
      "python-remoto fails to build with Python 3.14: AttributeError: 'TestRemoteError' object has no attribute 'traceback'"
    ]
  },
  "python-reproject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385533",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372104"
    ],
    "summaries": [
      "python-reproject: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-reproject"
    ]
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-simframe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2352552"
    ],
    "summaries": [
      "python-simframe fails to build with Python 3.14: TypeError: cannot pickle 'itertools.cycle' object"
    ]
  },
  "python-snakemake-executor-plugin-azure-batch": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385536",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2363643"
    ],
    "summaries": [
      "python-snakemake-executor-plugin-azure-batch: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-snakemake-executor-plugin-azure-batch"
    ]
  },
  "python-sqlmodel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385537",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372150"
    ],
    "summaries": [
      "python-sqlmodel: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-sqlmodel, python3-sqlmodel-slim"
    ]
  },
  "python-steam": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385538",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372152"
    ],
    "summaries": [
      "python-steam: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-steam"
    ]
  },
  "python-taskflow": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385540",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372159"
    ],
    "summaries": [
      "python-taskflow: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-taskflow"
    ]
  },
  "python-tinygrad": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385541",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372162"
    ],
    "summaries": [
      "python-tinygrad: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-tinygrad"
    ]
  },
  "python-torch": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385542",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372164"
    ],
    "summaries": [
      "python-torch: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-torch"
    ]
  },
  "python-torchaudio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385543",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372165"
    ],
    "summaries": [
      "python-torchaudio: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-torchaudio"
    ]
  },
  "python-torchdata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385544",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372166"
    ],
    "summaries": [
      "python-torchdata: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-torchdata"
    ]
  },
  "python-torchdiffeq": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385545",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372167"
    ],
    "summaries": [
      "python-torchdiffeq: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-torchdiffeq"
    ]
  },
  "python-torchsde": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385546",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372168"
    ],
    "summaries": [
      "python-torchsde: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-torchsde"
    ]
  },
  "python-torchtext": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385547",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372169"
    ],
    "summaries": [
      "python-torchtext: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-torchtext"
    ]
  },
  "python-torchvision": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385548",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372170"
    ],
    "summaries": [
      "python-torchvision: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-torchvision"
    ]
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-typish": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385550",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372181"
    ],
    "summaries": [
      "python-typish: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-typish"
    ]
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-valkey": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2349444"
    ],
    "summaries": [
      "python-valkey fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f5aa68cddd0>"
    ]
  },
  "python-wxnatpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385552",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372198"
    ],
    "summaries": [
      "python-wxnatpy: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-wxnatpy"
    ]
  },
  "python-xarray": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385553",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372200"
    ],
    "summaries": [
      "python-xarray: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-xarray+io, python3-xarray"
    ]
  },
  "python-xarray-einstats": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385554",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372201"
    ],
    "summaries": [
      "python-xarray-einstats: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-xarray-einstats"
    ]
  },
  "python-xbout": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385555",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372202"
    ],
    "summaries": [
      "python-xbout: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-xbout"
    ]
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "qtile-extras": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385564",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372210"
    ],
    "summaries": [
      "qtile-extras: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: qtile-extras"
    ]
  },
  "retext": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385573",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372215"
    ],
    "summaries": [
      "retext: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: retext"
    ]
  },
  "rpm-head-signing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366308"
    ],
    "summaries": [
      "rpm-head-signing: FTBFS in Fedora Rawhide with RPM 6"
    ]
  },
  "scancode-toolkit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385618",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372219"
    ],
    "summaries": [
      "scancode-toolkit: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: scancode-toolkit"
    ]
  },
  "signon-glib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341348"
    ],
    "summaries": [
      "signon-glib: FTBFS in Fedora rawhide/f42"
    ]
  },
  "stats-collect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385638",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372225"
    ],
    "summaries": [
      "stats-collect: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: stats-collect"
    ]
  },
  "strongswan": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2368971"
    ],
    "summaries": [
      "strongswan: FTBFS in Fedora Rawhide: error: possibly undefined macro: AC_LIB_PREFIX"
    ]
  },
  "swift-lang": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385672",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341403"
    ],
    "summaries": [
      "swift-lang: FTBFS in Fedora rawhide/f43",
      "swift-lang: FTBFS in Fedora rawhide/f42"
    ]
  },
  "thonny": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385688",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372232"
    ],
    "summaries": [
      "thonny: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: thonny"
    ]
  },
  "tmt": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385701",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372233"
    ],
    "summaries": [
      "tmt: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: tmt+all, tmt+export-polarion, tmt+link-jira, tmt+provision-beaker, tmt+provision-bootc, tmt+provision-container, tmt+provision-virtual, tmt+report-junit, tmt+report-polarion, tmt+test-convert, tmt"
    ]
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "wult": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2385734",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2372241"
    ],
    "summaries": [
      "wult: FTBFS in Fedora rawhide/f43",
      "F43FailsToInstall: python3-wult"
    ]
  },
  "zeek": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2366467"
    ],
    "summaries": [
      "zeek fails to build in Fedora Rawhide: Could not find prerequisite package 'BIND'"
    ]
  }
}