{
  "ara": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331346"
    ],
    "summaries": [
      "ara fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "awscli2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336910"
    ],
    "summaries": [
      "awscli2 fails to build with Python 3.14: ValueError('badly formed help string'),  KeyError: 'PATH'"
    ]
  },
  "binwalk": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336914"
    ],
    "summaries": [
      "binwalk fails to build with Python 3.14: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'"
    ]
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "brial": {
    "urls": [],
    "summaries": []
  },
  "capstone": {
    "urls": [],
    "summaries": []
  },
  "ceph": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336913"
    ],
    "summaries": [
      "ceph fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "chirp": {
    "urls": [],
    "summaries": []
  },
  "cjdns": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339969"
    ],
    "summaries": [
      "cjdns: FTBFS in Fedora rawhide/f42"
    ]
  },
  "cockpit": {
    "urls": [],
    "summaries": []
  },
  "condor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339993"
    ],
    "summaries": [
      "condor: FTBFS in Fedora rawhide/f42"
    ]
  },
  "criu": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340011"
    ],
    "summaries": [
      "criu: FTBFS in Fedora rawhide/f42"
    ]
  },
  "cryptlib": {
    "urls": [],
    "summaries": []
  },
  "csdiff": {
    "urls": [],
    "summaries": []
  },
  "dee": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340038"
    ],
    "summaries": [
      "dee: FTBFS in Fedora rawhide/f42"
    ]
  },
  "diceware": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340075"
    ],
    "summaries": [
      "diceware: FTBFS in Fedora rawhide/f42"
    ]
  },
  "did": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328006"
    ],
    "summaries": [
      "did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'"
    ]
  },
  "dlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340079",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328014"
    ],
    "summaries": [
      "dlib: FTBFS in Fedora rawhide/f42",
      "dlib fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "dnsconfd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340084"
    ],
    "summaries": [
      "dnsconfd: FTBFS in Fedora rawhide/f42"
    ]
  },
  "elements-alexandria": {
    "urls": [],
    "summaries": []
  },
  "espresso": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340139"
    ],
    "summaries": [
      "espresso: FTBFS in Fedora rawhide/f42"
    ]
  },
  "gdb": {
    "urls": [],
    "summaries": []
  },
  "gdl": {
    "urls": [],
    "summaries": []
  },
  "gnofract4d": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339539"
    ],
    "summaries": [
      "gnofract4d fails to build with Python 3.14: AssertionError: 'ct_sin6 = (0.841471,-0)' != 'ct_sin6 = (0.841471,0)'"
    ]
  },
  "h5py": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339470"
    ],
    "summaries": [
      "h5py fails to build with Python 3.14: ResourceWarning: TestFileObj.test_TemporaryFile: Implicitly cleaning up <_TemporaryFileWrapper file=<_io.BufferedRandom name='/tmp/tmp8pqafmzv'>>"
    ]
  },
  "httpie": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340619"
    ],
    "summaries": [
      "httpie: FTBFS in Fedora rawhide/f42"
    ]
  },
  "ikiwiki": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340642"
    ],
    "summaries": [
      "ikiwiki: FTBFS in Fedora rawhide/f42"
    ]
  },
  "ipa-hcc": {
    "urls": [],
    "summaries": []
  },
  "jc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331343"
    ],
    "summaries": [
      "jc fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "jrnl": {
    "urls": [],
    "summaries": []
  },
  "kernel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340285"
    ],
    "summaries": [
      "kernel: FTBFS in Fedora rawhide/f42"
    ]
  },
  "khal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340695"
    ],
    "summaries": [
      "khal: FTBFS in Fedora rawhide/f42"
    ]
  },
  "kicad": {
    "urls": [],
    "summaries": []
  },
  "kiwi-boxed-plugin": {
    "urls": [],
    "summaries": []
  },
  "koji": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340700"
    ],
    "summaries": [
      "koji: FTBFS in Fedora rawhide/f42"
    ]
  },
  "lammps": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340706"
    ],
    "summaries": [
      "lammps: FTBFS in Fedora rawhide/f42"
    ]
  },
  "lasso": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340708"
    ],
    "summaries": [
      "lasso: FTBFS in Fedora rawhide/f42"
    ]
  },
  "libarcus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340716"
    ],
    "summaries": [
      "libarcus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "libarrow": {
    "urls": [],
    "summaries": []
  },
  "libixion": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340744"
    ],
    "summaries": [
      "libixion: FTBFS in Fedora rawhide/f42"
    ]
  },
  "libnvme": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325194"
    ],
    "summaries": [
      "libnvme fails to build with Python 3.14: /usr/include/python3.14/pyport.h:629:35: error: missing ')' after \"__has_attribute\""
    ]
  },
  "liborcus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341623"
    ],
    "summaries": [
      "liborcus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "libreoffice": {
    "urls": [],
    "summaries": []
  },
  "libsonata": {
    "urls": [],
    "summaries": []
  },
  "libtalloc": {
    "urls": [],
    "summaries": []
  },
  "libtdb": {
    "urls": [],
    "summaries": []
  },
  "libtevent": {
    "urls": [],
    "summaries": []
  },
  "llvm": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336915"
    ],
    "summaries": [
      "llvm fails to build with Python 3.14: tools/opt-viewer/suppress.test: AttributeError: type object 'Passed' has no attribute 'demangler_lock'"
    ]
  },
  "mathgl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340819"
    ],
    "summaries": [
      "mathgl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "morphio": {
    "urls": [],
    "summaries": []
  },
  "needrestart": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340913"
    ],
    "summaries": [
      "needrestart: FTBFS in Fedora rawhide/f42"
    ]
  },
  "netgen-mesher": {
    "urls": [],
    "summaries": []
  },
  "nvmetcli": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340947"
    ],
    "summaries": [
      "nvmetcli: FTBFS in Fedora rawhide/f42"
    ]
  },
  "nwchem": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340948"
    ],
    "summaries": [
      "nwchem: FTBFS in Fedora rawhide/f42"
    ]
  },
  "obs-studio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2340952"
    ],
    "summaries": [
      "obs-studio: FTBFS in Fedora rawhide/f42"
    ]
  },
  "onnx": {
    "urls": [],
    "summaries": []
  },
  "pcs": {
    "urls": [],
    "summaries": []
  },
  "plplot": {
    "urls": [],
    "summaries": []
  },
  "powerline": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336943"
    ],
    "summaries": [
      "powerline fails to build with Python 3.14: ValueError: argument groups cannot be nested"
    ]
  },
  "pybind11": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336889"
    ],
    "summaries": [
      "pybind11 fails to build with Python 3.14: AttributeError: 'pybind11_tests.pickling.PickleableWithDict' object has no attribute 'dynamic' + AssertionError"
    ]
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pychromecast": {
    "urls": [],
    "summaries": []
  },
  "pygame": {
    "urls": [],
    "summaries": []
  },
  "pygsl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341119"
    ],
    "summaries": [
      "pygsl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "pykka": {
    "urls": [],
    "summaries": []
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pysubnettree": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341123"
    ],
    "summaries": [
      "pysubnettree: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-TestSlide": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343971"
    ],
    "summaries": [
      "python-TestSlide fails to build with Python 3.14: ERROR collecting tests/mock_callable_testslide.py: RuntimeError: dictionary changed size during iteration"
    ]
  },
  "python-aioesphomeapi": {
    "urls": [],
    "summaries": []
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-alsaaudio": {
    "urls": [],
    "summaries": []
  },
  "python-anyio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328710"
    ],
    "summaries": [
      "python-anyio fails to build with Python 3.14: AttributeError: '_UnixDefaultEventLoopPolicy' object has no attribute 'get_child_watcher' && TypeError: PurePath.relative_to() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-apsw": {
    "urls": [],
    "summaries": []
  },
  "python-astroid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
    ],
    "summaries": [
      "python-astroid fails to build with Python 3.14: astroid.exceptions.InferenceError: StopIteration raised without any error information."
    ]
  },
  "python-astropy-iers-data": {
    "urls": [],
    "summaries": []
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-autocommand": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
    ],
    "summaries": [
      "python-autocommand fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341130",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado: FTBFS in Fedora rawhide/f42",
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-aw-qt": {
    "urls": [],
    "summaries": []
  },
  "python-backrefs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325184"
    ],
    "summaries": [
      "python-backrefs fails to build with Python 3.14: Failed to acquire all needed Unicode files!"
    ]
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341131",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype: FTBFS in Fedora rawhide/f42",
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-behave": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339094"
    ],
    "summaries": [
      "python-behave fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-blinker": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325193"
    ],
    "summaries": [
      "python-blinker fails to build with Python 3.14: pluggy.PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown."
    ]
  },
  "python-boto3": {
    "urls": [],
    "summaries": []
  },
  "python-botocore": {
    "urls": [],
    "summaries": []
  },
  "python-breathe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341133"
    ],
    "summaries": [
      "python-breathe: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-catkin_tools": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341134"
    ],
    "summaries": [
      "python-catkin_tools: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-cattrs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343916"
    ],
    "summaries": [
      "python-cattrs fails to build with Python 3.14: TypeError: <class 'tests.strategies.test_include_subclasses.GrandChild'> has no usable non-default attributes"
    ]
  },
  "python-chalice": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342568"
    ],
    "summaries": [
      "python-chalice fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-colcon-cmake": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339465"
    ],
    "summaries": [
      "python-colcon-cmake fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-colcon-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339464"
    ],
    "summaries": [
      "python-colcon-core fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-commoncode": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325197"
    ],
    "summaries": [
      "python-commoncode fails to build with Python 3.14: tarfile.SpecialFileError: '6-FIFOTYPE' is a special file"
    ]
  },
  "python-confuse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
    ],
    "summaries": [
      "python-confuse fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-contourpy": {
    "urls": [],
    "summaries": []
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-cvxopt": {
    "urls": [],
    "summaries": []
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-dateparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336931"
    ],
    "summaries": [
      "python-dateparser: FTBFS in Fedora Rawhide: AssertionError in TestTranslateSearch.test_relative_base_setting_2_en"
    ]
  },
  "python-defcon": {
    "urls": [],
    "summaries": []
  },
  "python-dill": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323157"
    ],
    "summaries": [
      "python-dill fails to build with Python 3.14: TypeError: _Pickler._batch_setitems() missing 1 required positional argument: 'obj'"
    ]
  },
  "python-django-filter": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336944"
    ],
    "summaries": [
      "python-django-filter fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "python-epub": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319654"
    ],
    "summaries": [
      "python-epub fails to build with setuptools 74+"
    ]
  },
  "python-etcd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
    ],
    "summaries": [
      "python-etcd fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestWatch.test_watch_indexed_generator.<locals>.watch_value at 0x7f0d39f71dd0>"
    ]
  },
  "python-events": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319655"
    ],
    "summaries": [
      "python-events fails to build with setuptools 74+"
    ]
  },
  "python-executing": {
    "urls": [],
    "summaries": []
  },
  "python-flask": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327965"
    ],
    "summaries": [
      "python-flask fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-fs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336951"
    ],
    "summaries": [
      "python-fs fails to build with Python 3.14: AssertionError: 'osfs://///tmp/tmppauy69swfstestosfs/foo' != 'osfs:///tmp/tmppauy69swfstestosfs/foo'"
    ]
  },
  "python-fsleyes-widgets": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336911"
    ],
    "summaries": [
      "python-fsleyes-widgets fails to build with Python 3.14: AssertionError: assert 'file:/home/b...htmlfile.html' == 'file:///home...htmlfile.html'"
    ]
  },
  "python-giacpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341608"
    ],
    "summaries": [
      "python-giacpy: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-git-revise": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341157"
    ],
    "summaries": [
      "python-git-revise: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-gitlab": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342565"
    ],
    "summaries": [
      "python-gitlab fails to build with Python 3.14: AttributeError: 'Variable' object has no attribute '__annotations__'. Did you mean: '__annotate__'? and more"
    ]
  },
  "python-glyphsLib": {
    "urls": [],
    "summaries": []
  },
  "python-googleapis-common-protos": {
    "urls": [],
    "summaries": []
  },
  "python-gphoto2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341158"
    ],
    "summaries": [
      "python-gphoto2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-graph-tool": {
    "urls": [],
    "summaries": []
  },
  "python-h5netcdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325222"
    ],
    "summaries": [
      "python-h5netcdf fails to build with Python 3.14: test_no_circular_references: AssertionError"
    ]
  },
  "python-hamcrest": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341160"
    ],
    "summaries": [
      "python-hamcrest: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-hexbytes": {
    "urls": [],
    "summaries": []
  },
  "python-hl7": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341161"
    ],
    "summaries": [
      "python-hl7: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-howdoi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342558"
    ],
    "summaries": [
      "python-howdoi fails to build with Python 3.14: AssertionError: 'ERROR: Unable to reach google. Do you need to use a proxy? + json.decoder.JSONDecodeError"
    ]
  },
  "python-httpretty": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343976"
    ],
    "summaries": [
      "python-httpretty fails to build with Python 3.14: AttributeError: 'SSLContext' object has no attribute 'close' & 'sendall'"
    ]
  },
  "python-icalendar": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336946"
    ],
    "summaries": [
      "python-icalendar: FTBFS in Fedora Rawhide: AssertionError: assert 'WET' in ('Europe/Lisbon', 'Portugal')  where ('Europe/Lisbon', 'Portugal') = tzids_from_tzinfo(tzfile('/usr/share/zoneinfo/WET'))"
    ]
  },
  "python-img2pdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328707"
    ],
    "summaries": [
      "python-img2pdf fails to build in rawhide: 48 AssertionErrors"
    ]
  },
  "python-iniparse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
    ],
    "summaries": [
      "python-iniparse fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestIni.test_queue.<locals>.getxy at 0x7f86659a7740>"
    ]
  },
  "python-inject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
    ],
    "summaries": [
      "python-inject fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-irc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
    ],
    "summaries": [
      "python-irc fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-jeepney": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327982"
    ],
    "summaries": [
      "python-jeepney fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-joblib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339519"
    ],
    "summaries": [
      "python-joblib fails to build with Python 3.14: TypeError: Hasher._batch_setitems() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-josepy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342557",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323171"
    ],
    "summaries": [
      "python-josepy fails to build with Python 3.14: 7 tests fail with ValueError: Field `alg` in JSONObject `Header` has no type annotation.",
      "python-josepy fails to build with Python 3.14: 6x ValueError: Field `alg` in JSONObject `Header` has no type annotation."
    ]
  },
  "python-jupyter-c-kernel": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-events": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-kernel-singular": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-polymake": {
    "urls": [],
    "summaries": []
  },
  "python-m2r": {
    "urls": [],
    "summaries": []
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-matplotlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328713"
    ],
    "summaries": [
      "python-matplotlib fails to build with Python 3.14: RecursionError: maximum recursion depth exceeded"
    ]
  },
  "python-mccabe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328016"
    ],
    "summaries": [
      "python-mccabe fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-meshio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2333493"
    ],
    "summaries": [
      "python-meshio: FTBFS in Fedora Rawhide"
    ]
  },
  "python-mistune08": {
    "urls": [],
    "summaries": []
  },
  "python-mkapi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342559"
    ],
    "summaries": [
      "python-mkapi fails to build with Python 3.14: Expected: [None, <ast.Constant object at 0x...>, <ast.Constant object at 0x...>] Got: [None, Constant(value=2, kind=None), Constant(value=3, kind=None)]"
    ]
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-nine": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343977"
    ],
    "summaries": [
      "python-nine fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'URLopener'"
    ]
  },
  "python-nose": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323163"
    ],
    "summaries": [
      "python-nose fails to build with Python 3.14: multiple AssertionErrors related to timeouts in test outputs"
    ]
  },
  "python-notify2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341175"
    ],
    "summaries": [
      "python-notify2: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-oscrypto": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341177"
    ],
    "summaries": [
      "python-oscrypto: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-packvers": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341178"
    ],
    "summaries": [
      "python-packvers: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pandas": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341179"
    ],
    "summaries": [
      "python-pandas: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-photutils": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336893"
    ],
    "summaries": [
      "python-photutils: FTBFS in Fedora Rawhide: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments."
    ]
  },
  "python-pip": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335909"
    ],
    "summaries": [
      "python-pip fails to build with Python 3.14: AssertionError: assert 'file:/tmp/file' == 'file:///tmp/file'"
    ]
  },
  "python-praw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342562"
    ],
    "summaries": [
      "python-praw fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-psycopg3": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339461"
    ],
    "summaries": [
      "python-psycopg3 fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pydantic-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
    ],
    "summaries": [
      "python-pydantic-core fails to build with Python 3.14: AssertionError: Regex pattern did not match. + AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pymdown-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336948"
    ],
    "summaries": [
      "python-pymdown-extensions fails to build with Python 3.14: TestAbsolute.test_relative_path and TestAbsoluteFileScheme.test_relative_path AssertionErrors"
    ]
  },
  "python-pymeeus": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341186"
    ],
    "summaries": [
      "python-pymeeus: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pymilter": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341187"
    ],
    "summaries": [
      "python-pymilter: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pymssql": {
    "urls": [],
    "summaries": []
  },
  "python-pyopencl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341190"
    ],
    "summaries": [
      "python-pyopencl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyopengl": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341191"
    ],
    "summaries": [
      "python-pyopengl: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyqtgraph": {
    "urls": [],
    "summaries": []
  },
  "python-pyquery": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341196"
    ],
    "summaries": [
      "python-pyquery: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pytesseract": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341201"
    ],
    "summaries": [
      "python-pytesseract: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-pytest-aiohttp": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339466"
    ],
    "summaries": [
      "python-pytest-aiohttp fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-pytest-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342564"
    ],
    "summaries": [
      "python-pytest-asyncio fails to build with Python 3.14: DeprecationWarning: 'asyncio.get_event_loop_policy' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-pytest-datadir": {
    "urls": [],
    "summaries": []
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-pyvlx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
    ],
    "summaries": [
      "python-pyvlx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-rdflib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2343978",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336891"
    ],
    "summaries": [
      "python-rdflib fails to build with Python 3.14: AttributeError: term 'value' not in namespace 'http://www.w3.org/1999/02/22-rdf-syntax-ns#'",
      "python-rdflib fails to build with Python 3.14: \"TypeError: '<' not supported between instances of 'Literal' and 'Literal'\""
    ]
  },
  "python-reactivex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
    ],
    "summaries": [
      "python-reactivex fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-redis": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341204",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326927"
    ],
    "summaries": [
      "python-redis: FTBFS in Fedora rawhide/f42",
      "python-redis fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_redis_client.<locals>.target at 0x7fd5f829efb0>"
    ]
  },
  "python-remoto": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341205"
    ],
    "summaries": [
      "python-remoto: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-rosdep": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341207"
    ],
    "summaries": [
      "python-rosdep: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-rq": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342234"
    ],
    "summaries": [
      "python-rq fails to build with Python 3.14: test_worker.py::HerokuWorkerShutdownTestCase::test_handle_shutdown_request shuts down the whole build"
    ]
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-seaborn": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341210"
    ],
    "summaries": [
      "python-seaborn: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-sep": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336965"
    ],
    "summaries": [
      "python-sep: FTBFS in Fedora Rawhide: Error compiling Cython file: 'int_t' is not a type identifier"
    ]
  },
  "python-serpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319716"
    ],
    "summaries": [
      "python-serpy fails to build with setuptools 74+"
    ]
  },
  "python-social-auth-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341215",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328010"
    ],
    "summaries": [
      "python-social-auth-core: FTBFS in Fedora rawhide/f42",
      "python-social-auth-core fails to build with Python 3.14: 'SSLContext' object has no attribute 'close'"
    ]
  },
  "python-sqlalchemy1.4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
    ],
    "summaries": [
      "python-sqlalchemy1.4 fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-stdlibs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336938"
    ],
    "summaries": [
      "python-stdlibs fails to build with Python 3.14: test_all_my_modules_are_there: AssertionError: Items in the second set but not the first: '_apple_support'"
    ]
  },
  "python-steam": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341218"
    ],
    "summaries": [
      "python-steam: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-svg2tikz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341220"
    ],
    "summaries": [
      "python-svg2tikz: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-tenacity": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
    ],
    "summaries": [
      "python-tenacity fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-terminado": {
    "urls": [],
    "summaries": []
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-tornado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
    ],
    "summaries": [
      "python-tornado fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-tree-format": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319731"
    ],
    "summaries": [
      "python-tree-format fails to build with setuptools 74+"
    ]
  },
  "python-twisted": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2342754"
    ],
    "summaries": [
      "python-twisted fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'. + more"
    ]
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typing-extensions": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336937"
    ],
    "summaries": [
      "python-typing-extensions fails to build with Python 3.14: test_drop_in_for_typing: AssertionError: self.assertGreaterEqual(te_all, t_all - exceptions)"
    ]
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-urwid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
    ],
    "summaries": [
      "python-urwid fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341233",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop: FTBFS in Fedora rawhide/f42",
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-valkey": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341234",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326934"
    ],
    "summaries": [
      "python-valkey: FTBFS in Fedora rawhide/f42",
      "python-valkey fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f7d711b5dd0>"
    ]
  },
  "python-watchfiles": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2339462"
    ],
    "summaries": [
      "python-watchfiles fails to build with Python 3.14: DeprecationWarning: 'asyncio.set_event_loop' is deprecated and slated for removal in Python 3.16"
    ]
  },
  "python-webscrapbook": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341237",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326915"
    ],
    "summaries": [
      "python-webscrapbook: FTBFS in Fedora rawhide/f42",
      "python-webscrapbook fails to build with Python 3.14: 60x AssertionError in the test suite"
    ]
  },
  "python-wordcloud": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335908"
    ],
    "summaries": [
      "python-wordcloud fails to build with Python 3.14: test_cli_as_executable: AssertionError: assert expected_output in out if ret_code == 0 else err"
    ]
  },
  "python-xunitparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319738"
    ],
    "summaries": [
      "python-xunitparser fails to build with setuptools 74+"
    ]
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-zope-i18nmessageid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341241"
    ],
    "summaries": [
      "python-zope-i18nmessageid: FTBFS in Fedora rawhide/f42"
    ]
  },
  "python-zope-testrunner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2335907"
    ],
    "summaries": [
      "python-zope-testrunner fails to build with Python 3.14: difference in the asserted content in testrunner-edge-cases.rst"
    ]
  },
  "python-zstandard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326925"
    ],
    "summaries": [
      "python-zstandard fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "qgis": {
    "urls": [],
    "summaries": []
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "recoll": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341273"
    ],
    "summaries": [
      "recoll: FTBFS in Fedora rawhide/f42"
    ]
  },
  "remmina": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341277"
    ],
    "summaries": [
      "remmina: FTBFS in Fedora rawhide/f42"
    ]
  },
  "renderdoc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341279"
    ],
    "summaries": [
      "renderdoc: FTBFS in Fedora rawhide/f42"
    ]
  },
  "satyr": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
    ],
    "summaries": [
      "satyr fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestDistances.test_distances_part_parallel.<locals>.do_test.<locals>.compute_part at 0x7f7f845f2560>"
    ]
  },
  "scidavis": {
    "urls": [],
    "summaries": []
  },
  "scipy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341927"
    ],
    "summaries": [
      "scipy fails to build with Python 3.14: TestSystematic::test_bessely, TestSystematic::test_bessely_int and TestSystematic::test_wrightomega fail"
    ]
  },
  "signon-glib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341348"
    ],
    "summaries": [
      "signon-glib: FTBFS in Fedora rawhide/f42"
    ]
  },
  "strongswan": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332864"
    ],
    "summaries": [
      "strongswan-5.9.14-5.fc42 FTBFS: strongswan-5.9.14/missing: line 81: aclocal-1.16: command not found"
    ]
  },
  "systemtap": {
    "urls": [],
    "summaries": []
  },
  "tcl-snack": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341418"
    ],
    "summaries": [
      "tcl-snack: FTBFS in Fedora rawhide/f42"
    ]
  },
  "thrift": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341433"
    ],
    "summaries": [
      "thrift: FTBFS in Fedora rawhide/f42"
    ]
  },
  "ufw": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341477"
    ],
    "summaries": [
      "ufw: FTBFS in Fedora rawhide/f42"
    ]
  },
  "uhd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2341478"
    ],
    "summaries": [
      "uhd: FTBFS in Fedora rawhide/f42"
    ]
  },
  "unbound": {
    "urls": [],
    "summaries": []
  },
  "uv": {
    "urls": [],
    "summaries": []
  },
  "veusz": {
    "urls": [],
    "summaries": []
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "vorta": {
    "urls": [],
    "summaries": []
  },
  "weasyprint": {
    "urls": [],
    "summaries": []
  },
  "xonsh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336895"
    ],
    "summaries": [
      "xonsh fails to build with Python 3.14: ValueError: action 'store_true' is not valid for positional arguments"
    ]
  },
  "xpra": {
    "urls": [],
    "summaries": []
  },
  "yamllint": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2336947"
    ],
    "summaries": [
      "yamllint fails to build with Python 3.14: ValueError('I/O operation on closed file')"
    ]
  }
}