{
  "NLopt": {
    "urls": [],
    "summaries": []
  },
  "PyGreSQL": {
    "urls": [],
    "summaries": []
  },
  "RBTools": {
    "urls": [],
    "summaries": []
  },
  "WALinuxAgent": {
    "urls": [],
    "summaries": []
  },
  "adapt": {
    "urls": [],
    "summaries": []
  },
  "alot": {
    "urls": [],
    "summaries": []
  },
  "ara": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331346"
    ],
    "summaries": [
      "ara fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "astrometry": {
    "urls": [],
    "summaries": []
  },
  "aubio": {
    "urls": [],
    "summaries": []
  },
  "beaker": {
    "urls": [],
    "summaries": []
  },
  "bids-schema": {
    "urls": [],
    "summaries": []
  },
  "binwalk": {
    "urls": [],
    "summaries": []
  },
  "bluechi": {
    "urls": [],
    "summaries": []
  },
  "bodhi-client": {
    "urls": [],
    "summaries": []
  },
  "boost": {
    "urls": [],
    "summaries": []
  },
  "borgbackup": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326916"
    ],
    "summaries": [
      "borgbackup fails to build with Python 3.14: OSError: AF_UNIX path too long when compiling"
    ]
  },
  "cepces": {
    "urls": [],
    "summaries": []
  },
  "ceph": {
    "urls": [],
    "summaries": []
  },
  "chirp": {
    "urls": [],
    "summaries": []
  },
  "cjdns": {
    "urls": [],
    "summaries": []
  },
  "cloud-init": {
    "urls": [],
    "summaries": []
  },
  "cobbler": {
    "urls": [],
    "summaries": []
  },
  "cockpit": {
    "urls": [],
    "summaries": []
  },
  "codespell": {
    "urls": [],
    "summaries": []
  },
  "collectd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332982"
    ],
    "summaries": [
      "collectd-5.12.0-45.fc42 FTBFS: collectd-5.12.0/build-aux/missing: line 81: aclocal-1.16: command not found"
    ]
  },
  "compose-utils": {
    "urls": [],
    "summaries": []
  },
  "csmock": {
    "urls": [],
    "summaries": []
  },
  "did": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328006"
    ],
    "summaries": [
      "did fails to build with Python 3.14: AttributeError: module 'urllib.request' has no attribute 'FancyURLopener'"
    ]
  },
  "dist-git-client": {
    "urls": [],
    "summaries": []
  },
  "distgen": {
    "urls": [],
    "summaries": []
  },
  "dlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328014"
    ],
    "summaries": [
      "dlib fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'find_loader'"
    ]
  },
  "dnf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323186"
    ],
    "summaries": [
      "dnf fails to build with Python 3.14: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "dnsconfd": {
    "urls": [],
    "summaries": []
  },
  "dput-ng": {
    "urls": [],
    "summaries": []
  },
  "ec2-hibinit-agent": {
    "urls": [],
    "summaries": []
  },
  "elements-alexandria": {
    "urls": [],
    "summaries": []
  },
  "espresso": {
    "urls": [],
    "summaries": []
  },
  "esptool": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331345"
    ],
    "summaries": [
      "esptool fails to build with Python 3.14: AssertionError: assert 'usage: __main__.py [-h]' in 'espefuse.py v4.8.1\\nusage: python3 -m espefuse [-h]\\n                           [--chip {auto,esp32,esp32c2,esp32c3,e... --extend-efuse-table EXTEND_EFUSE_TABLE\\"
    ]
  },
  "fail2ban": {
    "urls": [],
    "summaries": []
  },
  "fedfind": {
    "urls": [],
    "summaries": []
  },
  "fedora-review": {
    "urls": [],
    "summaries": []
  },
  "fedscm-admin": {
    "urls": [],
    "summaries": []
  },
  "flann": {
    "urls": [],
    "summaries": []
  },
  "flatbuffers": {
    "urls": [],
    "summaries": []
  },
  "freeipa": {
    "urls": [],
    "summaries": []
  },
  "git-up": {
    "urls": [],
    "summaries": []
  },
  "gitlint": {
    "urls": [],
    "summaries": []
  },
  "gnuradio": {
    "urls": [],
    "summaries": []
  },
  "grammalecte": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319629"
    ],
    "summaries": [
      "grammalecte fails to build with setuptools 74+"
    ]
  },
  "h5py": {
    "urls": [],
    "summaries": []
  },
  "hddfancontrol": {
    "urls": [],
    "summaries": []
  },
  "home-assistant-cli": {
    "urls": [],
    "summaries": []
  },
  "ioc-writer": {
    "urls": [],
    "summaries": []
  },
  "jc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331343"
    ],
    "summaries": [
      "jc fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "keylime": {
    "urls": [],
    "summaries": []
  },
  "kicad": {
    "urls": [],
    "summaries": []
  },
  "lammps": {
    "urls": [],
    "summaries": []
  },
  "lazygal": {
    "urls": [],
    "summaries": []
  },
  "libarrow": {
    "urls": [],
    "summaries": []
  },
  "libfreenect": {
    "urls": [],
    "summaries": []
  },
  "libgpiod": {
    "urls": [],
    "summaries": []
  },
  "libnvme": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325194"
    ],
    "summaries": [
      "libnvme fails to build with Python 3.14: /usr/include/python3.14/pyport.h:629:35: error: missing ')' after \"__has_attribute\""
    ]
  },
  "libselinux": {
    "urls": [],
    "summaries": []
  },
  "libsemanage": {
    "urls": [],
    "summaries": []
  },
  "libsonata": {
    "urls": [],
    "summaries": []
  },
  "linode-cli": {
    "urls": [],
    "summaries": []
  },
  "liquidctl": {
    "urls": [],
    "summaries": []
  },
  "llvm": {
    "urls": [],
    "summaries": []
  },
  "mat2": {
    "urls": [],
    "summaries": []
  },
  "mathgl": {
    "urls": [],
    "summaries": []
  },
  "mkdocs": {
    "urls": [],
    "summaries": []
  },
  "mlpack": {
    "urls": [],
    "summaries": []
  },
  "mock": {
    "urls": [],
    "summaries": []
  },
  "module-build": {
    "urls": [],
    "summaries": []
  },
  "modulemd-tools": {
    "urls": [],
    "summaries": []
  },
  "mogui": {
    "urls": [],
    "summaries": []
  },
  "moose": {
    "urls": [],
    "summaries": []
  },
  "mopidy": {
    "urls": [],
    "summaries": []
  },
  "mopidy-mpd": {
    "urls": [],
    "summaries": []
  },
  "morphio": {
    "urls": [],
    "summaries": []
  },
  "nagios-plugins-systemd": {
    "urls": [],
    "summaries": []
  },
  "netcdf4-python": {
    "urls": [],
    "summaries": []
  },
  "nfs-ganesha": {
    "urls": [],
    "summaries": []
  },
  "nox": {
    "urls": [],
    "summaries": []
  },
  "nwchem": {
    "urls": [],
    "summaries": []
  },
  "offlineimap": {
    "urls": [],
    "summaries": []
  },
  "onnxruntime": {
    "urls": [],
    "summaries": []
  },
  "openmeeg": {
    "urls": [],
    "summaries": []
  },
  "openssh-ldap-authkeys": {
    "urls": [],
    "summaries": []
  },
  "opentrep": {
    "urls": [],
    "summaries": []
  },
  "openvino": {
    "urls": [],
    "summaries": []
  },
  "openwsman": {
    "urls": [],
    "summaries": []
  },
  "osbuild": {
    "urls": [],
    "summaries": []
  },
  "osc": {
    "urls": [],
    "summaries": []
  },
  "pacemaker": {
    "urls": [],
    "summaries": []
  },
  "past-time": {
    "urls": [],
    "summaries": []
  },
  "patool": {
    "urls": [],
    "summaries": []
  },
  "pcs": {
    "urls": [],
    "summaries": []
  },
  "pdc-client": {
    "urls": [],
    "summaries": []
  },
  "petsc": {
    "urls": [],
    "summaries": []
  },
  "pgzero": {
    "urls": [],
    "summaries": []
  },
  "plplot": {
    "urls": [],
    "summaries": []
  },
  "pmbootstrap": {
    "urls": [],
    "summaries": []
  },
  "poezio": {
    "urls": [],
    "summaries": []
  },
  "policycoreutils": {
    "urls": [],
    "summaries": []
  },
  "postfix-mta-sts-resolver": {
    "urls": [],
    "summaries": []
  },
  "postgresql15": {
    "urls": [],
    "summaries": []
  },
  "postgresql16": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332981"
    ],
    "summaries": [
      "postgresql16-16.3-7.fc42 FTBFS: tests fail with tzdata-2024b"
    ]
  },
  "postgresql17": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332978",
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327967"
    ],
    "summaries": [
      "postgresql17-17.0-1.fc42 FTBFS: RPM build errors: line 227: second Description",
      "postgresql17 fails to build with Python 3.14: jsonb_jsonpath fails: - \"12:34:56-07:00\" != + \"12:34:56-08:00\""
    ]
  },
  "powerline": {
    "urls": [],
    "summaries": []
  },
  "prewikka": {
    "urls": [],
    "summaries": []
  },
  "protobuf": {
    "urls": [],
    "summaries": []
  },
  "ptpython": {
    "urls": [],
    "summaries": []
  },
  "pybind11": {
    "urls": [],
    "summaries": []
  },
  "pycairo": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322709"
    ],
    "summaries": [
      "pycairo fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "pychess": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328708"
    ],
    "summaries": [
      "pychess fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "pygsl": {
    "urls": [],
    "summaries": []
  },
  "pyinstrument": {
    "urls": [],
    "summaries": []
  },
  "pykka": {
    "urls": [],
    "summaries": []
  },
  "pyosmium": {
    "urls": [],
    "summaries": []
  },
  "pyproj": {
    "urls": [],
    "summaries": []
  },
  "pyserial-asyncio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327980"
    ],
    "summaries": [
      "pyserial-asyncio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-APScheduler": {
    "urls": [],
    "summaries": []
  },
  "python-AppTools": {
    "urls": [],
    "summaries": []
  },
  "python-Automat": {
    "urls": [],
    "summaries": []
  },
  "python-PyAVM": {
    "urls": [],
    "summaries": []
  },
  "python-PyGithub": {
    "urls": [],
    "summaries": []
  },
  "python-accept-types": {
    "urls": [],
    "summaries": []
  },
  "python-accessible-pygments": {
    "urls": [],
    "summaries": []
  },
  "python-accuweather": {
    "urls": [],
    "summaries": []
  },
  "python-ailment": {
    "urls": [],
    "summaries": []
  },
  "python-aioftp": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-cors": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-oauthlib": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-retry": {
    "urls": [],
    "summaries": []
  },
  "python-aiohttp-sse-client": {
    "urls": [],
    "summaries": []
  },
  "python-aiokafka": {
    "urls": [],
    "summaries": []
  },
  "python-aiomultiprocess": {
    "urls": [],
    "summaries": []
  },
  "python-aioresponses": {
    "urls": [],
    "summaries": []
  },
  "python-aioruckus": {
    "urls": [],
    "summaries": []
  },
  "python-aiosmtpd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322718"
    ],
    "summaries": [
      "python-aiosmtpd fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-ansi2html": {
    "urls": [],
    "summaries": []
  },
  "python-ansible-pylibssh": {
    "urls": [],
    "summaries": []
  },
  "python-anyio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328710"
    ],
    "summaries": [
      "python-anyio fails to build with Python 3.14: AttributeError: '_UnixDefaultEventLoopPolicy' object has no attribute 'get_child_watcher' && TypeError: PurePath.relative_to() takes 2 positional arguments but 3 were given"
    ]
  },
  "python-apipkg": {
    "urls": [],
    "summaries": []
  },
  "python-apsw": {
    "urls": [],
    "summaries": []
  },
  "python-archinfo": {
    "urls": [],
    "summaries": []
  },
  "python-archspec": {
    "urls": [],
    "summaries": []
  },
  "python-aresponses": {
    "urls": [],
    "summaries": []
  },
  "python-argon2-cffi": {
    "urls": [],
    "summaries": []
  },
  "python-array-api-strict": {
    "urls": [],
    "summaries": []
  },
  "python-asn1tools": {
    "urls": [],
    "summaries": []
  },
  "python-astral": {
    "urls": [],
    "summaries": []
  },
  "python-astroid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323166"
    ],
    "summaries": [
      "python-astroid fails to build with Python 3.14: astroid.exceptions.InferenceError: StopIteration raised without any error information."
    ]
  },
  "python-astropy-iers-data": {
    "urls": [],
    "summaries": []
  },
  "python-asttokens": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331375"
    ],
    "summaries": [
      "python-asttokens fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-async-lru": {
    "urls": [],
    "summaries": []
  },
  "python-asyncssh": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325445"
    ],
    "summaries": [
      "python-asyncssh fails to build with Python 3.14: multiple test failures (failures=25, errors=697)"
    ]
  },
  "python-asysocks": {
    "urls": [],
    "summaries": []
  },
  "python-atlassian-python-api": {
    "urls": [],
    "summaries": []
  },
  "python-attrs": {
    "urls": [],
    "summaries": []
  },
  "python-audioread": {
    "urls": [],
    "summaries": []
  },
  "python-auth-credential": {
    "urls": [],
    "summaries": []
  },
  "python-autocommand": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327972"
    ],
    "summaries": [
      "python-autocommand fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-autograd": {
    "urls": [],
    "summaries": []
  },
  "python-automaton": {
    "urls": [],
    "summaries": []
  },
  "python-autopage": {
    "urls": [],
    "summaries": []
  },
  "python-avocado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325218"
    ],
    "summaries": [
      "python-avocado fails to build with Python 3.14: Error running method \"pre_tests\" of plugin \"fetchasset\": module 'ast' has no attribute 'Str' + Avocado crashed: TypeError: cannot pickle '_thread.RLock' object"
    ]
  },
  "python-azure-ai-formrecognizer": {
    "urls": [],
    "summaries": []
  },
  "python-azure-ai-textanalytics": {
    "urls": [],
    "summaries": []
  },
  "python-azure-appconfiguration": {
    "urls": [],
    "summaries": []
  },
  "python-azure-batch": {
    "urls": [],
    "summaries": []
  },
  "python-azure-common": {
    "urls": [],
    "summaries": []
  },
  "python-azure-data-tables": {
    "urls": [],
    "summaries": []
  },
  "python-azure-graphrbac": {
    "urls": [],
    "summaries": []
  },
  "python-azure-keyvault-administration": {
    "urls": [],
    "summaries": []
  },
  "python-azure-keyvault-keys": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-apimanagement": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-appconfiguration": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-appcontainers": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-applicationinsights": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-authorization": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-batch": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-batchai": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-cdn": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-cognitiveservices": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-compute": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-containerinstance": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-containerregistry": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-containerservice": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-core": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-cosmosdb": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-datalake-analytics": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-datalake-store": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-eventgrid": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-eventhub": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-extendedlocation": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-hdinsight": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-imagebuilder": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-iotcentral": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-iothub": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-iothubprovisioningservices": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-keyvault": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-kusto": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-loganalytics": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-managementgroups": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-media": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-monitor": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-msi": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-netapp": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-network": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-policyinsights": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-privatedns": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-quota": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-rdbms": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-recoveryservices": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-recoveryservicesbackup": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-redhatopenshift": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-redis": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-relay": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-resource": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-search": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-security": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-servicebus": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-servicefabric": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-servicefabricmanagedclusters": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-servicelinker": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-signalr": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-sql": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-sqlvirtualmachine": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-storage": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-subscription": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-support": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-synapse": {
    "urls": [],
    "summaries": []
  },
  "python-azure-mgmt-trafficmanager": {
    "urls": [],
    "summaries": []
  },
  "python-azure-monitor-query": {
    "urls": [],
    "summaries": []
  },
  "python-azure-multiapi-storage": {
    "urls": [],
    "summaries": []
  },
  "python-azure-servicebus": {
    "urls": [],
    "summaries": []
  },
  "python-azure-storage-blob": {
    "urls": [],
    "summaries": []
  },
  "python-azure-synapse-accesscontrol": {
    "urls": [],
    "summaries": []
  },
  "python-azure-synapse-artifacts": {
    "urls": [],
    "summaries": []
  },
  "python-azure-synapse-managedprivateendpoints": {
    "urls": [],
    "summaries": []
  },
  "python-azure-synapse-spark": {
    "urls": [],
    "summaries": []
  },
  "python-backrefs": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325184"
    ],
    "summaries": [
      "python-backrefs fails to build with Python 3.14: Failed to acquire all needed Unicode files!"
    ]
  },
  "python-base58": {
    "urls": [],
    "summaries": []
  },
  "python-bashate": {
    "urls": [],
    "summaries": []
  },
  "python-bcrypt": {
    "urls": [],
    "summaries": []
  },
  "python-beartype": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322721"
    ],
    "summaries": [
      "python-beartype fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-beautifulsoup4": {
    "urls": [],
    "summaries": []
  },
  "python-behave": {
    "urls": [],
    "summaries": []
  },
  "python-bidict": {
    "urls": [],
    "summaries": []
  },
  "python-billiard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323167"
    ],
    "summaries": [
      "python-billiard fails to build with Python 3.14: AttributeError: module 'subprocess' has no attribute '_USE_VFORK'"
    ]
  },
  "python-binaryornot": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319640"
    ],
    "summaries": [
      "python-binaryornot fails to build with setuptools 74+"
    ]
  },
  "python-bioread": {
    "urls": [],
    "summaries": []
  },
  "python-blinker": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325193"
    ],
    "summaries": [
      "python-blinker fails to build with Python 3.14: pluggy.PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown."
    ]
  },
  "python-blosc": {
    "urls": [],
    "summaries": []
  },
  "python-blowfish": {
    "urls": [],
    "summaries": []
  },
  "python-bravado": {
    "urls": [],
    "summaries": []
  },
  "python-bravado-core": {
    "urls": [],
    "summaries": []
  },
  "python-brukerapi": {
    "urls": [],
    "summaries": []
  },
  "python-bugzilla": {
    "urls": [],
    "summaries": []
  },
  "python-cached_property": {
    "urls": [],
    "summaries": []
  },
  "python-cachelib": {
    "urls": [],
    "summaries": []
  },
  "python-cairocffi": {
    "urls": [],
    "summaries": []
  },
  "python-calcephpy": {
    "urls": [],
    "summaries": []
  },
  "python-canonicaljson": {
    "urls": [],
    "summaries": []
  },
  "python-capturer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328004"
    ],
    "summaries": [
      "python-capturer fails to build with Python 3.14: OSError: [Errno 29] Illegal seek"
    ]
  },
  "python-cbor2": {
    "urls": [],
    "summaries": []
  },
  "python-cccolutils": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319642"
    ],
    "summaries": [
      "python-cccolutils fails to build with setuptools 74+"
    ]
  },
  "python-cffi": {
    "urls": [],
    "summaries": []
  },
  "python-cffsubr": {
    "urls": [],
    "summaries": []
  },
  "python-cftime": {
    "urls": [],
    "summaries": []
  },
  "python-chameleon": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322715"
    ],
    "summaries": [
      "python-chameleon fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-cheetah": {
    "urls": [],
    "summaries": []
  },
  "python-cid": {
    "urls": [],
    "summaries": []
  },
  "python-cinderclient": {
    "urls": [],
    "summaries": []
  },
  "python-claripy": {
    "urls": [],
    "summaries": []
  },
  "python-cliff": {
    "urls": [],
    "summaries": []
  },
  "python-cloup": {
    "urls": [],
    "summaries": []
  },
  "python-cma": {
    "urls": [],
    "summaries": []
  },
  "python-cmake-build-extension": {
    "urls": [],
    "summaries": []
  },
  "python-cmap": {
    "urls": [],
    "summaries": []
  },
  "python-cmd2": {
    "urls": [],
    "summaries": []
  },
  "python-cmdkit": {
    "urls": [],
    "summaries": []
  },
  "python-colcon-parallel-executor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325186"
    ],
    "summaries": [
      "python-colcon-parallel-executor fails to build with Python 3.14: test_parallel: AssertionError: DeprecationWarning: 'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction() instead"
    ]
  },
  "python-colcon-ros-bundle": {
    "urls": [],
    "summaries": []
  },
  "python-collada": {
    "urls": [],
    "summaries": []
  },
  "python-collectd_cvmfs": {
    "urls": [],
    "summaries": []
  },
  "python-collectd_systemd": {
    "urls": [],
    "summaries": []
  },
  "python-colorful": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325168"
    ],
    "summaries": [
      "python-colorful fails to build with Python 3.14: ast.Constant.s has been removed from Python 3.14"
    ]
  },
  "python-colormath2": {
    "urls": [],
    "summaries": []
  },
  "python-commoncode": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325197"
    ],
    "summaries": [
      "python-commoncode fails to build with Python 3.14: tarfile.SpecialFileError: '6-FIFOTYPE' is a special file"
    ]
  },
  "python-compreffor": {
    "urls": [],
    "summaries": []
  },
  "python-confuse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327966"
    ],
    "summaries": [
      "python-confuse fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-contourpy": {
    "urls": [],
    "summaries": []
  },
  "python-cramjam": {
    "urls": [],
    "summaries": []
  },
  "python-crick": {
    "urls": [],
    "summaries": []
  },
  "python-crossword": {
    "urls": [],
    "summaries": []
  },
  "python-cryptography": {
    "urls": [],
    "summaries": []
  },
  "python-cs": {
    "urls": [],
    "summaries": []
  },
  "python-css-parser": {
    "urls": [],
    "summaries": []
  },
  "python-cysignals": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325457"
    ],
    "summaries": [
      "python-cysignals fails to build with Python 3.14: Doctest src/cysignals/pselect.pyx terminated. Timeout limit exceeded (>2400s)"
    ]
  },
  "python-daikin": {
    "urls": [],
    "summaries": []
  },
  "python-dataclassy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325200"
    ],
    "summaries": [
      "python-dataclassy fails to build with Python 3.14: TypeError: Beta() takes no arguments"
    ]
  },
  "python-dateparser": {
    "urls": [],
    "summaries": []
  },
  "python-dateutil": {
    "urls": [],
    "summaries": []
  },
  "python-datrie": {
    "urls": [],
    "summaries": []
  },
  "python-debian": {
    "urls": [],
    "summaries": []
  },
  "python-debtcollector": {
    "urls": [],
    "summaries": []
  },
  "python-defcon": {
    "urls": [],
    "summaries": []
  },
  "python-detect-secrets": {
    "urls": [],
    "summaries": []
  },
  "python-dictdiffer": {
    "urls": [],
    "summaries": []
  },
  "python-diff-cover": {
    "urls": [],
    "summaries": []
  },
  "python-diff-match-patch": {
    "urls": [],
    "summaries": []
  },
  "python-dijitso": {
    "urls": [],
    "summaries": []
  },
  "python-dill": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323157"
    ],
    "summaries": [
      "python-dill fails to build with Python 3.14: TypeError: _Pickler._batch_setitems() missing 1 required positional argument: 'obj'"
    ]
  },
  "python-dirhash": {
    "urls": [],
    "summaries": []
  },
  "python-diskcache": {
    "urls": [],
    "summaries": []
  },
  "python-distroinfo": {
    "urls": [],
    "summaries": []
  },
  "python-django-allauth": {
    "urls": [],
    "summaries": []
  },
  "python-django-cacheops": {
    "urls": [],
    "summaries": []
  },
  "python-django-compressor": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322719"
    ],
    "summaries": [
      "python-django-compressor fails to build with Python 3.14: 'Constant' object has no attribute 's'"
    ]
  },
  "python-django-configurations": {
    "urls": [],
    "summaries": []
  },
  "python-django-contrib-comments": {
    "urls": [],
    "summaries": []
  },
  "python-django-debreach": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328003"
    ],
    "summaries": [
      "python-django-debreach fails to build with Python 3.14: AttributeError: 'super' object has no attribute 'dicts' and no __dict__ for setting new attributes"
    ]
  },
  "python-django-extensions": {
    "urls": [],
    "summaries": []
  },
  "python-django-filter": {
    "urls": [],
    "summaries": []
  },
  "python-django-mailman3": {
    "urls": [],
    "summaries": []
  },
  "python-django-picklefield": {
    "urls": [],
    "summaries": []
  },
  "python-djangoql": {
    "urls": [],
    "summaries": []
  },
  "python-dogpile-cache": {
    "urls": [],
    "summaries": []
  },
  "python-dotenv": {
    "urls": [],
    "summaries": []
  },
  "python-dropbox": {
    "urls": [],
    "summaries": []
  },
  "python-ducc0": {
    "urls": [],
    "summaries": []
  },
  "python-dulwich": {
    "urls": [],
    "summaries": []
  },
  "python-dunamai": {
    "urls": [],
    "summaries": []
  },
  "python-eccodes": {
    "urls": [],
    "summaries": []
  },
  "python-ecdsa": {
    "urls": [],
    "summaries": []
  },
  "python-elementpath": {
    "urls": [],
    "summaries": []
  },
  "python-emcee": {
    "urls": [],
    "summaries": []
  },
  "python-engineio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327989"
    ],
    "summaries": [
      "python-engineio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-environs": {
    "urls": [],
    "summaries": []
  },
  "python-enzyme": {
    "urls": [],
    "summaries": []
  },
  "python-epub": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319654"
    ],
    "summaries": [
      "python-epub fails to build with setuptools 74+"
    ]
  },
  "python-etcd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323184"
    ],
    "summaries": [
      "python-etcd fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestWatch.test_watch_indexed_generator.<locals>.watch_value at 0x7f0d39f71dd0>"
    ]
  },
  "python-eth-hash": {
    "urls": [],
    "summaries": []
  },
  "python-eth-typing": {
    "urls": [],
    "summaries": []
  },
  "python-events": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319655"
    ],
    "summaries": [
      "python-events fails to build with setuptools 74+"
    ]
  },
  "python-exabgp": {
    "urls": [],
    "summaries": []
  },
  "python-exdir": {
    "urls": [],
    "summaries": []
  },
  "python-expecttest": {
    "urls": [],
    "summaries": []
  },
  "python-exrex": {
    "urls": [],
    "summaries": []
  },
  "python-extension-helpers": {
    "urls": [],
    "summaries": []
  },
  "python-falcon": {
    "urls": [],
    "summaries": []
  },
  "python-fasjson-client": {
    "urls": [],
    "summaries": []
  },
  "python-fast-simplification": {
    "urls": [],
    "summaries": []
  },
  "python-fedora": {
    "urls": [],
    "summaries": []
  },
  "python-fingerprints": {
    "urls": [],
    "summaries": []
  },
  "python-fireflyalgorithm": {
    "urls": [],
    "summaries": []
  },
  "python-fisx": {
    "urls": [],
    "summaries": []
  },
  "python-fitsio": {
    "urls": [],
    "summaries": []
  },
  "python-fixtures": {
    "urls": [],
    "summaries": []
  },
  "python-flask": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327965"
    ],
    "summaries": [
      "python-flask fails to build with Python 3.14: AttributeError: module 'pkgutil' has no attribute 'get_loader'"
    ]
  },
  "python-flask-caching": {
    "urls": [],
    "summaries": []
  },
  "python-flask-httpauth": {
    "urls": [],
    "summaries": []
  },
  "python-flask-oidc": {
    "urls": [],
    "summaries": []
  },
  "python-flask-session": {
    "urls": [],
    "summaries": []
  },
  "python-flit": {
    "urls": [],
    "summaries": []
  },
  "python-flufl-bounce": {
    "urls": [],
    "summaries": []
  },
  "python-flufl-i18n": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319659"
    ],
    "summaries": [
      "python-flufl-i18n fails to build with setuptools 74+"
    ]
  },
  "python-fontMath": {
    "urls": [],
    "summaries": []
  },
  "python-fontname": {
    "urls": [],
    "summaries": []
  },
  "python-freeipa": {
    "urls": [],
    "summaries": []
  },
  "python-freetype": {
    "urls": [],
    "summaries": []
  },
  "python-freezegun": {
    "urls": [],
    "summaries": []
  },
  "python-fs": {
    "urls": [],
    "summaries": []
  },
  "python-futurist": {
    "urls": [],
    "summaries": []
  },
  "python-gbulb": {
    "urls": [],
    "summaries": []
  },
  "python-genty": {
    "urls": [],
    "summaries": []
  },
  "python-geojson": {
    "urls": [],
    "summaries": []
  },
  "python-geopy": {
    "urls": [],
    "summaries": []
  },
  "python-giacpy": {
    "urls": [],
    "summaries": []
  },
  "python-gios": {
    "urls": [],
    "summaries": []
  },
  "python-glyphsLib": {
    "urls": [],
    "summaries": []
  },
  "python-gmpy2": {
    "urls": [],
    "summaries": []
  },
  "python-gnocchiclient": {
    "urls": [],
    "summaries": []
  },
  "python-gnupg": {
    "urls": [],
    "summaries": []
  },
  "python-gradunwarp": {
    "urls": [],
    "summaries": []
  },
  "python-graphviz": {
    "urls": [],
    "summaries": []
  },
  "python-grip": {
    "urls": [],
    "summaries": []
  },
  "python-gsd": {
    "urls": [],
    "summaries": []
  },
  "python-gunicorn": {
    "urls": [],
    "summaries": []
  },
  "python-h2": {
    "urls": [],
    "summaries": []
  },
  "python-h5io": {
    "urls": [],
    "summaries": []
  },
  "python-h5netcdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325222"
    ],
    "summaries": [
      "python-h5netcdf fails to build with Python 3.14: test_no_circular_references: AssertionError"
    ]
  },
  "python-habitipy": {
    "urls": [],
    "summaries": []
  },
  "python-hamcrest": {
    "urls": [],
    "summaries": []
  },
  "python-haversion": {
    "urls": [],
    "summaries": []
  },
  "python-hdf5storage": {
    "urls": [],
    "summaries": []
  },
  "python-hexbytes": {
    "urls": [],
    "summaries": []
  },
  "python-hid-parser": {
    "urls": [],
    "summaries": []
  },
  "python-html5-parser": {
    "urls": [],
    "summaries": []
  },
  "python-html5lib": {
    "urls": [],
    "summaries": []
  },
  "python-httmock": {
    "urls": [],
    "summaries": []
  },
  "python-httpretty": {
    "urls": [],
    "summaries": []
  },
  "python-humanize": {
    "urls": [],
    "summaries": []
  },
  "python-hvac": {
    "urls": [],
    "summaries": []
  },
  "python-ibm-vpc": {
    "urls": [],
    "summaries": []
  },
  "python-icalendar": {
    "urls": [],
    "summaries": []
  },
  "python-imageio": {
    "urls": [],
    "summaries": []
  },
  "python-img2pdf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328707"
    ],
    "summaries": [
      "python-img2pdf fails to build in rawhide: 48 AssertionErrors"
    ]
  },
  "python-indexed_gzip": {
    "urls": [],
    "summaries": []
  },
  "python-influxdb-client": {
    "urls": [],
    "summaries": []
  },
  "python-iniparse": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323164"
    ],
    "summaries": [
      "python-iniparse fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestIni.test_queue.<locals>.getxy at 0x7f86659a7740>"
    ]
  },
  "python-inject": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327978"
    ],
    "summaries": [
      "python-inject fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-inkex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331350"
    ],
    "summaries": [
      "python-inkex fails to build with Python 3.14: InxTestCase.test_inx_files: ValueError: badly formed help string"
    ]
  },
  "python-ipuz": {
    "urls": [],
    "summaries": []
  },
  "python-ipykernel": {
    "urls": [],
    "summaries": []
  },
  "python-ipyparallel": {
    "urls": [],
    "summaries": []
  },
  "python-irc": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327991"
    ],
    "summaries": [
      "python-irc fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-iso3166": {
    "urls": [],
    "summaries": []
  },
  "python-iso8601": {
    "urls": [],
    "summaries": []
  },
  "python-jack-client": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319666"
    ],
    "summaries": [
      "python-jack-client fails to build with setuptools 74+"
    ]
  },
  "python-jaconv": {
    "urls": [],
    "summaries": []
  },
  "python-jaraco-packaging": {
    "urls": [],
    "summaries": []
  },
  "python-jaraco-stream": {
    "urls": [],
    "summaries": []
  },
  "python-jedi": {
    "urls": [],
    "summaries": []
  },
  "python-jeepney": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327982"
    ],
    "summaries": [
      "python-jeepney fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-jmespath": {
    "urls": [],
    "summaries": []
  },
  "python-joblib": {
    "urls": [],
    "summaries": []
  },
  "python-josepy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323171"
    ],
    "summaries": [
      "python-josepy fails to build with Python 3.14: 6x ValueError: Field `alg` in JSONObject `Header` has no type annotation."
    ]
  },
  "python-json5": {
    "urls": [],
    "summaries": []
  },
  "python-jsondiff": {
    "urls": [],
    "summaries": []
  },
  "python-jsonpath-ng": {
    "urls": [],
    "summaries": []
  },
  "python-jsonref": {
    "urls": [],
    "summaries": []
  },
  "python-jsonschema-path": {
    "urls": [],
    "summaries": []
  },
  "python-junit_xml": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-c-kernel": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-client": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-console": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-kernel-singular": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-kernel-test": {
    "urls": [],
    "summaries": []
  },
  "python-jupyter-polymake": {
    "urls": [],
    "summaries": []
  },
  "python-keystoneauth1": {
    "urls": [],
    "summaries": []
  },
  "python-kitchen": {
    "urls": [],
    "summaries": []
  },
  "python-klusta": {
    "urls": [],
    "summaries": []
  },
  "python-lazy-loader": {
    "urls": [],
    "summaries": []
  },
  "python-lazy-object-proxy": {
    "urls": [],
    "summaries": []
  },
  "python-lazy_load": {
    "urls": [],
    "summaries": []
  },
  "python-lazyarray": {
    "urls": [],
    "summaries": []
  },
  "python-ldap3": {
    "urls": [],
    "summaries": []
  },
  "python-libNeuroML": {
    "urls": [],
    "summaries": []
  },
  "python-libarchive-c": {
    "urls": [],
    "summaries": []
  },
  "python-libcst": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328019"
    ],
    "summaries": [
      "python-libcst fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-libusb1": {
    "urls": [],
    "summaries": []
  },
  "python-logutils": {
    "urls": [],
    "summaries": []
  },
  "python-lqrt": {
    "urls": [],
    "summaries": []
  },
  "python-lru-dict": {
    "urls": [],
    "summaries": []
  },
  "python-lupa": {
    "urls": [],
    "summaries": []
  },
  "python-lxml": {
    "urls": [],
    "summaries": []
  },
  "python-lxml-html-clean": {
    "urls": [],
    "summaries": []
  },
  "python-lz4": {
    "urls": [],
    "summaries": []
  },
  "python-makefun": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328706"
    ],
    "summaries": [
      "python-makefun fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-manuel": {
    "urls": [],
    "summaries": []
  },
  "python-mapbox-earcut": {
    "urls": [],
    "summaries": []
  },
  "python-matplotlib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328713"
    ],
    "summaries": [
      "python-matplotlib fails to build with Python 3.14: RecursionError: maximum recursion depth exceeded"
    ]
  },
  "python-mbstrdecoder": {
    "urls": [],
    "summaries": []
  },
  "python-mccabe": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328016"
    ],
    "summaries": [
      "python-mccabe fails to build with Python 3.14: AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-mediafile": {
    "urls": [],
    "summaries": []
  },
  "python-merge3": {
    "urls": [],
    "summaries": []
  },
  "python-mergedeep": {
    "urls": [],
    "summaries": []
  },
  "python-meson-python": {
    "urls": [],
    "summaries": []
  },
  "python-messaging": {
    "urls": [],
    "summaries": []
  },
  "python-migen": {
    "urls": [],
    "summaries": []
  },
  "python-mirrors-countme": {
    "urls": [],
    "summaries": []
  },
  "python-mmtf": {
    "urls": [],
    "summaries": []
  },
  "python-mnemonic": {
    "urls": [],
    "summaries": []
  },
  "python-mockito": {
    "urls": [],
    "summaries": []
  },
  "python-more-itertools": {
    "urls": [],
    "summaries": []
  },
  "python-morphys": {
    "urls": [],
    "summaries": []
  },
  "python-mrcfile": {
    "urls": [],
    "summaries": []
  },
  "python-msal": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323170"
    ],
    "summaries": [
      "python-msal fails to build with Python 3.14: test_no_two_concurrent_receivers_can_listen_on_same_port: AssertionError: OSError not raised"
    ]
  },
  "python-msgspec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325169"
    ],
    "summaries": [
      "python-msgspec fails to build with Python 3.14: error: \u2018_Py_IMMORTAL_REFCNT\u2019 undeclared here"
    ]
  },
  "python-msrest": {
    "urls": [],
    "summaries": []
  },
  "python-msrestazure": {
    "urls": [],
    "summaries": []
  },
  "python-multiaddr": {
    "urls": [],
    "summaries": []
  },
  "python-multibase": {
    "urls": [],
    "summaries": []
  },
  "python-multicodec": {
    "urls": [],
    "summaries": []
  },
  "python-multihash": {
    "urls": [],
    "summaries": []
  },
  "python-mutagen": {
    "urls": [],
    "summaries": []
  },
  "python-mwclient": {
    "urls": [],
    "summaries": []
  },
  "python-natsort": {
    "urls": [],
    "summaries": []
  },
  "python-ncclient": {
    "urls": [],
    "summaries": []
  },
  "python-ndindex": {
    "urls": [],
    "summaries": []
  },
  "python-neovim": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326224"
    ],
    "summaries": [
      "python-neovim fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'get_child_watcher'"
    ]
  },
  "python-nibabel": {
    "urls": [],
    "summaries": []
  },
  "python-nine": {
    "urls": [],
    "summaries": []
  },
  "python-nmrglue": {
    "urls": [],
    "summaries": []
  },
  "python-normality": {
    "urls": [],
    "summaries": []
  },
  "python-nose": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323163"
    ],
    "summaries": [
      "python-nose fails to build with Python 3.14: multiple AssertionErrors related to timeouts in test outputs"
    ]
  },
  "python-nose2": {
    "urls": [],
    "summaries": []
  },
  "python-nuheat": {
    "urls": [],
    "summaries": []
  },
  "python-numexpr": {
    "urls": [],
    "summaries": []
  },
  "python-numpy-stl": {
    "urls": [],
    "summaries": []
  },
  "python-odata-query": {
    "urls": [],
    "summaries": []
  },
  "python-omsdk": {
    "urls": [],
    "summaries": []
  },
  "python-openctm": {
    "urls": [],
    "summaries": []
  },
  "python-openidc-client": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319685"
    ],
    "summaries": [
      "python-openidc-client fails to build with setuptools 74+"
    ]
  },
  "python-openpaperwork-core": {
    "urls": [],
    "summaries": []
  },
  "python-openqa_client": {
    "urls": [],
    "summaries": []
  },
  "python-opensearch-py": {
    "urls": [],
    "summaries": []
  },
  "python-openstep-plist": {
    "urls": [],
    "summaries": []
  },
  "python-opytimark": {
    "urls": [],
    "summaries": []
  },
  "python-orjson": {
    "urls": [],
    "summaries": []
  },
  "python-oscrypto": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-concurrency": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-i18n": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-serialization": {
    "urls": [],
    "summaries": []
  },
  "python-oslo-utils": {
    "urls": [],
    "summaries": []
  },
  "python-oslotest": {
    "urls": [],
    "summaries": []
  },
  "python-overpy": {
    "urls": [],
    "summaries": []
  },
  "python-paginate": {
    "urls": [],
    "summaries": []
  },
  "python-pandas": {
    "urls": [],
    "summaries": []
  },
  "python-pandas-datareader": {
    "urls": [],
    "summaries": []
  },
  "python-pari-jupyter": {
    "urls": [],
    "summaries": []
  },
  "python-parse_type": {
    "urls": [],
    "summaries": []
  },
  "python-parsel": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319689"
    ],
    "summaries": [
      "python-parsel fails to build with setuptools 74+"
    ]
  },
  "python-parsimonious": {
    "urls": [],
    "summaries": []
  },
  "python-parso": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325187"
    ],
    "summaries": [
      "python-parso fails to build with Python 3.14: NotImplementedError: Python version 3.14 is currently not supported."
    ]
  },
  "python-parver": {
    "urls": [],
    "summaries": []
  },
  "python-paste-script": {
    "urls": [],
    "summaries": []
  },
  "python-patsy": {
    "urls": [],
    "summaries": []
  },
  "python-pdfkit": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319690"
    ],
    "summaries": [
      "python-pdfkit fails to build with setuptools 74+"
    ]
  },
  "python-pdir2": {
    "urls": [],
    "summaries": []
  },
  "python-pdm-backend": {
    "urls": [],
    "summaries": []
  },
  "python-periodictable": {
    "urls": [],
    "summaries": []
  },
  "python-pexpect": {
    "urls": [],
    "summaries": []
  },
  "python-pikepdf": {
    "urls": [],
    "summaries": []
  },
  "python-pillow": {
    "urls": [],
    "summaries": []
  },
  "python-pip": {
    "urls": [],
    "summaries": []
  },
  "python-pluggy1.3": {
    "urls": [],
    "summaries": []
  },
  "python-portalocker": {
    "urls": [],
    "summaries": []
  },
  "python-pox": {
    "urls": [],
    "summaries": []
  },
  "python-priority": {
    "urls": [],
    "summaries": []
  },
  "python-psycogreen": {
    "urls": [],
    "summaries": []
  },
  "python-pulp-glue": {
    "urls": [],
    "summaries": []
  },
  "python-pure-eval": {
    "urls": [],
    "summaries": []
  },
  "python-pure-protobuf": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322710"
    ],
    "summaries": [
      "python-pure-protobuf fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python-puzpy": {
    "urls": [],
    "summaries": []
  },
  "python-pyaes": {
    "urls": [],
    "summaries": []
  },
  "python-pybbi": {
    "urls": [],
    "summaries": []
  },
  "python-pybeam": {
    "urls": [],
    "summaries": []
  },
  "python-pybtex": {
    "urls": [],
    "summaries": []
  },
  "python-pybtex-docutils": {
    "urls": [],
    "summaries": []
  },
  "python-pycec": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327973"
    ],
    "summaries": [
      "python-pycec fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-pyclipper": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319696"
    ],
    "summaries": [
      "python-pyclipper fails to build with setuptools 74+"
    ]
  },
  "python-pycoingecko": {
    "urls": [],
    "summaries": []
  },
  "python-pydantic-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325425"
    ],
    "summaries": [
      "python-pydantic-core fails to build with Python 3.14: AssertionError: Regex pattern did not match. + AttributeError: module 'typing' has no attribute 'ByteString'"
    ]
  },
  "python-pydepsdev": {
    "urls": [],
    "summaries": []
  },
  "python-pydispatcher": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319697"
    ],
    "summaries": [
      "python-pydispatcher fails to build with setuptools 74+"
    ]
  },
  "python-pyemd": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319698"
    ],
    "summaries": [
      "python-pyemd fails to build with setuptools 74+"
    ]
  },
  "python-pyerfa": {
    "urls": [],
    "summaries": []
  },
  "python-pyface": {
    "urls": [],
    "summaries": []
  },
  "python-pygit2": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328023"
    ],
    "summaries": [
      "python-pygit2 fails to build with Python 3.14: TypeError: 'GenericIterator' object is not iterable"
    ]
  },
  "python-pygments-git": {
    "urls": [],
    "summaries": []
  },
  "python-pygments-style-solarized": {
    "urls": [],
    "summaries": []
  },
  "python-pygmtools": {
    "urls": [],
    "summaries": []
  },
  "python-pyiqvia": {
    "urls": [],
    "summaries": []
  },
  "python-pykcs11": {
    "urls": [],
    "summaries": []
  },
  "python-pymatreader": {
    "urls": [],
    "summaries": []
  },
  "python-pymdown-extensions": {
    "urls": [],
    "summaries": []
  },
  "python-pymeeus": {
    "urls": [],
    "summaries": []
  },
  "python-pymilter": {
    "urls": [],
    "summaries": []
  },
  "python-pymongo": {
    "urls": [],
    "summaries": []
  },
  "python-pynacl": {
    "urls": [],
    "summaries": []
  },
  "python-pyongc": {
    "urls": [],
    "summaries": []
  },
  "python-pyopencl": {
    "urls": [],
    "summaries": []
  },
  "python-pyopengl": {
    "urls": [],
    "summaries": []
  },
  "python-pypdf": {
    "urls": [],
    "summaries": []
  },
  "python-pyqt-feedback-flow": {
    "urls": [],
    "summaries": []
  },
  "python-pyqtgraph": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid-tm": {
    "urls": [],
    "summaries": []
  },
  "python-pyramid_sawing": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319702"
    ],
    "summaries": [
      "python-pyramid_sawing fails to build with setuptools 74+"
    ]
  },
  "python-pyroaring": {
    "urls": [],
    "summaries": []
  },
  "python-pyrsistent": {
    "urls": [],
    "summaries": []
  },
  "python-pyscaffold": {
    "urls": [],
    "summaries": []
  },
  "python-pyside6": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325444"
    ],
    "summaries": [
      "python-pyside6 fails to build with Python 3.14: TypeError: Formatter.formatannotation() got an unexpected keyword argument 'quote_annotation_strings'"
    ]
  },
  "python-pyspike": {
    "urls": [],
    "summaries": []
  },
  "python-pysqueezebox": {
    "urls": [],
    "summaries": []
  },
  "python-pysrt": {
    "urls": [],
    "summaries": []
  },
  "python-pytaglib": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319705"
    ],
    "summaries": [
      "python-pytaglib fails to build with setuptools 74+"
    ]
  },
  "python-pytesseract": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-aiohttp": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-arraydiff": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-asyncio": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-bdd": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-cid": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-console-scripts": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-datadir": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-dependency": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-django": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-fixture-config": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-flakes": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319708"
    ],
    "summaries": [
      "python-pytest-flakes fails to build with setuptools 74+"
    ]
  },
  "python-pytest-jupyter": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-localserver": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-randomly": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-rerunfailures": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327998"
    ],
    "summaries": [
      "python-pytest-rerunfailures fails to build with Python 3.14: remains unmatched: 'session teardown'"
    ]
  },
  "python-pytest-runner": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319709"
    ],
    "summaries": [
      "python-pytest-runner fails to build with setuptools 74+"
    ]
  },
  "python-pytest-sourceorder": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-timeout": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-tldr": {
    "urls": [],
    "summaries": []
  },
  "python-pytest-trio": {
    "urls": [],
    "summaries": []
  },
  "python-pytz-deprecation-shim": {
    "urls": [],
    "summaries": []
  },
  "python-pyupgrade": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322713"
    ],
    "summaries": [
      "python-pyupgrade fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-pyvlx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327983"
    ],
    "summaries": [
      "python-pyvlx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-qtconsole": {
    "urls": [],
    "summaries": []
  },
  "python-rdflib": {
    "urls": [],
    "summaries": []
  },
  "python-reactivex": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327987"
    ],
    "summaries": [
      "python-reactivex fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-readability-lxml": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323185"
    ],
    "summaries": [
      "python-readability-lxml fails to build with Python 3.14: _pickle.PicklingError: Can't pickle <function TestArticleOnly.test_many_repeated_spaces at 0x7ff0ea064460>: it's not the same object as tests.test_article_only.TestArticleOnly.test_many_repeated_spa"
    ]
  },
  "python-recordclass": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327968"
    ],
    "summaries": [
      "python-recordclass fails to build with Python 3.14: 25 failures, 65 errors in the test suite"
    ]
  },
  "python-redis": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326927"
    ],
    "summaries": [
      "python-redis fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_redis_client.<locals>.target at 0x7fd5f829efb0>"
    ]
  },
  "python-remoto": {
    "urls": [],
    "summaries": []
  },
  "python-reportlab": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2331341"
    ],
    "summaries": [
      "python-reportlab fails to build with Python 3.14: AttributeError: module 'ast' has no attribute 'Str'"
    ]
  },
  "python-repoze-lru": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319711"
    ],
    "summaries": [
      "python-repoze-lru fails to build with setuptools 74+"
    ]
  },
  "python-requests-credssp": {
    "urls": [],
    "summaries": []
  },
  "python-requests-gssapi": {
    "urls": [],
    "summaries": []
  },
  "python-requests-kerberos": {
    "urls": [],
    "summaries": []
  },
  "python-requests-toolbelt": {
    "urls": [],
    "summaries": []
  },
  "python-requests_ntlm": {
    "urls": [],
    "summaries": []
  },
  "python-rfc3339-validator": {
    "urls": [],
    "summaries": []
  },
  "python-rfc3986-validator": {
    "urls": [],
    "summaries": []
  },
  "python-rich": {
    "urls": [],
    "summaries": []
  },
  "python-rmtest": {
    "urls": [],
    "summaries": []
  },
  "python-rpmautospec-koji": {
    "urls": [],
    "summaries": []
  },
  "python-rpmfluff": {
    "urls": [],
    "summaries": []
  },
  "python-rq": {
    "urls": [],
    "summaries": []
  },
  "python-rstcheck": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2322705"
    ],
    "summaries": [
      "python-rstcheck fails to build with Python 3.14: AttributeError: 'Constant' object has no attribute 's'"
    ]
  },
  "python-rust-update-set": {
    "urls": [],
    "summaries": []
  },
  "python-rx": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327979"
    ],
    "summaries": [
      "python-rx fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-s3transfer": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326933"
    ],
    "summaries": [
      "python-s3transfer fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <class 'tests.unit.test_compat.TestBaseManager.create_pid_manager.<locals>.PIDManager'>"
    ]
  },
  "python-selenium": {
    "urls": [],
    "summaries": []
  },
  "python-sep": {
    "urls": [],
    "summaries": []
  },
  "python-serpy": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319716"
    ],
    "summaries": [
      "python-serpy fails to build with setuptools 74+"
    ]
  },
  "python-setuptools-rust": {
    "urls": [],
    "summaries": []
  },
  "python-sgqlc": {
    "urls": [],
    "summaries": []
  },
  "python-simple-websocket": {
    "urls": [],
    "summaries": []
  },
  "python-simplegeneric": {
    "urls": [],
    "summaries": []
  },
  "python-simplevisor": {
    "urls": [],
    "summaries": []
  },
  "python-singledispatch": {
    "urls": [],
    "summaries": []
  },
  "python-slacker": {
    "urls": [],
    "summaries": []
  },
  "python-smbprotocol": {
    "urls": [],
    "summaries": []
  },
  "python-snuggs": {
    "urls": [],
    "summaries": []
  },
  "python-social-auth-core": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328010"
    ],
    "summaries": [
      "python-social-auth-core fails to build with Python 3.14: 'SSLContext' object has no attribute 'close'"
    ]
  },
  "python-sphinx-autoapi": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-blockdiag": {
    "urls": [],
    "summaries": []
  },
  "python-sphinxcontrib-seqdiag": {
    "urls": [],
    "summaries": []
  },
  "python-spotipy": {
    "urls": [],
    "summaries": []
  },
  "python-spyder-kernels": {
    "urls": [],
    "summaries": []
  },
  "python-sqlalchemy1.4": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327976"
    ],
    "summaries": [
      "python-sqlalchemy1.4 fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-sshpubkeys": {
    "urls": [],
    "summaries": []
  },
  "python-statsmodels": {
    "urls": [],
    "summaries": []
  },
  "python-stdlibs": {
    "urls": [],
    "summaries": []
  },
  "python-surt": {
    "urls": [],
    "summaries": []
  },
  "python-svg2tikz": {
    "urls": [],
    "summaries": []
  },
  "python-tables": {
    "urls": [],
    "summaries": []
  },
  "python-tabulate": {
    "urls": [],
    "summaries": []
  },
  "python-tenacity": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327977"
    ],
    "summaries": [
      "python-tenacity fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-terminado": {
    "urls": [],
    "summaries": []
  },
  "python-teslajsonpy": {
    "urls": [],
    "summaries": []
  },
  "python-tgscheduler": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319728"
    ],
    "summaries": [
      "python-tgscheduler fails to build with setuptools 74+"
    ]
  },
  "python-tinygrad": {
    "urls": [],
    "summaries": []
  },
  "python-toolz": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323168"
    ],
    "summaries": [
      "python-toolz fails to build with Python 3.14: AssertionError: is_none: assert should_curry(getattr(operator, k)) == isinstance(v, toolz.curry), k"
    ]
  },
  "python-tornado": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327969"
    ],
    "summaries": [
      "python-tornado fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-tpm2-pytss": {
    "urls": [],
    "summaries": []
  },
  "python-tree-format": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319731"
    ],
    "summaries": [
      "python-tree-format fails to build with setuptools 74+"
    ]
  },
  "python-trio-websocket": {
    "urls": [],
    "summaries": []
  },
  "python-tvb-gdist": {
    "urls": [],
    "summaries": []
  },
  "python-twisted": {
    "urls": [],
    "summaries": []
  },
  "python-txaio": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327981"
    ],
    "summaries": [
      "python-txaio fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-typeguard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328015"
    ],
    "summaries": [
      "python-typeguard fails to build with Python 3.14: typeguard.TypeCheckError: argument \"x\" (class dummymodule.DummyClass) is not a subclass of dummymodule.DummyClass && AssertionError: Regex pattern did not match."
    ]
  },
  "python-typing-extensions": {
    "urls": [],
    "summaries": []
  },
  "python-typing-inspect": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325455"
    ],
    "summaries": [
      "python-typing-inspect fails to build with Python 3.14: AssertionError: {} != {'x': <class 'int'>, 'y': <class 'int'>}"
    ]
  },
  "python-urwid": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2327984"
    ],
    "summaries": [
      "python-urwid fails to build with Python 3.14: RuntimeError: There is no current event loop in thread 'MainThread'."
    ]
  },
  "python-uvloop": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326210"
    ],
    "summaries": [
      "python-uvloop fails to build with Python 3.14: AttributeError: module 'asyncio' has no attribute 'AbstractChildWatcher'"
    ]
  },
  "python-valkey": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326934"
    ],
    "summaries": [
      "python-valkey fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestMultiprocessing.test_close_connection_in_child.<locals>.target at 0x7f7d711b5dd0>"
    ]
  },
  "python-virtualenv": {
    "urls": [],
    "summaries": []
  },
  "python-vsts": {
    "urls": [],
    "summaries": []
  },
  "python-wcag-contrast-ratio": {
    "urls": [],
    "summaries": []
  },
  "python-webscrapbook": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326915"
    ],
    "summaries": [
      "python-webscrapbook fails to build with Python 3.14: 60x AssertionError in the test suite"
    ]
  },
  "python-whoosh": {
    "urls": [],
    "summaries": []
  },
  "python-winrm": {
    "urls": [],
    "summaries": []
  },
  "python-wled": {
    "urls": [],
    "summaries": []
  },
  "python-xunitparser": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319738"
    ],
    "summaries": [
      "python-xunitparser fails to build with setuptools 74+"
    ]
  },
  "python-yamlloader": {
    "urls": [],
    "summaries": []
  },
  "python-yappi": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2323160"
    ],
    "summaries": [
      "python-yappi fails to build with Python 3.14: error: invalid use of incomplete typedef \u2018PyGenObject\u2019 {aka \u2018struct _PyGenObject\u2019}"
    ]
  },
  "python-zc-lockfile": {
    "urls": [],
    "summaries": []
  },
  "python-zict": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328012"
    ],
    "summaries": [
      "python-zict fails to build with Python 3.14: test_stress_different_keys_threadsafe Timeout"
    ]
  },
  "python-zmq": {
    "urls": [],
    "summaries": []
  },
  "python-zope-deprecation": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319742"
    ],
    "summaries": [
      "python-zope-deprecation fails to build with setuptools 74+"
    ]
  },
  "python-zope-testing": {
    "urls": [],
    "summaries": []
  },
  "python-zope-testrunner": {
    "urls": [],
    "summaries": []
  },
  "python-zstandard": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2326925"
    ],
    "summaries": [
      "python-zstandard fails to build with Python 3.14: ImportError: cannot import name 'ByteString' from 'typing'"
    ]
  },
  "python3-exiv2": {
    "urls": [],
    "summaries": []
  },
  "pyzor": {
    "urls": [],
    "summaries": []
  },
  "qgis": {
    "urls": [],
    "summaries": []
  },
  "qtile": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2328711"
    ],
    "summaries": [
      "qtile fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestManager.start.<locals>.run_qtile at 0x7f9c5918fed0>"
    ]
  },
  "radicale": {
    "urls": [],
    "summaries": []
  },
  "rapidyaml": {
    "urls": [],
    "summaries": []
  },
  "re2": {
    "urls": [],
    "summaries": []
  },
  "realtime-tests": {
    "urls": [],
    "summaries": []
  },
  "rmol": {
    "urls": [],
    "summaries": []
  },
  "root": {
    "urls": [],
    "summaries": []
  },
  "satyr": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325452"
    ],
    "summaries": [
      "satyr fails to build with Python 3.14: _pickle.PicklingError: Can't pickle local object <function TestDistances.test_distances_part_parallel.<locals>.do_test.<locals>.compute_part at 0x7f7f845f2560>"
    ]
  },
  "scipy": {
    "urls": [],
    "summaries": []
  },
  "sentencepiece": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2319749"
    ],
    "summaries": [
      "sentencepiece fails to build with setuptools 74+"
    ]
  },
  "sherlock-project": {
    "urls": [],
    "summaries": []
  },
  "strongswan": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2332864"
    ],
    "summaries": [
      "strongswan-5.9.14-5.fc42 FTBFS: strongswan-5.9.14/missing: line 81: aclocal-1.16: command not found"
    ]
  },
  "subunit": {
    "urls": [],
    "summaries": []
  },
  "syncplay": {
    "urls": [],
    "summaries": []
  },
  "totpcgi": {
    "urls": [],
    "summaries": []
  },
  "trademgen": {
    "urls": [],
    "summaries": []
  },
  "urh": {
    "urls": [],
    "summaries": []
  },
  "visidata": {
    "urls": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=2325446"
    ],
    "summaries": [
      "visidata fails to build with Python 3.14: TestVisidataPath.test_withName: AssertionError: assert 'foo' == 'foo.'"
    ]
  },
  "vtk": {
    "urls": [],
    "summaries": []
  },
  "weasyprint": {
    "urls": [],
    "summaries": []
  },
  "xpra": {
    "urls": [],
    "summaries": []
  },
  "xrootd": {
    "urls": [],
    "summaries": []
  },
  "yamllint": {
    "urls": [],
    "summaries": []
  }
}